"""Turn the extracted fortress-killer roster into the C# table the AI reads.

CLI:
    python emit_fortress_killers_table.py out/fortress_killers.tsv <out.cs>
"""
from __future__ import annotations

import argparse
import collections
import pathlib

HEADER = '''// <auto-generated>
//     Generated by tools/client-extract/emit_fortress_killers_table.py from the retail AI patterns.
//     Do not edit by hand: re-run the extractor instead. See docs/retail-ai-fidelity.md.
// </auto-generated>

using Aion.GameServer.Ai.Pattern;
using Aion.GameServer.Model;

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// What a fortress killer does besides answering messages: its wake call, its walk, and its quarry.
/// </summary>
/// <remarks>
/// {rows} killers across {patterns} retail patterns, and <b>they are not uniform</b>, which is why this
/// is a table and not three constants: {shapes}.
/// <para>
/// <b>Nineteen of them hunt on sight.</b> <c>LDF4_Advance_Killer_43</c> tests a seen npc's race against
/// <c>gchief_dragon</c>, <c>gchief_light</c> and <c>gchief_dark</c> and drops <b>a million hate</b> on
/// it — that is what makes an Advance killer walk into a garrison and go for the chief instead of
/// wandering into whoever is nearest. It is the largest killer family in the game and none of it ran.
/// </para>
/// <para>
/// <b>Seventeen walk.</b> Retail sends them off with <c>goto_waypoint</c> as they wake and
/// <c>goto_next_waypoint</c> when a fight ends. The rest stand where they spawned, in retail as here.
/// </para>
/// </remarks>
internal static class FortressKillers
{{
    /// <param name="WakeRange">Retail's <c>range_as_meter</c> on the 30001 it shouts as it wakes.</param>
    /// <param name="Walks">Whether retail puts it on its route.</param>
    /// <param name="SightHate">Hate dropped on a garrison chief it sees, or 0 for a killer that waits.</param>
    /// <param name="Hunted">The chief races it reacts to.</param>
    internal readonly record struct Killer(float WakeRange, bool Walks, int SightHate, Race[] Hunted);

    internal static readonly IReadOnlyDictionary<int, Killer> ByNpc = new Dictionary<int, Killer>
    {{
'''

FOOTER = '''    };

    private static readonly System.Collections.Concurrent.ConcurrentDictionary<int, AiPattern> Built =
        new System.Collections.Concurrent.ConcurrentDictionary<int, AiPattern>();

    private static readonly AiPattern Nothing = new AiPattern();

    /// <summary>The wake call, the walk and the hunt for one killer.</summary>
    /// <remarks>
    /// Built here rather than in <see cref="FortressKillerAI"/> for the same reason
    /// <see cref="ProtectorCalls"/> is: the numbers and the branches that read them belong together, and
    /// a killer absent from the table gets an empty pattern rather than a default that would be wrong.
    /// </remarks>
    internal static AiPattern PatternFor(int npcId) => Built.GetOrAdd(npcId, static id =>
    {
        if (!ByNpc.TryGetValue(id, out Killer killer))
            return Nothing;

        List<PatternBranch> waking =
        [
            AiPattern.Branch(95, "tell the guards I am here", When.Always,
                Do.BroadcastAboutSelf(FortressKillerAI.KillerAwake, killer.WakeRange)),
        ];
        if (killer.Walks)
            waking.Add(AiPattern.Branch(94, "and set off", When.Always, Do.StartWalking()));

        return new AiPattern
        {
            OnWakeUp = [.. waking],

            OnLeaveAttack = killer.Walks
                ? AiPattern.Of(AiPattern.Branch(94, "back to the route", When.Always, Do.StartWalking()))
                : AiPattern.Of(),

            OnSeeNpc = killer.SightHate == 0
                ? AiPattern.Of()
                : AiPattern.Of(AiPattern.Branch(30, "a garrison chief; that is what I came for",
                    [When.SeenRace(killer.Hunted)],
                    Do.HateSeen(killer.SightHate))),
        };
    });
}
'''


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("tsv", type=pathlib.Path)
    ap.add_argument("out", type=pathlib.Path)
    args = ap.parse_args()

    rows = []
    patterns: set[str] = set()
    shapes: collections.Counter[str] = collections.Counter()
    for line in args.tsv.read_text(encoding="utf-8").splitlines()[1:]:
        npc, reach, walks, hate, races, pattern = line.split("\t")
        rows.append((int(npc), int(reach), walks, int(hate), races, pattern))
        patterns.add(pattern)
        shapes[f"{reach}m wake call"] += 1

    spread = ", ".join(f"{n} at a {m}" for m, n in shapes.most_common())
    header = HEADER.format(rows=len(rows), patterns=len(patterns), shapes=spread)

    with args.out.open("w", encoding="utf-8", newline="\n") as out:
        out.write(header)
        for npc, reach, walks, hate, races, pattern in rows:
            hunted = ", ".join(f"Race.{r}" for r in races.split("|") if r)
            out.write(f"        [{npc}] = new Killer({reach}f, {walks}, {hate}, [{hunted}]),"
                      f"  // {pattern}\n")
        out.write(FOOTER)

    print(f"{len(rows)} rows -> {args.out}")


if __name__ == "__main__":
    main()
