"""Transcribe death_spawns.tsv into DeathSpawns.cs. See extract_death_spawns.py for the claim."""
from __future__ import annotations

import argparse
import collections
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from emit_battle_cycles_table import CHUNK, action_code, guard_code  # noqa: E402

HEADER = '''// <auto-generated>
//     Generated by tools/client-extract/emit_death_spawns_table.py from out/death_spawns.tsv.
//     Do not edit by hand; edit the extractor and re-run.
// </auto-generated>
using Aion.GameServer.Ai.Pattern;
using Aion.GameServer.Controllers.Attack;
using Aion.GameServer.Model.Templates.Npcskill;

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// What a retail npc leaves behind when it dies: {patterns} patterns across {npcs} npcs, {actions} actions.
/// </summary>
/// <remarks>
/// The encounters no rotation table can reach. <see cref="BattleCycles"/> reads <c>on_die</c> too, but
/// it is keyed on a battle-timer chain, and <b>179 of the encounters still missing an add have no
/// rotation at all</b> -- there is nothing there to hang a death handler off. A death spawn is not part
/// of a rotation; it needs a table keyed on dying, which is this one.
/// <para>
/// Retail splits <c>on_die</c> from <c>on_killed_by_user</c>: the first fires however the npc died, the
/// second only when a player did it. This port has one slot and <see cref="When.KilledByPlayer"/>,
/// which is exactly that distinction, so the second is emitted as the first plus that guard.
/// </para>
/// <para>
/// <see cref="DeathSpawnAI"/>'s own nine hand-read npcs are excluded from generation and keep their
/// entries: they carry curated notes, and one of them encodes a judgement about a betrayer npc that is
/// worth not regenerating over.
/// </para>
/// </remarks>
internal static class DeathSpawns
{{
    /// <summary>What this npc leaves behind, or empty for one that leaves nothing.</summary>
    internal static PatternBranch[] RungsFor(int npcId)
        => Rungs.TryGetValue(npcId, out PatternBranch[]? rungs) ? rungs : [];

    /// <summary>Every npc this table drives.</summary>
    internal static IEnumerable<int> Npcs => Rungs.Keys;

'''

FOOTER = '''}
'''


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("tsv", type=pathlib.Path)
    ap.add_argument("out", type=pathlib.Path)
    args = ap.parse_args()

    lines = args.tsv.read_text(encoding="utf-8").splitlines()
    header = lines[0].split("\t")
    branches: dict[int, dict[tuple[str, int], list[dict]]] = collections.defaultdict(
        lambda: collections.defaultdict(list))
    meta: dict[tuple[int, str, int], tuple[int, str, bool]] = {}
    names: dict[int, str] = {}
    actions = 0
    for line in lines[1:]:
        row = dict(zip(header, line.split("\t")))
        npc, branch = int(row["npc"]), int(row["branch"])
        key = (row["handler"], branch)
        names[npc] = row["pattern"]
        meta[(npc, row["handler"], branch)] = (int(row["priority"]), row["guards"],
                                               row["player_only"] == "TRUE")
        branches[npc][key].append(row)
        actions += 1

    npcs = sorted(branches)
    chunks = [npcs[i:i + CHUNK] for i in range(0, len(npcs), CHUNK)] or [[]]

    with args.out.open("w", encoding="utf-8", newline="\n") as out:
        out.write(HEADER.format(patterns=len(set(names.values())), npcs=len(names), actions=actions))
        out.write("    private static readonly IReadOnlyDictionary<int, PatternBranch[]> Rungs =\n")
        out.write("        BuildRungs();\n\n")
        out.write("    private static Dictionary<int, PatternBranch[]> BuildRungs()\n    {\n")
        out.write("        Dictionary<int, PatternBranch[]> rungs = "
                  "new Dictionary<int, PatternBranch[]>();\n")
        for index in range(len(chunks)):
            out.write(f"        Rungs{index}(rungs);\n")
        out.write("        return rungs;\n    }\n\n")

        for index, chunk in enumerate(chunks):
            out.write(f"    private static void Rungs{index}"
                      "(Dictionary<int, PatternBranch[]> rungs)\n    {\n")
            for npc in chunk:
                out.write(f"        rungs[{npc}] = [  // {names[npc]}\n")
                for handler, branch in sorted(branches[npc]):
                    priority, guards, player_only = meta[(npc, handler, branch)]
                    tokens = [guard_code(t) for t in guards.split("|") if t]
                    # on_killed_by_user is on_die plus "a player did it".
                    if player_only:
                        tokens.insert(0, "When.KilledByPlayer")
                    condition = "When.Always" if not tokens else "[" + ", ".join(tokens) + "]"
                    body = ",\n".join("                " + action_code(r)
                                      for r in branches[npc][(handler, branch)])
                    out.write(f'            AiPattern.Branch({priority}, "{handler} {branch}", '
                              f'{condition},\n')
                    out.write(body + "),\n")
                out.write("        ];\n")
            out.write("    }\n\n")
        out.write(FOOTER)

    print(f"{len(set(names.values()))} patterns, {len(names)} npcs, {actions} actions -> {args.out}")


if __name__ == "__main__":
    main()
