"""Transcribe guard_answers.tsv into GuardAnswers.g.cs. See extract_guard_answers.py for the claim."""
from __future__ import annotations

import argparse
import collections
import pathlib
import xml.dom.minidom

XML_HEADER = '''<?xml version="1.0" encoding="UTF-8"?>
<!--
    Generated by tools/client-extract/emit_guard_answers_table.py from out/guard_answers.tsv.
    Do not edit by hand; edit the extractor and re-run.

    Who answers a guard's call for help, and with what weight: {rows} answers across {npcs} npcs.

    `call` is the message number the caller broadcasts. `idle` and `busy` are retail's hate weights
    for a guard standing about and one already in a fight; a negative `busy` means it does not answer
    while fighting. `aims_at_sender` marks the calls that name the caller rather than a player.
    GuardAnswers deliberately does not turn those into pattern rungs, because the classes that answer
    them carry their own actions.

    {common} answers use retail's common weighting and {odd} differ from it.

    This was 3,700 lines of C#. It is data, and it sits with the rest of the static data now; see
    GuardAnswerData for how it is read and GuardAnswers for what is done with it.
-->
<guard_answers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="guard_answers.xsd">
'''

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("tsv", type=pathlib.Path)
    ap.add_argument("out", type=pathlib.Path)
    args = ap.parse_args()

    by_npc: dict[int, list[tuple[int, int, int]]] = collections.defaultdict(list)
    names: dict[int, str] = {}
    common = odd = 0
    protectors = 0
    for line in args.tsv.read_text(encoding="utf-8").splitlines()[1:]:
        npc, call, idle, busy, sender, pattern = (line.split("\t") + [""] * 6)[:6]
        by_npc[int(npc)].append((int(call), int(idle), int(busy), int(sender)))
        names[int(npc)] = pattern
        if (int(idle), int(busy)) == (1, 100) and int(call) < 30000:
            common += 1
        else:
            odd += 1
        if int(call) == 23100:
            protectors += 1

    rows = sum(len(v) for v in by_npc.values())
    with args.out.open("w", encoding="utf-8", newline="\n") as out:
        out.write(XML_HEADER.format(rows=rows, npcs=len(by_npc), common=common, odd=odd))
        for npc in sorted(by_npc):
            # A comment cannot carry a double dash, and a pattern name is free to contain one.
            safe = names[npc].replace("--", "-")
            label = f"  <!-- {safe} -->" if safe else ""
            out.write(f'\t<guard npc_id="{npc}">{label}\n')
            for call, idle, busy, sender in sorted(by_npc[npc]):
                out.write(f'\t\t<answer call="{call}" idle="{idle}" busy="{busy}"'
                          f' aims_at_sender="{"true" if sender else "false"}" />\n')
            out.write("\t</guard>\n")
        out.write("</guard_answers>\n")

    # Parse what was just written. A double dash inside a comment is legal Python, legal-looking
    # prose, and an XML syntax error -- it has taken this suite down twice now, and the failure
    # arrives as two thousand unrelated red tests because DataManager cannot load at all.
    xml.dom.minidom.parse(str(args.out))

    print(f"{rows} answers across {len(by_npc)} npcs -> {args.out}")


if __name__ == "__main__":
    main()
