"""Transcribe Tiamat's rotation TSV into the C# table the AI reads.

Emitted as one flat list in document order rather than grouped by band, because
that is how retail evaluates it: priorities descend down the file and the first
branch whose guards pass wins. Grouping by band would lose the ordering between
bands, and this pattern has a place where that matters -- `BreathL_75-51` guards
`51..74` where the M and R steps beside it guard `51..75`, so at exactly 75 the L
step fails and evaluation falls through to whatever is beneath it.

CLI:
    python emit_tiamat_table.py out/tiamat_rotation.tsv <out.cs>
"""
from __future__ import annotations

import argparse
import collections
import pathlib

HEADER = '''// <auto-generated>
//     Generated by tools/client-extract/emit_tiamat_table.py from the retail AI patterns.
//     Do not edit by hand: re-run the extractor instead. See docs/retail-ai-fidelity.md.
// </auto-generated>

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// Tiamat's dying-phase rotation: every battle-timer step, in the order retail evaluates them.
/// </summary>
/// <remarks>
/// {steps} steps across four health bands plus the unbanded heartbeat, placing {npcs} distinct
/// hazards at {rows} fixed points. Read out of <c>IDTiamat_Tiamat_Dragon_Dying_Named_60_Al</c>.
/// <para>
/// Flat and in document order on purpose. Retail's priorities descend down the file and the first
/// branch whose guards pass wins, and this pattern has a place where the ordering between bands
/// matters: <c>BreathL_75-51</c> guards 51..74 where the M and R steps beside it guard 51..75, so at
/// exactly 75 the L step fails and evaluation falls through. Grouping by band would lose that.
/// </para>
/// </remarks>
internal static class TiamatRotation
{{
    /// <summary>One hazard placed by a step. <paramref name="Degrees"/> is the pattern's own <c>dir</c>.</summary>
    internal readonly record struct Placement(int NpcId, int Count, float X, float Y, float Z, int Degrees, int LiveSeconds);

    /// <summary>One step of the chain.</summary>
    /// <param name="Low">Inclusive band bounds as retail writes them, or 0/100 for the unbanded heartbeat.</param>
    /// <param name="Label">The pattern's own branch comment, kept so the table reads against the digest.</param>
    /// <param name="Banded">False for the heartbeat, which carries no health guard at all.</param>
    internal readonly record struct Step(
        int Timer, int NextTimer, int DelayMillis, int Low, int High, bool Banded,
        string Label, Placement[] Spawns);

    internal static readonly Step[] Steps =
    [
'''

FOOTER = '''    ];
}
'''


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("tsv")
    ap.add_argument("out")
    args = ap.parse_args()

    steps: dict[int, dict] = {}
    order: list[int] = []
    rows = 0
    npcs: set[str] = set()
    for line in pathlib.Path(args.tsv).read_text(encoding="utf-8").splitlines():
        parts = line.split("\t")
        if not parts or parts[0] in ("band", ""):
            continue
        (band, step, timer, nxt, delay, label, _indices,
         npc_id, count, x, y, z, deg, live) = parts
        step = int(step)
        if step not in steps:
            if band == "any":
                low, high, banded = 0, 100, False
            else:
                lo, hi = band.split("-")
                low, high, banded = int(lo), int(hi), True
            steps[step] = {
                "timer": int(timer), "next": int(nxt), "delay": int(delay),
                "low": low, "high": high, "banded": banded,
                "label": label, "spawns": [],
            }
            order.append(step)
        if npc_id:
            npcs.add(npc_id)
            steps[step]["spawns"].append(
                (npc_id, int(count), x, y, z, str(int(float(deg or 0))), int(live)))
        rows += 1

    lines = [HEADER.format(steps=len(steps), npcs=len(npcs), rows=rows)]
    for step in order:
        s = steps[step]
        placements = ", ".join(
            f"new Placement({n}, {c}, {x}f, {y}f, {z}f, {d}, {lv})"
            for n, c, x, y, z, d, lv in s["spawns"])
        lines.append(
            f'        new Step({s["timer"]}, {s["next"]}, {s["delay"]}, {s["low"]}, {s["high"]}, '
            f'{"true" if s["banded"] else "false"}, "{s["label"]}", [{placements}]),\n')
    lines.append(FOOTER)
    pathlib.Path(args.out).write_text("".join(lines), encoding="utf-8")
    print(f"{len(steps)} steps, {rows} rows, {len(npcs)} distinct npcs")


if __name__ == "__main__":
    main()
