"""Transcribe the extracted Vritra-caller options into the C# table the AI reads.

CLI:
    python emit_vritra_table.py out/vritra_callers.tsv <out.cs>
"""
from __future__ import annotations

import argparse
import collections
import pathlib

# Client path name -> the route id it was imported under. Route ids are ours to choose, so this mapping
# is a decision and not a translation, which is why it lives here in the open rather than being derived.
LANES = {
    "NPCPathVriAss_Path01": "3008000001",
    "NPCPathVriAss_Path02": "3008000002",
}

HEADER = '''// <auto-generated>
//     Generated by tools/client-extract/emit_vritra_table.py from the retail AI patterns.
//     Do not edit by hand: re-run the extractor instead. See docs/retail-ai-fidelity.md.
// </auto-generated>
#nullable enable

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// What each Runatorium Vritra caller puts on the floor.
/// </summary>
/// <remarks>
/// Read out of the retail <c>BIDRuneWP_Main_CallVritra*</c> patterns — {rows} spawns across
/// {callers} controllers. The options are in retail's evaluation order: highest priority first and,
/// within a priority, document order. Evaluation stops at the first option whose roll passes, so a
/// cascade of ten twenty-percent branches is a weighted pick, not ten independent rolls, and the
/// unguarded branch beneath them is the fallback that makes exactly one trooper appear every time.
/// </remarks>
internal static class VritraCallers
{{
    /// <summary>One spawn: who, how many, and where.</summary>
    /// <param name="Lane">
    /// Our route id for the client <c>pathname</c> on this spawn action, or null if it carried none.
    /// The trooper walks it after appearing at the coordinates.
    /// </param>
    internal readonly record struct Placement(int NpcId, int Count, float X, float Y, float Z, string? Lane);

    /// <summary>One branch of the cascade.</summary>
    /// <param name="Chance">Percent, or 100 for the unguarded fallback.</param>
    internal readonly record struct Option(int Chance, Placement[] Spawns);

    internal static readonly IReadOnlyDictionary<int, Option[]> ByCaller = new Dictionary<int, Option[]>
    {{
'''

FOOTER = '''    };

'''

LANE_HEADER = '''    /// <summary>Which lane each trooper marches once it is on the floor.</summary>
    /// <remarks>
    /// Derived from the <c>pathname</c> on the spawn actions above. The emitter refuses to write this if
    /// any npc id appears on two different lanes, because the AI looks its own lane up by npc id and that
    /// is only sound while each id has exactly one.
    /// </remarks>
    internal static readonly IReadOnlyDictionary<int, string> LaneOf = new Dictionary<int, string>
    {
'''

LANE_FOOTER = '''    };
}
'''


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("tsv")
    ap.add_argument("out")
    args = ap.parse_args()

    by_caller: dict[int, dict[int, list]] = collections.defaultdict(lambda: collections.defaultdict(list))
    lane_of: dict[int, str] = {}
    chances: dict[tuple[int, int], int] = {}
    pattern_of: dict[int, str] = {}
    rows = 0
    for line in pathlib.Path(args.tsv).read_text(encoding="utf-8").splitlines():
        parts = line.split("\t")
        if not parts or parts[0] in ("caller_npc_id", ""):
            continue
        caller, pattern, option, chance, npc_id, count, x, y, z, pathname = parts
        caller, option = int(caller), int(option)
        by_caller[caller][option].append((int(npc_id), int(count), x, y, z, pathname))
        if pathname:
            lane = LANES.get(pathname)
            if lane is None:
                raise SystemExit(
                    f"no route id known for client path {pathname!r}. Import it into npc_walker and add "
                    f"it to LANES here; leaving it out is how the march went missing the first time.")
            seen = lane_of.setdefault(int(npc_id), lane)
            if seen != lane:
                raise SystemExit(
                    f"npc {npc_id} is spawned onto two different lanes ({seen} and {lane}). The AI finds "
                    f"its own lane from its npc id, and that only works while this holds.")
        chances[(caller, option)] = int(chance)
        pattern_of[caller] = pattern
        rows += 1

    lines = [HEADER.format(rows=rows, callers=len(by_caller))]
    for caller in sorted(by_caller):
        rendered = []
        for option in sorted(by_caller[caller]):
            spawns = ", ".join(
                f"new Placement({npc}, {count}, {x}f, {y}f, {z}f, "
                + (f'"{LANES[path]}"' if path else "null") + ")"
                for npc, count, x, y, z, path in by_caller[caller][option])
            rendered.append(f"new Option({chances[(caller, option)]}, [{spawns}])")
        body = ", ".join(rendered)
        lines.append(f"        // {pattern_of[caller]}\n        [{caller}] = [{body}],\n")
    lines.append(FOOTER)
    lines.append(LANE_HEADER)
    for npc in sorted(lane_of):
        lines.append(f'        [{npc}] = "{lane_of[npc]}",' + chr(10))
    lines.append(LANE_FOOTER)
    pathlib.Path(args.out).write_text("".join(lines), encoding="utf-8")
    print(f"{rows} spawns -> {len(by_caller)} controllers")


if __name__ == "__main__":
    main()
