"""Turn the extracted guard call roster into the C# table the AI reads.

Kept separate from `extract_guard_calls.py` so the TSV stays the thing a human reviews: the extraction
is the claim about what retail does, and this is only a transcription of it.

CLI:
    python emit_guard_calls_table.py out/guard_calls.tsv <out.cs>
"""
from __future__ import annotations

import argparse
import collections
import pathlib

HEADER = '''// <auto-generated>
//     Generated by tools/client-extract/emit_guard_calls_table.py from the retail AI patterns.
//     Do not edit by hand: re-run the extractor instead. See docs/retail-ai-fidelity.md.
// </auto-generated>

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// Which guards call for help when they are pulled, and which answer.
/// </summary>
/// <remarks>
/// Retail's message <c>23000</c>, read straight out of the patterns: {rows} live guards across
/// {patterns} pattern variants, of which {senders} send the call and {listeners} answer it. It is the
/// largest single mechanic in the dump by npc count, and the answer to it is uniform to a degree
/// nothing else in this project has been -- every one of the answering patterns carries the same two
/// branches with the same hate value, and there is no third shape anywhere.
/// <para>
/// The send half is not uniform, which is why the range is a column rather than a constant: {ranges}.
/// Three further broadcasts sit on battle timers inside cast chains we are not porting and are left
/// out, because a send on a timer is a different cadence and would need that timer built.
/// </para>
/// </remarks>
internal static class GuardCalls
{{
    /// <summary>What one guard does with the call.</summary>
    /// <param name="SendRange">
    /// Retail's <c>range_as_meter</c> on the broadcast it makes as it is pulled, or 0 for a guard that
    /// only listens. Most guards only listen: a fortress is a few criers and a great many answerers.
    /// </param>
    /// <param name="Answers">
    /// True when the guard carries retail's <c>on_message 23000</c> pair. Both halves always appear
    /// together, so one flag covers them.
    /// </param>
    internal readonly record struct Call(float SendRange, bool Answers);

    internal static readonly IReadOnlyDictionary<int, Call> ByGuard = new Dictionary<int, Call>
    {{
'''

FOOTER = '''    };
}
'''


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("tsv", type=pathlib.Path)
    ap.add_argument("out", type=pathlib.Path)
    args = ap.parse_args()

    rows: list[tuple[int, int, int, str]] = []
    ranges: collections.Counter[int] = collections.Counter()
    patterns: set[str] = set()
    for line in args.tsv.read_text(encoding="utf-8").splitlines()[1:]:
        npc, pattern, send_range, receives, name = (line.split("\t") + [""])[:5]
        rows.append((int(npc), int(send_range), int(receives), name))
        patterns.add(pattern)
        if int(send_range):
            ranges[int(send_range)] += 1

    spread = ", ".join(f"{n} of them at {m} metres" for m, n in sorted(ranges.items()))
    header = HEADER.format(
        rows=len(rows), patterns=len(patterns),
        senders=sum(1 for r in rows if r[1]), listeners=sum(1 for r in rows if r[2]),
        ranges=spread)

    with args.out.open("w", encoding="utf-8", newline="\n") as out:
        out.write(header)
        for npc, send_range, receives, name in rows:
            answers = "true" if receives else "false"
            comment = f"  // {name}" if name else ""
            out.write(f"        [{npc}] = new Call({send_range}f, {answers}),{comment}\n")
        out.write(FOOTER)

    print(f"{len(rows)} rows -> {args.out}")


if __name__ == "__main__":
    main()
