"""Turn the extracted gate squad chains into the C# table the AI reads.

Sibling to `emit_guard_table.py`, and kept separate from the extraction for the same
reason: the TSV is the reviewable claim about what retail does, this is only a
transcription of it.

CLI:
    python emit_gate_table.py out/gate_squads.tsv <out.cs>
"""
from __future__ import annotations

import argparse
import collections
import pathlib

HEADER = '''// <auto-generated>
//     Generated by tools/client-extract/emit_gate_table.py from the retail AI patterns.
//     Do not edit by hand: re-run the extractor instead. See docs/retail-ai-fidelity.md.
// </auto-generated>

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// The squad each fortress gate puts out, wave by wave.
/// </summary>
/// <remarks>
/// Read out of the retail <c>BGuard_*Gate*</c> patterns — {rows} steps for {gates} gates across
/// {patterns} pattern variants. A gate is attacked, waits, and puts out waves on a fixed chain; most
/// then remove themselves, and some cycle back to the first wave instead and keep going for as long
/// as the fight lasts.
/// </remarks>
internal static class GateSquads
{{
    /// <summary>One wave.</summary>
    /// <param name="DelayMillis">How long after the previous wave — or after being attacked, for the first.</param>
    /// <param name="OnTarget">True when retail places the wave on whoever the gate is fighting.</param>
    /// <param name="Summons">npc id and count, in the order the pattern lists them.</param>
    internal readonly record struct Wave(int DelayMillis, bool OnTarget, (int NpcId, int Count)[] Summons);

    /// <summary>One gate's chain.</summary>
    /// <param name="Waves">In order.</param>
    /// <param name="DespawnAfterMillis">How long the gate stands after its last wave, or 0 if it loops.</param>
    /// <param name="LoopsTo">The wave the chain returns to, or -1 when the gate removes itself instead.</param>
    internal readonly record struct Squad(Wave[] Waves, int DespawnAfterMillis, int LoopsTo);

    internal static readonly IReadOnlyDictionary<int, Squad> ByGate = new Dictionary<int, Squad>
    {{
'''

FOOTER = '''    };
}
'''


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("tsv")
    ap.add_argument("out")
    args = ap.parse_args()

    by_gate: dict[int, list[tuple]] = collections.defaultdict(list)
    meta: dict[int, tuple] = {}
    patterns: set[str] = set()
    rows = 0
    for line in pathlib.Path(args.tsv).read_text(encoding="utf-8").splitlines():
        parts = line.split("\t")
        if not parts or parts[0] in ("gate_npc_id", ""):
            continue
        gate, pattern, step, delay, placement, summons, despawn, loops = parts
        patterns.add(pattern)
        pairs = []
        for chunk in summons.split(","):
            npc_id, count = chunk.split("*")
            pairs.append((int(npc_id), int(count)))
        by_gate[int(gate)].append((int(step), int(delay), placement, pairs))
        meta[int(gate)] = (pattern, int(despawn), int(loops))
        rows += 1

    lines = [HEADER.format(rows=rows, gates=len(by_gate), patterns=len(patterns))]
    for gate in sorted(by_gate):
        waves = sorted(by_gate[gate])
        pattern, despawn, loops = meta[gate]
        rendered = []
        for _step, delay, placement, pairs in waves:
            summons = ", ".join(f"({npc}, {count})" for npc, count in pairs)
            on_target = "true" if placement == "TARGET" else "false"
            rendered.append(f"new Wave({delay}, {on_target}, [{summons}])")
        body = ", ".join(rendered)
        lines.append(f"        // {pattern}\n        [{gate}] = new Squad([{body}], {despawn}, {loops}),\n")
    lines.append(FOOTER)
    pathlib.Path(args.out).write_text("".join(lines), encoding="utf-8")
    print(f"{rows} steps -> {len(by_gate)} gates, {len(patterns)} patterns")


if __name__ == "__main__":
    main()
