"""Transcribe passive_patterns.tsv into PassivePatterns.cs. See extract_passive_patterns.py."""
from __future__ import annotations

import argparse
import collections
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from emit_battle_cycles_table import CHUNK
from emit_idle_cycles_table import action_code, guard_code

HANDLERS = [("on_wake_up", "OnWakeUp", "What it does the moment it appears."),
            ("on_idle_timer", "OnIdleTimer", "What it does each time its own timer fires.")]

HEADER = '''// <auto-generated>
//     Generated by tools/client-extract/emit_passive_patterns_table.py from out/passive_patterns.tsv.
//     Do not edit by hand; edit the extractor and re-run.
// </auto-generated>
using Aion.GameServer.Ai.Pattern;

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// Full patterns for npcs that do not fight: {patterns} patterns across {npcs} npcs, {actions} actions.
/// </summary>
/// <remarks>
/// Flags, wave controllers and scenery. <see cref="WakeVariables"/> took the ones whose whole behaviour
/// was an unguarded list of variable writes; everything with a guard, a timer, a message or a spawn
/// beside it was counted and left, and this is that remainder.
/// <para>
/// <b>The vocabulary was never the obstacle -- the base class was.</b> <c>PatternAi</c> extends
/// <c>AggressiveNpcAI</c>, and this project once bound 67 wave controllers to a class that descends
/// from it and made them attack on sight for a dozen entries without a single pin noticing.
/// <see cref="Aion.GameServer.Ai.Pattern.PassivePatternAi"/> is what makes this table safe.
/// </para>
/// </remarks>
internal static class PassivePatterns
{{
    /// <summary>Retail's <c>SPAWN_ID_NONE</c>: these rungs do not track what they placed.</summary>
    internal const int Untracked = 0;

'''


def write_table(out, field, summary, branches, meta, names):
    npcs = sorted(branches)
    chunks = [npcs[i:i + CHUNK] for i in range(0, len(npcs), CHUNK)] or [[]]
    out.write("    /// <summary>" + summary + "</summary>\n")
    out.write("    internal static PatternBranch[] " + field + "For(int npcId)\n")
    out.write("        => " + field + ".TryGetValue(npcId, out PatternBranch[]? rungs) ? rungs : [];\n\n")
    out.write("    private static readonly IReadOnlyDictionary<int, PatternBranch[]> " + field
              + " =\n        Build" + field + "();\n\n")
    out.write("    private static Dictionary<int, PatternBranch[]> Build" + field + "()\n    {\n")
    out.write("        Dictionary<int, PatternBranch[]> rungs = "
              "new Dictionary<int, PatternBranch[]>();\n")
    for index in range(len(chunks)):
        out.write("        " + field + str(index) + "(rungs);\n")
    out.write("        return rungs;\n    }\n\n")
    for index, chunk in enumerate(chunks):
        out.write("    private static void " + field + str(index)
                  + "(Dictionary<int, PatternBranch[]> rungs)\n    {\n")
        for npc in chunk:
            out.write(f"        rungs[{npc}] = [  // {names[npc]}\n")
            for branch in sorted(branches[npc]):
                priority, guards = meta[(npc, branch)]
                tokens = [guard_code(t) for t in guards.split("|") if t]
                condition = "When.Always" if not tokens else "[" + ", ".join(tokens) + "]"
                body = ",\n".join("                " + action_code(r) for r in branches[npc][branch])
                out.write(f'            AiPattern.Branch({priority}, "rung {branch}", {condition},\n')
                out.write(body + "),\n")
            out.write("        ];\n")
        out.write("    }\n\n")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("tsv", type=pathlib.Path)
    ap.add_argument("out", type=pathlib.Path)
    args = ap.parse_args()

    lines = args.tsv.read_text(encoding="utf-8").splitlines()
    header = lines[0].split("\t")
    tables = collections.defaultdict(lambda: collections.defaultdict(lambda: collections.defaultdict(list)))
    meta = {}
    names = {}
    actions = 0
    for line in lines[1:]:
        row = dict(zip(header, line.split("\t")))
        npc, branch = int(row["npc"]), int(row["branch"])
        names[npc] = row["pattern"]
        meta[(row["handler"], npc, branch)] = (int(row["priority"]), row["guards"])
        tables[row["handler"]][npc][branch].append(row)
        actions += 1

    with args.out.open("w", encoding="utf-8", newline="\n") as out:
        out.write(HEADER.format(patterns=len(set(names.values())), npcs=len(names), actions=actions))
        for handler, field, summary in HANDLERS:
            write_table(out, field, summary, tables[handler],
                        {(n, b): v for (h, n, b), v in meta.items() if h == handler}, names)
        out.write("    /// <summary>Every npc this table drives.</summary>\n")
        out.write("    internal static IEnumerable<int> Npcs => OnWakeUp.Keys.Union(OnIdleTimer.Keys);\n")
        out.write("}\n")

    print(f"{len(set(names.values()))} patterns, {len(names)} npcs, {actions} actions -> {args.out}")


if __name__ == "__main__":
    main()
