"""Transcribe battle_cycles.tsv into pattern_tables/battle_cycles.xml.

See extract_battle_cycles.py for the claim, and PatternTableLoader for how a stored token becomes
the guard or action a PatternAi runs.
"""
from __future__ import annotations

import argparse
import collections
import pathlib
import xml.dom.minidom

#: Each retail handler this table drives, and the field it becomes. `cycle` is `on_battle_timer`; the
#: rest are places retail arms a timer from, and a rotation with no arming rung never runs at all.
HANDLERS = [
    ("cycle", "Cycle", "The rotation itself, chosen by which timer fired."),
    ("on_enter_attack_state", "OnEnterAttackState", "Arms the chain when the fight starts."),
    ("on_message", "OnMessage", "Arms the chain when another npc calls."),
    ("on_attacked", "OnAttacked", "Arms the chain on being hit."),
    ("on_spelled", "OnSpelled", "Arms the chain on being spelled."),
    ("on_wake_up", "OnWakeUp", "Arms the chain on waking."),
    ("on_see_npc", "OnSeeNpc", "Arms the chain on seeing an npc."),
    ("on_see_user", "OnSeeUser", "Arms the chain on seeing a player."),
    ("on_see_user_move", "OnSeeUserMove", "Arms the chain when a player moves in sight."),
    ("on_die", "OnDie", "What the encounter leaves behind when it dies."),
    ("on_leave_attack_state", "OnLeaveAttack", "What it does when the fight ends without dying."),
    ("on_enter_idle_state", "OnEnterIdleState", "What the npc does the moment it goes back to idle."),
    ("on_talked_by_user", "OnTalkedByUser", "What it does when a player talks to it."),
    ("on_see_friend_attacked", "OnSeeFriendAttacked", "What it does when something it counts as a friend is attacked."),
    ("on_arrived_at_waypoint", "OnArrivedAtWaypoint", "What it does on reaching a point on its route."),
    ("on_despawn", "OnDespawn", "What it leaves behind when it is removed without dying."),
    ("on_friend_spelled", "OnFriendSpelled", "What it does when a friend is spelled."),
    ("on_stop_to_flee", "OnStopToFlee", "What it does when it stops running away."),
    ("on_see_friend_killed_by_user", "OnFriendKilled", "What it does when a player kills a friend."),
    ("on_enter_return_sp", "OnEnterReturnSp", "What it does on giving up and heading home."),
    ("on_leave_return_sp", "OnLeaveReturnSp", "What it does on getting home again."),
]

XML_HEADER = '''<?xml version="1.0" encoding="UTF-8"?>
<!--
    Generated by tools/client-extract/emit_battle_cycles_table.py from out/battle_cycles.tsv.
    Do not edit by hand; edit the extractor and re-run.

    Retail's battle rotations and the handlers that arm them: {patterns} patterns across {npcs} npcs,
    {actions} actions.

    Branch lists are shared. Many npcs run the same retail pattern, so each distinct list is written
    once as a <variant> and each npc points at one. Two npcs share a variant only when the text
    written for them is identical, so this cannot merge npcs that differ in some way nobody thought
    to check.

    Branch order is the order written here; retail's lists are first-match-wins.

    This was 133,959 lines of generated C#, the largest file in the port. See PatternTableLoader for
    how a guard token and an action row become the guards and actions a PatternAi runs.
-->
<pattern_table>
'''


def escape(value: str) -> str:
    """XML attribute escaping."""
    return (value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;"))

def guard_code(token: str) -> str:
    kind, _, argument = token.partition(":")
    if kind == "timer":
        return f"When.Timer({argument})"
    if kind == "class":
        name, classes = argument.split(":")
        listed = ", ".join(f"PlayerClass.{c}" for c in classes.split("+"))
        return f"When.{name}({listed})"
    if kind == "eventskill":
        return f"When.EventSkill({argument})"
    if kind == "abnormal":
        name, state = argument.split(":")
        return f"When.{name}(AbnormalState.{state})"
    if kind == "race":
        name, race = argument.split(":")
        return f"When.{name}(Race.{race})"
    if kind == "within":
        name, metres = argument.split(":")
        return f"When.{name}({metres})"
    if kind == "beyond":
        name, metres = argument.split(":")
        return f"When.{name}({metres})"
    if kind == "hp_of":
        name, percent = argument.split(":")
        return f"When.{name}({percent})"
    if kind == "hp_below":
        return f"When.HpBelow({argument})"
    if kind == "hp_between":
        low, high = argument.split(":")
        return f"When.HpBetween({low}, {high})"
    if kind == "set_flag_var":
        return f"When.FirstTime({argument})"
    if kind == "unset_flag_var":
        return f"When.Consuming({argument})"
    if kind == "set_world_flag_var":
        return f"When.FirstTimeInWorld({argument})"
    if kind == "unset_world_flag_var":
        return f"When.ConsumingWorld({argument})"
    if kind == "is_world_flag_var":
        return f"When.WorldFlagSet({argument})"
    if kind == "message":
        return f"When.Message({argument})"
    if kind == "flying":
        return f"When.{argument}Flying"
    if kind == "chance":
        return f"When.Chance({argument})"
    if kind == "waypoint":
        # Retail's one-based index, carried verbatim; `When.AtWaypoint` does the conversion.
        return f"When.AtWaypoint({argument})"
    if kind == "last_waypoint":
        return "When.AtLastWaypoint"
    if kind == "skillready":
        return f"When.SkillReady({argument})"
    if kind == "who":
        # The parser already resolved the role to its condition name.
        return "When." + argument
    if kind == "enemy":
        # The parser already resolved the role to its condition name.
        return "When." + argument
    if kind == "state":
        return "When." + {"fight": "Fighting", "idle": "Idling", "route": "WalkingItsRoute",
                          "wander": "WanderingAtRandom", "point": "MovingToAPoint",
                          "casting": "Casting"}[argument]
    if kind == "countby":
        slot, step, low, high, at_bound = argument.split(":")
        return (f"When.CountingBy({slot}, {step}, {low}, {high}, "
                f"{'true' if at_bound == '1' else 'false'})")
    if kind == "count":
        # `increase_intvar`, which the idle parser brought when the two merged: a condition that
        # increments as it tests.
        slot, low, high, at_bound = argument.split(":")
        return f"When.Counting({slot}, {low}, {high}, {'true' if at_bound == '1' else 'false'})"
    raise ValueError(f"unknown guard {token}")


def action_code(row: dict) -> str:
    kind = row["kind"]
    if kind == "spawn":
        npc, count, live, group = row["a1"], row["a2"], row["a3"], row["group"]
        place, x, y, z = row["place"], row["x"], row["y"], row["z"]
        # Retail's despawn_at_attack_state: the add goes when the fight does.
        suffix = ""
        if place.startswith("for_the_fight_"):
            place, suffix = place[len("for_the_fight_"):], "ForTheFight"
        if place == "self":
            return f"Do.SpawnNear{suffix}({npc}, {group}, {count}, 0f, {live})"
        if place == "offset":
            return f"Do.SpawnOffset{suffix}({npc}, {group}, {x}f, {y}f, {live}, {z}f)"
        spots = ", ".join(f"new SpawnSpot({x}f, {y}f, {z}f)" for _ in range(max(1, int(count))))
        return f"Do.SpawnAt{suffix}({npc}, {group}, {live}, {spots})"
    if kind == "skill":
        return f"Do.SkillOn(NpcSkillTargetAttribute.{row['place']}, {row['a1']})"
    if kind == "skill_now":
        # The hazard's immediate path; see the extractor. `Do.SkillOn` would queue it and the npc is
        # gone before the queue drains.
        return f"Do.SkillOnSelfNow({row['a1']})"
    if kind == "skill_in_reach":
        return f"Do.SkillOnRankedInReach(AggroTarget.{row['place']}, {row['a1']})"
    if kind == "skill_at":
        return f"Do.SkillOn{row['place']}({row['a1']})"
    if kind == "arm":
        return f"Do.ArmTimer({row['a1']}, {row['a2']})"
    if kind == "despawn":
        return f"Do.Despawn({row['a1']})"
    if kind == "spawn_on_ranked":
        return (f"Do.SpawnOnAttacker(AggroTarget.{row['place']}, {row['a1']}, {row['group']}, "
                f"{row['x']}f, {int(float(row['z']))}, {row['a2']}, {row['y']}f)")
    if kind == "spawn_each":
        return (f"Do.SpawnOnEachTarget({row['a1']}, {row['group']}, {row['x']}f, {row['a2']}, "
                f"MultiTargetOrder.{row['place']}, {row['y']}f, {int(float(row['z']))}, {row['a3']})")
    if kind == "spawn_on_target":
        return (f"Do.SpawnOnTarget({row['a1']}, {row['group']}, {row['a2']}, {row['x']}f, "
                f"{row['a3']}, {int(float(row['z']))}, {row['y']}f)")
    if kind == "spawn_near":
        return f"Do.SpawnNear({row['a1']}, {row['group']}, {row['a2']}, {row['x']}f, {row['a3']})"
    if kind == "switch_to":
        return f"Do.SwitchTarget(AggroTarget.{row['place']})"
    if kind.startswith("hate_at:"):
        return f"Do.{kind[len('hate_at:'):]}({row['a1']})"
    if kind == "hate":
        return f"Do.HateMessageParam({row['a1']})"
    if kind.startswith("switch_to:"):
        return f"Do.{kind[len('switch_to:'):]}()"
    if kind == "switch":
        return "Do.TargetMessageParam()"
    if kind == "attack":
        return "Do.AttackMostHating()"
    if kind == "despawn_self":
        return "Do.DespawnSelf()"
    # The three the idle vocabulary brought when the parsers merged.
    if kind == "timer":
        return f"Do.SetIdleTimer({row['a1']})"
    if kind == "waypoint":
        return f"Do.GotoWaypoint({row['a1']})"
    if kind.startswith("flee_"):
        # The parser resolved the role to its action name.
        return f"Do.{kind[len('flee_'):]}({row['a1']})"
    if kind == "reset_hate":
        return "Do.ResetHate()"
    if kind == "reset_hate_top":
        return "Do.ResetHateExceptTop()"
    if kind == "nothing":
        return "Do.Nothing()"
    if kind == "next_waypoint":
        return "Do.ContinueRoute()"
    if kind == "next_waypoint_run":
        return "Do.ContinueRouteRunning()"
    if kind == "waypoint_run":
        return f"Do.GotoWaypointRunning({row['a1']})"
    if kind == "say":
        return f"Do.Say({row['a1']}, {row['a2']})"
    if kind == "sysmsg":
        return f"Do.SystemMessage({row['a1']}, {row['a2']})"
    if kind == "var":
        return f'Do.SetSpawnVariable("{row["place"]}", {row["a1"]}, {row["a2"]})'
    if kind == "broadcast":
        return f"Do.Broadcast({row['a1']}, {row['a2']}f)"
    raise ValueError(f"unknown action {kind}")


#: How many npcs go into one generated method.
#:
#: A single initializer holding every npc **overflowed the stack the first time the class was touched**
#: -- in the type initializer itself, not in any test harness quirk, so it would have taken the live
#: server down the same way the moment a bound npc entered combat. The table is built by a chain of
#: small methods instead. 100 npcs per method keeps each one well inside what the runtime will start.
CHUNK = 100


def write_table(out, handler: str, branches, meta, names) -> None:
    """Emit one handler as deduplicated variants plus an npc -> variant map.

    **The rows are 6.7x redundant.** Retail keys a pattern by name and many npcs run the same one, so
    writing per npc would repeat the same branch list once per owner: 166,639 rows for 24,923 distinct
    ones.

    Deduplication is on **the written text of the branch list**, not on the fields we believe vary.
    That distinction is the safety argument. A rule like "casts vary by npc, everything else is
    pattern-level" happens to be true today -- measured: 0 of 14,921 non-cast sites differ between npcs
    of one pattern -- but it is a claim about the data that a later extractor change could quietly
    falsify. Two npcs share a variant only when the text written for them is identical, so this cannot
    lose a difference it failed to anticipate.
    """
    variants: dict[str, int] = {}
    of: dict[int, int] = {}
    for npc in sorted(branches):
        body = []
        for branch in sorted(branches[npc]):
            priority, guards = meta[(npc, branch)]
            body.append(f'\t\t<branch priority="{priority}" comment="rung {branch}">\n')
            for token in [t for t in guards.split("|") if t]:
                body.append(f'\t\t\t<guard token="{escape(token)}" />\n')
            for row in branches[npc][branch]:
                body.append(
                    f'\t\t\t<action kind="{escape(row["kind"])}"'
                    f' a1="{row["a1"]}" a2="{row["a2"]}" a3="{row["a3"]}"'
                    f' place="{escape(row["place"])}"'
                    f' x="{row["x"]}" y="{row["y"]}" z="{row["z"]}"'
                    f' group="{row["group"]}" />\n')
            body.append(f'\t\t</branch>\n')
        of[npc] = variants.setdefault("".join(body), len(variants))

    for body, slot in sorted(variants.items(), key=lambda kv: kv[1]):
        out.write(f'\t<variant id="{slot}" handler="{handler}">\n')
        out.write(body)
        out.write(f'\t</variant>\n')
    for npc in sorted(of):
        label = names[npc].replace("--", "-")
        out.write(f'\t<owner npc="{npc}" handler="{handler}" variant="{of[npc]}" />'
                  f'  <!-- {label} -->\n')


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("tsv", type=pathlib.Path)
    ap.add_argument("out", type=pathlib.Path)
    args = ap.parse_args()

    lines = args.tsv.read_text(encoding="utf-8").splitlines()
    header = lines[0].split("\t")
    tables: dict[str, dict] = collections.defaultdict(
        lambda: collections.defaultdict(lambda: collections.defaultdict(list)))
    meta: dict[tuple[str, int, int], tuple[int, str]] = {}
    names: dict[int, str] = {}
    actions = 0
    for line in lines[1:]:
        row = dict(zip(header, line.split("\t")))
        npc, branch = int(row["npc"]), int(row["branch"])
        names[npc] = row["pattern"]
        meta[(row["handler"], npc, branch)] = (int(row["priority"]), row["guards"])
        tables[row["handler"]][npc][branch].append(row)
        actions += 1

    with args.out.open("w", encoding="utf-8", newline="\n") as out:
        out.write(XML_HEADER.format(patterns=len(set(names.values())), npcs=len(names), actions=actions))
        for handler, _field, _summary in HANDLERS:
            # Written even when empty: a handler with no rows today is the normal state for the rarer
            # ones. `on_leave_attack_state` is exactly that -- every branch retail puts there is
            # currently unsayable, and it simply contributes nothing.
            write_table(out, handler, tables[handler],
                        {(n, b): v for (h, n, b), v in meta.items() if h == handler}, names)
        out.write("</pattern_table>" + "\n")

    # A double dash in a comment is an XML error, and this file's comments carry retail pattern names.
    xml.dom.minidom.parse(str(args.out))

    print(f"{len(set(names.values()))} patterns, {len(names)} npcs, {actions} actions -> {args.out}")


if __name__ == "__main__":
    main()
