"""Transcribe idle_spawns.tsv into IdleSpawns.cs. See extract_idle_spawns.py for the claim."""
from __future__ import annotations

import argparse
import collections
import pathlib

HEADER = '''// <auto-generated>
//     Generated by tools/client-extract/emit_idle_spawns_table.py from out/idle_spawns.tsv.
//     Do not edit by hand; edit the extractor and re-run.
// </auto-generated>
#nullable enable
using Aion.GameServer.Ai.Pattern;

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// NPCs that wake, wait, and place something: {rows} placements across {npcs} npcs.
/// </summary>
/// <remarks>
/// The portable subset of a shape this port was missing wholesale. 132 retail patterns spawn from
/// <c>on_idle_timer</c> and their npcs ran a generic class here, which does nothing with a timer; these
/// are the ones whose rung is a single unguarded branch carrying nothing but spawns and the timer.
/// <para>
/// Everything is per npc because nothing is constant: the wait runs 2 to 600 seconds, the placements 1
/// to 11, and the re-arm is absent, zero — which <b>stops</b> the timer — or a real period.
/// </para>
/// </remarks>
internal static class IdleSpawns
{{
    /// <summary>Where a placement goes. Retail has three and they are not interchangeable.</summary>
    internal enum Where
    {{
        /// <summary><c>SPAWN_LOCATION_ABSOLUTE</c> — world coordinates.</summary>
        Absolute,

        /// <summary><c>SPAWN_LOCATION_MY_POINT</c> — on the npc; the block carries no coordinates.</summary>
        AtTheNpc,

        /// <summary><c>SPAWN_LOCATION_RELATIVE</c> — an offset from the npc, not a world position.</summary>
        Offset,
    }}

    /// <summary>One thing an npc places. <c>Scoped</c> is retail's <c>despawn_at_attack_state</c>.</summary>
    internal readonly record struct Placement(int Npc, int Count, int LiveSeconds, Where Place,
        float X, float Y, float Z, bool Scoped);

    /// <summary>One npc's whole behaviour. <c>ReArmMillis</c> is -1 when the rung does not re-arm.</summary>
    internal readonly record struct Cycle(int WakeMillis, int ReArmMillis, Placement[] Places);

    /// <summary>Every spawner, by npc id.</summary>
    internal static readonly IReadOnlyDictionary<int, Cycle> ByNpc = new Dictionary<int, Cycle>
    {{
'''

FOOTER = '''    };

    /// <summary>Retail's <c>SPAWN_ID_NONE</c> on these rungs: the spawner does not track what it placed.</summary>
    internal const int Untracked = 0;

    /// <summary>The rung that starts the wait, or empty for an npc that is not a spawner.</summary>
    internal static PatternBranch[] WakeRungFor(int npcId)
        => ByNpc.TryGetValue(npcId, out Cycle cycle)
            ? [AiPattern.Branch(7, "start the wait", When.Always, Do.SetIdleTimer(cycle.WakeMillis))]
            : [];

    /// <summary>The rung that places everything, or empty for an npc that is not a spawner.</summary>
    /// <remarks>
    /// The re-arm is emitted only when retail carries one. A rung that re-arms with zero is emitting a
    /// deliberate stop, and passing zero through is the same thing — but a rung with no re-arm at all
    /// must not gain one.
    /// </remarks>
    internal static PatternBranch[] PlaceRungFor(int npcId)
    {
        if (!ByNpc.TryGetValue(npcId, out Cycle cycle))
            return [];

        List<PatternAction> actions = new List<PatternAction>(cycle.Places.Length + 1);
        foreach (Placement place in cycle.Places)
        {
            // Scoped placements belong to the npc that made it: killing the spawner takes them away.
            // All 36 of retail's here are scoped and three are permanent, which is the leak this
            // closes -- but the flag is read per placement rather than assumed for the table.
            actions.Add((place.Place, place.Scoped) switch
            {
                (Where.AtTheNpc, true) => Do.SpawnNearForTheFight(place.Npc, Untracked, place.Count,
                    0f, place.LiveSeconds),
                (Where.AtTheNpc, false) => Do.SpawnNear(place.Npc, Untracked, place.Count, 0f,
                    place.LiveSeconds),
                (Where.Offset, true) => Do.SpawnOffsetForTheFight(place.Npc, Untracked, place.X,
                    place.Y, place.LiveSeconds, place.Z),
                (Where.Offset, false) => Do.SpawnOffset(place.Npc, Untracked, place.X, place.Y,
                    place.LiveSeconds, place.Z),
                (_, true) => Do.SpawnAtForTheFight(place.Npc, Untracked, place.LiveSeconds,
                    new SpawnSpot(place.X, place.Y, place.Z)),
                _ => Do.SpawnAt(place.Npc, Untracked, place.LiveSeconds,
                    new SpawnSpot(place.X, place.Y, place.Z)),
            });
        }

        if (cycle.ReArmMillis >= 0)
            actions.Add(Do.SetIdleTimer(cycle.ReArmMillis));

        return [AiPattern.Branch(7, "place it", When.Always, actions.ToArray())];
    }
}
'''


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("tsv", type=pathlib.Path)
    ap.add_argument("out", type=pathlib.Path)
    args = ap.parse_args()

    places: dict[int, list] = collections.defaultdict(list)
    meta: dict[int, tuple] = {}
    names: dict[int, str] = {}
    for line in args.tsv.read_text(encoding="utf-8").splitlines()[1:]:
        npc, wake, rearm, placed, count, live, place, x, y, z, scoped, pattern = (
            line.split("\t") + [""] * 12)[:12]
        places[int(npc)].append((int(placed), int(count), int(live), place,
                                 float(x), float(y), float(z), scoped == "TRUE"))
        meta[int(npc)] = (int(wake), int(rearm))
        names[int(npc)] = pattern

    rows = sum(len(v) for v in places.values())
    with args.out.open("w", encoding="utf-8", newline="\n") as out:
        out.write(HEADER.format(rows=rows, npcs=len(places)))
        for npc in sorted(places):
            wake, rearm = meta[npc]
            spots = ", ".join(
                f"new Placement({p}, {c}, {l}, Where.{ {'self': 'AtTheNpc', 'offset': 'Offset'}.get(s, 'Absolute') }, "
                f"{x}f, {y}f, {z}f, {'true' if scoped else 'false'})"
                for p, c, l, s, x, y, z, scoped in places[npc])
            out.write(f"        [{npc}] = new Cycle({wake}, {rearm}, [{spots}]),  // {names[npc]}\n")
        out.write(FOOTER)

    print(f"{rows} placements across {len(places)} npcs -> {args.out}")


if __name__ == "__main__":
    main()
