"""Transcribe battle_cycles.tsv into BattleCycles.g.cs. See extract_battle_cycles.py for the claim."""
from __future__ import annotations

import argparse
import collections
import pathlib

#: Each retail handler this table drives, and the field it becomes. `cycle` is `on_battle_timer`; the
#: rest are places retail arms a timer from, and a rotation with no arming rung never runs at all.
HANDLERS = [
    ("cycle", "Cycle", "The rotation itself, chosen by which timer fired."),
    ("on_enter_attack_state", "OnEnterAttackState", "Arms the chain when the fight starts."),
    ("on_message", "OnMessage", "Arms the chain when another npc calls."),
    ("on_attacked", "OnAttacked", "Arms the chain on being hit."),
    ("on_spelled", "OnSpelled", "Arms the chain on being spelled."),
    ("on_wake_up", "OnWakeUp", "Arms the chain on waking."),
    ("on_see_npc", "OnSeeNpc", "Arms the chain on seeing an npc."),
    ("on_see_user", "OnSeeUser", "Arms the chain on seeing a player."),
    ("on_see_user_move", "OnSeeUserMove", "Arms the chain when a player moves in sight."),
    ("on_die", "OnDie", "What the encounter leaves behind when it dies."),
    ("on_leave_attack_state", "OnLeaveAttack", "What it does when the fight ends without dying."),
    ("on_enter_idle_state", "OnEnterIdleState", "What the npc does the moment it goes back to idle."),
    ("on_talked_by_user", "OnTalkedByUser", "What it does when a player talks to it."),
    ("on_see_friend_attacked", "OnSeeFriendAttacked", "What it does when something it counts as a friend is attacked."),
    ("on_arrived_at_waypoint", "OnArrivedAtWaypoint", "What it does on reaching a point on its route."),
    ("on_despawn", "OnDespawn", "What it leaves behind when it is removed without dying."),
    ("on_friend_spelled", "OnFriendSpelled", "What it does when a friend is spelled."),
    ("on_stop_to_flee", "OnStopToFlee", "What it does when it stops running away."),
    ("on_see_friend_killed_by_user", "OnFriendKilled", "What it does when a player kills a friend."),
    ("on_enter_return_sp", "OnEnterReturnSp", "What it does on giving up and heading home."),
    ("on_leave_return_sp", "OnLeaveReturnSp", "What it does on getting home again."),
]

HEADER = '''// <auto-generated>
//     Generated by tools/client-extract/emit_battle_cycles_table.py from out/battle_cycles.tsv.
//     Do not edit by hand; edit the extractor and re-run.
// </auto-generated>
#nullable enable
using Aion.GameServer.Ai.Pattern;
using Aion.GameServer.Controllers.Attack;
using Aion.GameServer.Model;
using Aion.GameServer.SkillEngine.Effects;
using Aion.GameServer.Model.Templates.Npcskill;

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// Combat rotations: {patterns} retail patterns across {npcs} npcs, {actions} actions.
/// </summary>
/// <remarks>
/// What a boss does <b>during</b> the fight, as opposed to <see cref="IdleCycles"/>, which is what an
/// npc does while nothing is happening. Retail arms a battle timer on entering combat and every timer
/// branch arms the next link itself, so a fight is a chain of timers rather than an HP ladder.
/// <para>
/// The arming rung runs on <c>on_enter_attack_state</c>; the cycle rungs run when the timer fires and
/// are guarded by its indicator, so two rotations on different indicators do not disturb each other.
/// <see cref="PatternAi"/> cancels every timer when the fight ends, which is why nothing here needs to
/// clean up after itself.
/// </para>
/// <para>
/// <b>The skills are real too.</b> Retail names them by index into the npc's own ordered list, which
/// this port could not resolve until that list was found in the 5.8 server dump; see
/// <c>extract_npc_skill_lists.py</c>. A rotation is only taken if the owning npc's list answers every
/// index it uses, so a boss here never casts a skill picked by position out of the wrong list.
/// </para>
/// <para>
/// <b>Spawn groups are real here.</b> The idle table spawns into <c>Untracked</c> because nothing there
/// refers back to what it placed; a rotation that despawns its adds needs the group it spawned into.
/// </para>
/// </remarks>
internal static class BattleCycles
{{
    /// <summary>What the npc does on entering combat -- normally arming the first timer.</summary>
    internal static PatternBranch[] ArmingRungsFor(int npcId)
        => OnEnterAttackStateOf.TryGetValue(npcId, out int variant) ? OnEnterAttackStateVariants[variant] : [];

    /// <summary>Rungs that arm a timer when another npc sends a message.</summary>
    internal static PatternBranch[] MessageRungsFor(int npcId)
        => OnMessageOf.TryGetValue(npcId, out int variant) ? OnMessageVariants[variant] : [];

    /// <summary>Rungs that arm a timer on being hit.</summary>
    internal static PatternBranch[] AttackedRungsFor(int npcId)
        => OnAttackedOf.TryGetValue(npcId, out int variant) ? OnAttackedVariants[variant] : [];

    /// <summary>Rungs that arm a timer on being spelled.</summary>
    internal static PatternBranch[] SpelledRungsFor(int npcId)
        => OnSpelledOf.TryGetValue(npcId, out int variant) ? OnSpelledVariants[variant] : [];

    /// <summary>Rungs that arm a timer on waking.</summary>
    internal static PatternBranch[] WakeRungsFor(int npcId)
        => OnWakeUpOf.TryGetValue(npcId, out int variant) ? OnWakeUpVariants[variant] : [];

    /// <summary>Rungs that arm a timer on seeing another npc.</summary>
    internal static PatternBranch[] SeeNpcRungsFor(int npcId)
        => OnSeeNpcOf.TryGetValue(npcId, out int variant) ? OnSeeNpcVariants[variant] : [];

    /// <summary>Rungs that arm a timer on seeing a player.</summary>
    internal static PatternBranch[] SeeUserRungsFor(int npcId)
        => OnSeeUserOf.TryGetValue(npcId, out int variant) ? OnSeeUserVariants[variant] : [];

    /// <summary>Rungs for a player moving inside the npc's sight, which repeats as they move.</summary>
    internal static PatternBranch[] SeeUserMoveRungsFor(int npcId)
        => OnSeeUserMoveOf.TryGetValue(npcId, out int variant) ? OnSeeUserMoveVariants[variant] : [];

    /// <summary>What the npc leaves behind when it dies.</summary>
    internal static PatternBranch[] DeathRungsFor(int npcId)
        => OnDieOf.TryGetValue(npcId, out int variant) ? OnDieVariants[variant] : [];

    /// <summary>What it does when the fight ends without it dying.</summary>
    internal static PatternBranch[] LeaveFightRungsFor(int npcId)
        => OnLeaveAttackOf.TryGetValue(npcId, out int variant) ? OnLeaveAttackVariants[variant] : [];

    /// <summary>What each timer does when it fires, in retail's order.</summary>
    internal static PatternBranch[] CycleRungsFor(int npcId)
        => CycleOf.TryGetValue(npcId, out int variant) ? CycleVariants[variant] : [];

    /// <summary>What the npc does the moment it goes back to idle.</summary>
    internal static PatternBranch[] EnterIdleRungsFor(int npcId)
        => OnEnterIdleStateOf.TryGetValue(npcId, out int variant) ? OnEnterIdleStateVariants[variant] : [];

    /// <summary>What it does when a player talks to it.</summary>
    internal static PatternBranch[] TalkRungsFor(int npcId)
        => OnTalkedByUserOf.TryGetValue(npcId, out int variant) ? OnTalkedByUserVariants[variant] : [];

    /// <summary>What it does when something it counts as a friend is attacked.</summary>
    internal static PatternBranch[] FriendAttackedRungsFor(int npcId)
        => OnSeeFriendAttackedOf.TryGetValue(npcId, out int variant) ? OnSeeFriendAttackedVariants[variant] : [];

    /// <summary>What it does on reaching a point on its route.</summary>
    internal static PatternBranch[] ArrivedRungsFor(int npcId)
        => OnArrivedAtWaypointOf.TryGetValue(npcId, out int variant) ? OnArrivedAtWaypointVariants[variant] : [];

    /// <summary>What it leaves behind when it is removed without dying.</summary>
    internal static PatternBranch[] DespawnRungsFor(int npcId)
        => OnDespawnOf.TryGetValue(npcId, out int variant) ? OnDespawnVariants[variant] : [];

    /// <summary>What it does when a friend is spelled.</summary>
    internal static PatternBranch[] FriendSpelledRungsFor(int npcId)
        => OnFriendSpelledOf.TryGetValue(npcId, out int variant) ? OnFriendSpelledVariants[variant] : [];

    /// <summary>What it does when it stops running away.</summary>
    internal static PatternBranch[] StopFleeingRungsFor(int npcId)
        => OnStopToFleeOf.TryGetValue(npcId, out int variant) ? OnStopToFleeVariants[variant] : [];

    /// <summary>What it does when a player kills a friend.</summary>
    internal static PatternBranch[] FriendKilledRungsFor(int npcId)
        => OnFriendKilledOf.TryGetValue(npcId, out int variant) ? OnFriendKilledVariants[variant] : [];

    /// <summary>What it does on giving up and heading home.</summary>
    internal static PatternBranch[] EnterReturningRungsFor(int npcId)
        => OnEnterReturnSpOf.TryGetValue(npcId, out int variant) ? OnEnterReturnSpVariants[variant] : [];

    /// <summary>What it does on getting home again.</summary>
    internal static PatternBranch[] LeaveReturningRungsFor(int npcId)
        => OnLeaveReturnSpOf.TryGetValue(npcId, out int variant) ? OnLeaveReturnSpVariants[variant] : [];

    /// <summary>Every npc this table drives.</summary>
    /// <remarks>
    /// The union, not <c>CycleOf</c>. This was the rotation's npc list back when a rotation was the
    /// price of entry; once the table began taking patterns that have only a signal handler -- an
    /// <c>on_despawn</c> that leaves an add, an <c>on_enter_idle_state</c> that spawns one -- reading
    /// it as the cycle's keys would have quietly excluded exactly those npcs from
    /// <c>TheBindingsAndTheTableAgree</c>, which is the pin that catches rows nothing runs.
    /// </remarks>
    internal static IEnumerable<int> Npcs => allOwners ??= BuildAllOwners();

    /// <summary>Built on demand, not in a field initializer.</summary>
    /// <remarks>
    /// <c>EveryOwnerTable</c> is emitted after every table it names, and C# runs static field
    /// initializers in textual order -- so a <c>readonly</c> field here would read it as null and
    /// throw inside the type initializer, taking down everything that touches this class. That is
    /// exactly what it did: 86 tests failed at once, none of them about npc lists.
    /// </remarks>
    private static int[]? allOwners;

    private static int[] BuildAllOwners()
    {{
        HashSet<int> owners = new HashSet<int>();
        foreach (IReadOnlyDictionary<int, int> table in EveryOwnerTable)
        {{
            foreach (int npc in table.Keys)
            {{
                owners.Add(npc);
            }}
        }}

        return [.. owners];
    }}

'''

FOOTER = '''}
'''


def guard_code(token: str) -> str:
    kind, _, argument = token.partition(":")
    if kind == "timer":
        return f"When.Timer({argument})"
    if kind == "class":
        name, classes = argument.split(":")
        listed = ", ".join(f"PlayerClass.{c}" for c in classes.split("+"))
        return f"When.{name}({listed})"
    if kind == "eventskill":
        return f"When.EventSkill({argument})"
    if kind == "abnormal":
        name, state = argument.split(":")
        return f"When.{name}(AbnormalState.{state})"
    if kind == "race":
        name, race = argument.split(":")
        return f"When.{name}(Race.{race})"
    if kind == "within":
        name, metres = argument.split(":")
        return f"When.{name}({metres})"
    if kind == "beyond":
        name, metres = argument.split(":")
        return f"When.{name}({metres})"
    if kind == "hp_of":
        name, percent = argument.split(":")
        return f"When.{name}({percent})"
    if kind == "hp_below":
        return f"When.HpBelow({argument})"
    if kind == "hp_between":
        low, high = argument.split(":")
        return f"When.HpBetween({low}, {high})"
    if kind == "set_flag_var":
        return f"When.FirstTime({argument})"
    if kind == "unset_flag_var":
        return f"When.Consuming({argument})"
    if kind == "set_world_flag_var":
        return f"When.FirstTimeInWorld({argument})"
    if kind == "unset_world_flag_var":
        return f"When.ConsumingWorld({argument})"
    if kind == "is_world_flag_var":
        return f"When.WorldFlagSet({argument})"
    if kind == "message":
        return f"When.Message({argument})"
    if kind == "flying":
        return f"When.{argument}Flying"
    if kind == "chance":
        return f"When.Chance({argument})"
    if kind == "waypoint":
        # Retail's one-based index, carried verbatim; `When.AtWaypoint` does the conversion.
        return f"When.AtWaypoint({argument})"
    if kind == "last_waypoint":
        return "When.AtLastWaypoint"
    if kind == "skillready":
        return f"When.SkillReady({argument})"
    if kind == "who":
        # The parser already resolved the role to its condition name.
        return "When." + argument
    if kind == "enemy":
        # The parser already resolved the role to its condition name.
        return "When." + argument
    if kind == "state":
        return "When." + {"fight": "Fighting", "idle": "Idling", "route": "WalkingItsRoute",
                          "wander": "WanderingAtRandom", "point": "MovingToAPoint",
                          "casting": "Casting"}[argument]
    if kind == "countby":
        slot, step, low, high, at_bound = argument.split(":")
        return (f"When.CountingBy({slot}, {step}, {low}, {high}, "
                f"{'true' if at_bound == '1' else 'false'})")
    if kind == "count":
        # `increase_intvar`, which the idle parser brought when the two merged: a condition that
        # increments as it tests.
        slot, low, high, at_bound = argument.split(":")
        return f"When.Counting({slot}, {low}, {high}, {'true' if at_bound == '1' else 'false'})"
    raise ValueError(f"unknown guard {token}")


def action_code(row: dict) -> str:
    kind = row["kind"]
    if kind == "spawn":
        npc, count, live, group = row["a1"], row["a2"], row["a3"], row["group"]
        place, x, y, z = row["place"], row["x"], row["y"], row["z"]
        # Retail's despawn_at_attack_state: the add goes when the fight does.
        suffix = ""
        if place.startswith("for_the_fight_"):
            place, suffix = place[len("for_the_fight_"):], "ForTheFight"
        if place == "self":
            return f"Do.SpawnNear{suffix}({npc}, {group}, {count}, 0f, {live})"
        if place == "offset":
            return f"Do.SpawnOffset{suffix}({npc}, {group}, {x}f, {y}f, {live}, {z}f)"
        spots = ", ".join(f"new SpawnSpot({x}f, {y}f, {z}f)" for _ in range(max(1, int(count))))
        return f"Do.SpawnAt{suffix}({npc}, {group}, {live}, {spots})"
    if kind == "skill":
        return f"Do.SkillOn(NpcSkillTargetAttribute.{row['place']}, {row['a1']})"
    if kind == "skill_now":
        # The hazard's immediate path; see the extractor. `Do.SkillOn` would queue it and the npc is
        # gone before the queue drains.
        return f"Do.SkillOnSelfNow({row['a1']})"
    if kind == "skill_in_reach":
        return f"Do.SkillOnRankedInReach(AggroTarget.{row['place']}, {row['a1']})"
    if kind == "skill_at":
        return f"Do.SkillOn{row['place']}({row['a1']})"
    if kind == "arm":
        return f"Do.ArmTimer({row['a1']}, {row['a2']})"
    if kind == "despawn":
        return f"Do.Despawn({row['a1']})"
    if kind == "spawn_on_ranked":
        return (f"Do.SpawnOnAttacker(AggroTarget.{row['place']}, {row['a1']}, {row['group']}, "
                f"{row['x']}f, {int(float(row['z']))}, {row['a2']}, {row['y']}f)")
    if kind == "spawn_each":
        return (f"Do.SpawnOnEachTarget({row['a1']}, {row['group']}, {row['x']}f, {row['a2']}, "
                f"MultiTargetOrder.{row['place']}, {row['y']}f, {int(float(row['z']))}, {row['a3']})")
    if kind == "spawn_on_target":
        return (f"Do.SpawnOnTarget({row['a1']}, {row['group']}, {row['a2']}, {row['x']}f, "
                f"{row['a3']}, {int(float(row['z']))}, {row['y']}f)")
    if kind == "spawn_near":
        return f"Do.SpawnNear({row['a1']}, {row['group']}, {row['a2']}, {row['x']}f, {row['a3']})"
    if kind == "switch_to":
        return f"Do.SwitchTarget(AggroTarget.{row['place']})"
    if kind.startswith("hate_at:"):
        return f"Do.{kind[len('hate_at:'):]}({row['a1']})"
    if kind == "hate":
        return f"Do.HateMessageParam({row['a1']})"
    if kind.startswith("switch_to:"):
        return f"Do.{kind[len('switch_to:'):]}()"
    if kind == "switch":
        return "Do.TargetMessageParam()"
    if kind == "attack":
        return "Do.AttackMostHating()"
    if kind == "despawn_self":
        return "Do.DespawnSelf()"
    # The three the idle vocabulary brought when the parsers merged.
    if kind == "timer":
        return f"Do.SetIdleTimer({row['a1']})"
    if kind == "waypoint":
        return f"Do.GotoWaypoint({row['a1']})"
    if kind.startswith("flee_"):
        # The parser resolved the role to its action name.
        return f"Do.{kind[len('flee_'):]}({row['a1']})"
    if kind == "reset_hate":
        return "Do.ResetHate()"
    if kind == "reset_hate_top":
        return "Do.ResetHateExceptTop()"
    if kind == "nothing":
        return "Do.Nothing()"
    if kind == "next_waypoint":
        return "Do.ContinueRoute()"
    if kind == "next_waypoint_run":
        return "Do.ContinueRouteRunning()"
    if kind == "waypoint_run":
        return f"Do.GotoWaypointRunning({row['a1']})"
    if kind == "say":
        return f"Do.Say({row['a1']}, {row['a2']})"
    if kind == "sysmsg":
        return f"Do.SystemMessage({row['a1']}, {row['a2']})"
    if kind == "var":
        return f'Do.SetSpawnVariable("{row["place"]}", {row["a1"]}, {row["a2"]})'
    if kind == "broadcast":
        return f"Do.Broadcast({row['a1']}, {row['a2']}f)"
    raise ValueError(f"unknown action {kind}")


#: How many npcs go into one generated method.
#:
#: A single initializer holding every npc **overflowed the stack the first time the class was touched**
#: -- in the type initializer itself, not in any test harness quirk, so it would have taken the live
#: server down the same way the moment a bound npc entered combat. The table is built by a chain of
#: small methods instead. 100 npcs per method keeps each one well inside what the runtime will start.
CHUNK = 100


def write_table(out, field: str, summary: str, branches, meta, names) -> None:
    """Emit one handler as deduplicated variants plus an npc -> variant map.

    **The rows were 6.7x redundant.** Retail keys a pattern by name and many npcs run the same one, so
    emitting per npc wrote the same branch list once per owner: 166,639 rows for 24,923 distinct ones,
    in a 15MB source file Roslyn chewed through on every build. That was affordable only while the
    table stayed this size, and it is directly in the way of reading more handlers per npc.

    Deduplication is on **the generated text of the branch array**, not on the fields we believe vary.
    That distinction is the safety argument. A rule like "casts vary by npc, everything else is
    pattern-level" happens to be true today -- measured: 0 of 14,921 non-cast sites differ between npcs
    of one pattern -- but it is a claim about the data that a later extractor change could quietly
    falsify. Two npcs share an entry only when the code emitted for them is byte-identical, so this
    cannot lose a difference it failed to anticipate.
    """
    variants: dict[str, int] = {}
    of: dict[int, int] = {}
    for npc in sorted(branches):
        body = []
        for branch in sorted(branches[npc]):
            priority, guards = meta[(npc, branch)]
            tokens = [guard_code(t) for t in guards.split("|") if t]
            condition = "When.Always" if not tokens else "[" + ", ".join(tokens) + "]"
            actions = ",\n".join("                " + action_code(r) for r in branches[npc][branch])
            body.append('            AiPattern.Branch(%d, "rung %d", %s,\n%s),\n'
                        % (priority, branch, condition, actions))
        of[npc] = variants.setdefault("".join(body), len(variants))

    out.write("    /// <summary>" + summary + "</summary>\n")
    out.write("    private static readonly PatternBranch[][] " + field
              + "Variants = Build" + field + "Variants();\n\n")
    ordered = sorted(variants.items(), key=lambda kv: kv[1])
    chunks = [ordered[i:i + CHUNK] for i in range(0, len(ordered), CHUNK)] or [[]]
    out.write("    private static PatternBranch[][] Build" + field + "Variants()\n    {\n")
    out.write("        PatternBranch[][] variants = new PatternBranch[%d][];\n" % len(ordered))
    for index in range(len(chunks)):
        out.write("        " + field + "Variants" + str(index) + "(variants);\n")
    out.write("        return variants;\n    }\n\n")
    for index, chunk in enumerate(chunks):
        out.write("    private static void " + field + "Variants" + str(index)
                  + "(PatternBranch[][] variants)\n    {\n")
        for text, slot in chunk:
            out.write("        variants[%d] = [\n%s        ];\n" % (slot, text))
        out.write("    }\n\n")

    npcs = sorted(of)
    maps = [npcs[i:i + 400] for i in range(0, len(npcs), 400)] or [[]]
    out.write("    private static readonly IReadOnlyDictionary<int, int> " + field
              + "Of = Build" + field + "Of();\n\n")
    out.write("    private static Dictionary<int, int> Build" + field + "Of()\n    {\n")
    out.write("        Dictionary<int, int> owners = new Dictionary<int, int>();\n")
    for index in range(len(maps)):
        out.write("        " + field + "Of" + str(index) + "(owners);\n")
    out.write("        return owners;\n    }\n\n")
    for index, chunk in enumerate(maps):
        out.write("    private static void " + field + "Of" + str(index)
                  + "(Dictionary<int, int> owners)\n    {\n")
        for npc in chunk:
            out.write("        owners[%d] = %d;  // %s\n" % (npc, of[npc], names[npc]))
        out.write("    }\n\n")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("tsv", type=pathlib.Path)
    ap.add_argument("out", type=pathlib.Path)
    args = ap.parse_args()

    lines = args.tsv.read_text(encoding="utf-8").splitlines()
    header = lines[0].split("\t")
    tables: dict[str, dict] = collections.defaultdict(
        lambda: collections.defaultdict(lambda: collections.defaultdict(list)))
    meta: dict[tuple[str, int, int], tuple[int, str]] = {}
    names: dict[int, str] = {}
    actions = 0
    for line in lines[1:]:
        row = dict(zip(header, line.split("\t")))
        npc, branch = int(row["npc"]), int(row["branch"])
        names[npc] = row["pattern"]
        meta[(row["handler"], npc, branch)] = (int(row["priority"]), row["guards"])
        tables[row["handler"]][npc][branch].append(row)
        actions += 1

    with args.out.open("w", encoding="utf-8", newline="\n") as out:
        out.write(HEADER.format(patterns=len(set(names.values())), npcs=len(names), actions=actions))
        for handler, field, summary in HANDLERS:
            # Emitted even when empty: the accessors above name every field unconditionally, and a
            # handler with no rows today is the normal state for the rarer ones rather than a reason
            # to leave a dangling name. `on_leave_attack_state` is exactly that -- every branch retail
            # puts there is currently unsayable, and the field is an empty dictionary saying so.
            write_table(out, field, summary, tables[handler],
                        {(n, b): v for (h, n, b), v in meta.items() if h == handler}, names)

        # Emitted last because it names every field written above. `Npcs` unions these rather than
        # reading the cycle's keys, so an npc whose only rows are in a signal handler is still checked
        # for a binding.
        out.write("    private static readonly IReadOnlyDictionary<int, int>[] EveryOwnerTable =\n")
        out.write("    [\n")
        for _, field, _ in HANDLERS:
            out.write("        " + field + "Of,\n")
        out.write("    ];\n\n")
        out.write(FOOTER)

    print(f"{len(set(names.values()))} patterns, {len(names)} npcs, {actions} actions -> {args.out}")


if __name__ == "__main__":
    main()
