"""Turn the extracted 30002 roster into the C# table the siege protectors read.

Kept separate from `extract_protector_calls.py` so the TSV stays the thing a human reviews.

CLI:
    python emit_protector_calls_table.py out/protector_calls.tsv <out.cs>
"""
from __future__ import annotations

import argparse
import collections
import pathlib

HEADER = '''// <auto-generated>
//     Generated by tools/client-extract/emit_protector_calls_table.py from the retail AI patterns.
//     Do not edit by hand: re-run the extractor instead. See docs/retail-ai-fidelity.md.
// </auto-generated>

using Aion.GameServer.Ai.Pattern;

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// When a siege protector calls its killer to itself: retail's message <c>30002</c>.
/// </summary>
/// <remarks>
/// {rows} npcs across {patterns} retail patterns, and <b>nothing in this port sent it before this
/// table existed</b>. Retail's siege fight is a three-message loop -- the killer wakes and pulls the
/// protectors (30001), a protector calls the killer to itself (30002), a dying protector calls it off
/// (30003) -- and the middle one was missing, so <c>FortressKillerAI</c>'s answer to it had never been
/// reachable. The fight could start and end but never move.
/// <para>
/// <b>The cadence is read out of the timer chain, not assumed.</b> The broadcast hangs off a battle
/// timer several rungs deep, and the chain differs per pattern: {cadences}. The extractor walks
/// timer -> (next timer, delay) edges from the enter-combat rung to the one that broadcasts, and
/// <b>refuses</b> any chain that only reaches the broadcast through a guarded rung -- a chain gated on
/// health has two cadences, not one, and a single number for it would look measured without being so.
/// </para>
/// <para>
/// Some npcs open at zero: retail's village chiefs broadcast in the enter-combat rung itself and then
/// every five seconds, which their own comment on that rung says in as many words.
/// </para>
/// </remarks>
internal static class ProtectorCalls
{{
    /// <param name="First">Milliseconds from entering combat to the first call. Zero means at once.</param>
    /// <param name="Period">Milliseconds between calls thereafter.</param>
    /// <param name="Range">Retail's <c>range_as_meter</c>, which is not the same for every protector.</param>
    internal readonly record struct Call(int First, int Period, float Range);

    internal static readonly IReadOnlyDictionary<int, Call> ByNpc = new Dictionary<int, Call>
    {{
'''

FOOTER = '''    };

    private static readonly System.Collections.Concurrent.ConcurrentDictionary<int, AiPattern> Built =
        new System.Collections.Concurrent.ConcurrentDictionary<int, AiPattern>();

    private static readonly AiPattern Silent = new AiPattern();

    /// <summary>
    /// The call pattern for one protector, or an empty one for the many that never call.
    /// </summary>
    /// <remarks>
    /// <b>Four unrelated classes own npcs in this table</b> -- the two siege protectors, the base
    /// protectors and the simple abyss guards -- and only the first two share a base. So the pattern is
    /// built here, beside the numbers, and each class returns it from its own <c>Pattern</c> property.
    /// The alternative was the same twenty lines in four places, differing by accident within a year.
    /// </remarks>
    internal static AiPattern PatternFor(int npcId) => Built.GetOrAdd(npcId, static id =>
    {
        // The pull call belongs in the SAME enter-combat branch, not behind it: branch lists are
        // first-match-wins, so a second unconditional branch would be dead -- the bug found twice in the
        // fortress killers. 557 siege protectors shout 23200 when pulled, naming the player to every
        // guard around them, and this class had no part of that.
        PatternBranch[] pull = PullCalls.RungFor(id);
        PatternAction[] pullActions = pull.Length == 0 ? [] : pull[0].Actions;

        // The answering half of the same family. 102 artifact protectors answer 23100 in retail and this
        // class had no `on_message` at all, so these fold in additively -- unlike the pull call above,
        // which had to join an existing branch rather than sit behind it.
        PatternBranch[] answers = GuardAnswers.RungsFor(id);

        if (!ByNpc.TryGetValue(id, out Call call))
        {
            return pullActions.Length == 0 && answers.Length == 0
                ? Silent
                : new AiPattern
                {
                    OnMessage = AiPattern.Of(answers),
                    OnEnterAttack = pullActions.Length == 0
                        ? AiPattern.Of()
                        : AiPattern.Of(
                            AiPattern.Branch(7, "pulled -- tell the guards around me", When.Always,
                                pullActions)),
                };
        }

        return new AiPattern
        {
            OnMessage = AiPattern.Of(answers),

            OnEnterAttack = AiPattern.Of(
                call.First == 0
                    ? AiPattern.Branch(7, "call at once, then keep calling", When.Always,
                        [Do.BroadcastAboutSelf(AbstractSiegeProtectorAI.CallTheKiller, call.Range),
                         Do.ArmTimer(0, call.Period), .. pullActions])
                    : AiPattern.Branch(7, "start the chain that reaches the call", When.Always,
                        [Do.ArmTimer(0, call.First), .. pullActions])),

            OnBattleTimer = AiPattern.Of(
                AiPattern.Branch(7, "call the killer to me", [When.Timer(0)],
                    Do.BroadcastAboutSelf(AbstractSiegeProtectorAI.CallTheKiller, call.Range),
                    Do.ArmTimer(0, call.Period))),
        };
    });
}
'''


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("tsv", type=pathlib.Path)
    ap.add_argument("out", type=pathlib.Path)
    args = ap.parse_args()

    rows: list[tuple[int, int, int, int, str]] = []
    patterns: set[str] = set()
    shapes: collections.Counter[tuple[int, int]] = collections.Counter()
    for line in args.tsv.read_text(encoding="utf-8").splitlines()[1:]:
        npc, first, period, reach, pattern = line.split("\t")
        rows.append((int(npc), int(first), int(period), int(reach), pattern))
        patterns.add(pattern)
        shapes[(int(first), int(period))] += 1

    cadences = ", ".join(
        f"{n} npcs first call at {f / 1000:g}s then every {p / 1000:g}s"
        for (f, p), n in shapes.most_common(4))
    header = HEADER.format(rows=len(rows), patterns=len(patterns), cadences=cadences)

    with args.out.open("w", encoding="utf-8", newline="\n") as out:
        out.write(header)
        for npc, first, period, reach, pattern in rows:
            out.write(f"        [{npc}] = new Call({first}, {period}, {reach}f),  // {pattern}\n")
        out.write(FOOTER)

    print(f"{len(rows)} rows -> {args.out}")


if __name__ == "__main__":
    main()
