"""Transcribe Tiamat's rotation TSVs into the C# table the AI reads.

Takes one TSV per boss. Normal and hard mode are **structurally identical** — the
same 45 steps, the same delays, the same coordinates and headings — with an entirely
different cast of thirteen hazards, so they share a class and differ only in data.

Emitted flat and in document order rather than grouped by band, because that is how
retail evaluates it: priorities descend down the file and the first branch whose
guards pass wins. This pattern has a place where the ordering between bands matters
— `BreathL_75-51` guards `51..74` where the M and R steps beside it guard `51..75`,
so at exactly 75 the L step fails and evaluation falls through.

CLI:
    python emit_tiamat_table.py <out.cs> --table 219362=out/tiamat_rotation.tsv \
                                         --table 236277=out/tiamat_rotation_hard.tsv
"""
from __future__ import annotations

import argparse
import pathlib

HEADER = '''// <auto-generated>
//     Generated by tools/client-extract/emit_tiamat_table.py from the retail AI patterns.
//     Do not edit by hand: re-run the extractor instead. See docs/retail-ai-fidelity.md.
// </auto-generated>

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// Tiamat's dying-phase rotation: every battle-timer step, in the order retail evaluates them.
/// </summary>
/// <remarks>
/// {steps} steps per boss across four health bands plus the unbanded heartbeat, placing {npcs}
/// distinct hazards at {rows} fixed points. Read out of
/// <c>IDTiamat_Tiamat_Dragon_Dying_Named_60_Al</c> and <c>IDTiamat_Hard_Tiamat_Dragon_Dying</c>,
/// which are the same table with a different cast.
/// <para>
/// Flat and in document order on purpose. Retail's priorities descend down the file and the first
/// branch whose guards pass wins, and this pattern has a place where the ordering between bands
/// matters: <c>BreathL_75-51</c> guards 51..74 where the M and R steps beside it guard 51..75, so at
/// exactly 75 the L step fails and evaluation falls through. Grouping by band would lose that.
/// </para>
/// </remarks>
internal static class TiamatRotation
{{
    /// <summary>One hazard placed by a step. <paramref name="Degrees"/> is the pattern's own <c>dir</c>.</summary>
    internal readonly record struct Placement(int NpcId, int Count, float X, float Y, float Z, int Degrees, int LiveSeconds);

    /// <summary>One step of the chain.</summary>
    /// <param name="Low">Inclusive band bounds as retail writes them, or 0/100 for the unbanded heartbeat.</param>
    /// <param name="Label">The pattern's own branch comment, kept so the table reads against the digest.</param>
    /// <param name="Banded">False for the heartbeat, which carries no health guard at all.</param>
    /// <param name="SkillIndices">
    /// The <c>SKILLI_INDEX_n</c> values the step casts, in order. Carried rather than resolved: only
    /// some of them map to a known skill id, and that decision belongs to the AI class, not here.
    /// </param>
    internal readonly record struct Step(
        int Timer, int NextTimer, int DelayMillis, int Low, int High, bool Banded,
        string Label, int[] SkillIndices, Placement[] Spawns);

    internal static readonly IReadOnlyDictionary<int, Step[]> ByBoss = new Dictionary<int, Step[]>
    {{
'''

FOOTER = '''    };
}
'''


def read_one(tsv: pathlib.Path):
    """(ordered step keys, step data, rows read, npc ids seen) for one boss's TSV."""
    steps: dict[int, dict] = {}
    order: list[int] = []
    rows = 0
    npcs: set[str] = set()
    for line in tsv.read_text(encoding="utf-8").splitlines():
        parts = line.split("\t")
        if not parts or parts[0] in ("band", ""):
            continue
        (band, step, timer, nxt, delay, label, indices,
         npc_id, count, x, y, z, deg, live) = parts
        step = int(step)
        if step not in steps:
            if band == "any":
                low, high, banded = 0, 100, False
            else:
                lo, hi = band.split("-")
                low, high, banded = int(lo), int(hi), True
            steps[step] = {
                "timer": int(timer), "next": int(nxt), "delay": int(delay),
                "low": low, "high": high, "banded": banded,
                "label": label, "spawns": [],
                "indices": [int(i) for i in indices.split(",") if i],
            }
            order.append(step)
        if npc_id:
            npcs.add(npc_id)
            steps[step]["spawns"].append(
                (npc_id, int(count), x, y, z, str(int(float(deg or 0))), int(live)))
        rows += 1
    return order, steps, rows, npcs


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("out")
    ap.add_argument("--table", action="append", metavar="BOSS_NPC_ID=TSV", required=True,
                    help="repeatable; hard mode is the same table with a different cast")
    args = ap.parse_args()

    body: list[str] = []
    rows = 0
    npcs: set[str] = set()
    steps_each = 0

    for spec in args.table:
        boss_id, tsv = spec.split("=", 1)
        order, steps, read, seen = read_one(pathlib.Path(tsv))
        rows += read
        npcs |= seen
        steps_each = max(steps_each, len(steps))
        body.append("        [" + str(int(boss_id)) + "] =\n        [\n")
        for step in order:
            s = steps[step]
            placements = ", ".join(
                "new Placement({}, {}, {}f, {}f, {}f, {}, {})".format(n, c, x, y, z, d, lv)
                for n, c, x, y, z, d, lv in s["spawns"])
            indices = ", ".join(str(i) for i in s["indices"])
            body.append(
                "            new Step({}, {}, {}, {}, {}, {}, \"{}\", [{}], [{}]),\n".format(
                    s["timer"], s["next"], s["delay"], s["low"], s["high"],
                    "true" if s["banded"] else "false", s["label"], indices, placements))
        body.append("        ],\n")

    out = [HEADER.format(steps=steps_each, npcs=len(npcs), rows=rows)]
    out.extend(body)
    out.append(FOOTER)
    pathlib.Path(args.out).write_text("".join(out), encoding="utf-8")
    print(f"{steps_each} steps per boss, {rows} rows, {len(npcs)} distinct npcs")


if __name__ == "__main__":
    main()
