"""Transcribe guard_answers.tsv into GuardAnswers.cs. See extract_guard_answers.py for the claim."""
from __future__ import annotations

import argparse
import collections
import pathlib

HEADER = '''// <auto-generated>
//     Generated by tools/client-extract/emit_guard_answers_table.py from out/guard_answers.tsv.
//     Do not edit by hand; edit the extractor and re-run.
// </auto-generated>
using Aion.GameServer.Ai;
using Aion.GameServer.Ai.Pattern;
using Aion.GameServer.Model.GameObjects;

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// Who answers a guard's call for help, and with what weight: {rows} answers across {npcs} spawnable
/// npcs.
/// </summary>
/// <remarks>
/// The answering half of the whole call family. Retail gives it exactly two rungs and no third:
/// <c>is_npc_state NPC_STATE_ATTACK</c> answers with <c>switch_target</c>, and the unguarded rung with
/// <c>add_hate_point</c> followed by <c>attack_most_hating</c>. {common} of the {rows} answers carry
/// the common 1/100 pair; the {odd} that do not are carried at their own values rather than flattened.
/// <para>
/// A table rather than a constant because <b>which</b> call an npc answers is per npc, not per class:
/// {protectors} artifact protectors answer <c>23100</c> while keeping a class that has no
/// <c>on_message</c> of its own, which is why <see cref="ProtectorCalls"/> folds these rungs in.
/// </para>
/// </remarks>
internal static class GuardAnswers
{{
    /// <summary>One call an npc answers. <c>Busy</c> is -1 when retail gives it no fighting rung.</summary>
    internal readonly record struct Answer(int Call, int Idle, int Busy);

    /// <summary>Every answer, by npc id.</summary>
    internal static readonly IReadOnlyDictionary<int, Answer[]> ByNpc = new Dictionary<int, Answer[]>
    {{
'''

FOOTER = '''    };

    /// <summary>
    /// The rungs one npc answers with, highest priority first, or empty for an npc that answers nothing.
    /// </summary>
    /// <remarks>
    /// The fighting rung is emitted <b>before</b> the idle one for the same call, because branch lists
    /// are first-match-wins and the idle rung's conditions are a subset of the fighting rung's -- emitted
    /// the other way round, a guard already in combat would take the idle answer and never switch.
    /// </remarks>
    internal static PatternBranch[] RungsFor(int npcId)
    {
        if (!ByNpc.TryGetValue(npcId, out Answer[]? answers))
            return [];

        List<PatternBranch> rungs = new List<PatternBranch>(answers.Length * 2);
        int priority = answers.Length * 2;
        foreach (Answer answer in answers)
        {
            if (answer.Busy >= 0)
            {
                rungs.Add(AiPattern.Branch(priority--, "a call, and I am already fighting",
                    [When.MessageParamIsEnemy, When.Message(answer.Call), When.Fighting],
                    Do.HateMessageTarget(answer.Busy)));
            }

            if (answer.Idle >= 0)
            {
                rungs.Add(AiPattern.Branch(priority--, "a call, and I am not",
                    [When.MessageParamIsEnemy, When.Message(answer.Call)],
                    Do.HateMessageParam(answer.Idle),
                    Do.AttackMostHating()));
            }
        }

        return rungs.ToArray();
    }

    /// <summary>
    /// The same two rungs for a listener that is <b>not</b> pattern-driven, applied directly.
    /// </summary>
    /// <remarks>
    /// Sixteen Ahserion npcs and four others answer <c>23000</c> in retail on classes that run plain
    /// <c>aggressive</c> with cast rotations this work cannot resolve, so there is no pattern to fold
    /// the rungs into. This is the same shape as <see cref="PullCalls"/>.<c>Shout</c>, which exists for
    /// the sending half and for the same reason.
    /// <para>
    /// The idle rung goes through <see cref="SummonOrder"/>, which <b>is</b> <c>add_hate_point</c>
    /// followed by <c>attack_most_hating</c> -- the same pair, already written and already reasoned
    /// about. The fighting rung is a <c>switch_target</c> and cannot use it: that one turns the npc
    /// whether or not the named player is the one it now hates most.
    /// </para>
    /// </remarks>
    /// <returns>true if this npc had an answer for the message, whether or not it landed.</returns>
    internal static bool AnswerCall(Npc listener, Npc sender, int messageType, VisibleObject? param)
    {
        if (listener.IsDead() || ReferenceEquals(sender, listener))
            return false;

        if (!ByNpc.TryGetValue(listener.GetNpcId(), out Answer[]? answers))
            return false;

        foreach (Answer answer in answers)
        {
            if (answer.Call != messageType)
                continue;

            // is_enemy, in the direction the pattern conditions use.
            if (param is not Creature named || named.IsDead() || !named.IsEnemy(listener))
                return true;

            if (answer.Busy >= 0 && listener.GetAi().IsInState(AIState.FIGHT))
            {
                listener.GetAggroList().AddHate(named, answer.Busy);
                listener.SetTarget(named);
                return true;
            }

            if (answer.Idle >= 0)
                SummonOrder.Take(listener, named, answer.Idle);

            return true;
        }

        return false;
    }
}
'''


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("tsv", type=pathlib.Path)
    ap.add_argument("out", type=pathlib.Path)
    args = ap.parse_args()

    by_npc: dict[int, list[tuple[int, int, int]]] = collections.defaultdict(list)
    names: dict[int, str] = {}
    common = odd = 0
    protectors = 0
    for line in args.tsv.read_text(encoding="utf-8").splitlines()[1:]:
        npc, call, idle, busy, pattern = (line.split("\t") + [""] * 5)[:5]
        by_npc[int(npc)].append((int(call), int(idle), int(busy)))
        names[int(npc)] = pattern
        if (int(idle), int(busy)) == (1, 100):
            common += 1
        else:
            odd += 1
        if int(call) == 23100:
            protectors += 1

    rows = sum(len(v) for v in by_npc.values())
    with args.out.open("w", encoding="utf-8", newline="\n") as out:
        out.write(HEADER.format(rows=rows, npcs=len(by_npc), common=common, odd=odd, protectors=102))
        for npc in sorted(by_npc):
            answers = ", ".join(f"new Answer({c}, {i}, {b})" for c, i, b in sorted(by_npc[npc]))
            out.write(f"        [{npc}] = [{answers}],  // {names[npc]}\n")
        out.write(FOOTER)

    print(f"{rows} answers across {len(by_npc)} npcs -> {args.out}")


if __name__ == "__main__":
    main()
