"""Transcribe wake_variables.tsv into WakeVariables.cs. See extract_wake_variables.py for the claim."""
from __future__ import annotations

import argparse
import collections
import pathlib

HEADER = '''// <auto-generated>
//     Generated by tools/client-extract/emit_wake_variables_table.py from out/wake_variables.tsv.
//     Do not edit by hand; edit the extractor and re-run.
// </auto-generated>
namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// Spawn variables retail sets simply by an npc existing: {patterns} patterns, {npcs} npcs, {writes} writes.
/// </summary>
/// <remarks>
/// The conditional spawn engine reads 1,201 distinct variables across 21,096 gated placements, and the
/// death handlers write 101 of them. Classifying the rest by who writes them put <c>on_wake_up</c> at
/// the top by a wide margin -- and it is the simplest entry in the list, an npc announcing that it is
/// there. These 209 patterns write a variable on waking and do nothing else at all.
/// <para>
/// <b>Deliberately not a <see cref="Aion.GameServer.Ai.Pattern.PatternAi"/> table.</b> Most of these
/// npcs are on <c>general</c> and are not aggressive; <c>PatternAi</c> extends <c>AggressiveNpcAI</c>,
/// so feeding them through it would make passive npcs attack on sight. <see cref="WakeVariableAI"/>
/// extends <c>GeneralNpcAI</c> and does the one thing these patterns do.
/// </para>
/// </remarks>
internal static class WakeVariables
{{
    /// <summary>One write: retail's <c>set</c> and <c>modify</c> on a named variable.</summary>
    internal readonly record struct Write(string Name, int Set, int Modify);

    /// <summary>What this npc writes when it appears, or empty for one that writes nothing.</summary>
    internal static Write[] For(int npcId)
        => ByNpc.TryGetValue(npcId, out Write[]? writes) ? writes : [];

    /// <summary>Every npc this table drives.</summary>
    internal static IEnumerable<int> Npcs => ByNpc.Keys;

    private static readonly IReadOnlyDictionary<int, Write[]> ByNpc = new Dictionary<int, Write[]>
    {{
'''

FOOTER = '''    };
}
'''


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("tsv", type=pathlib.Path)
    ap.add_argument("out", type=pathlib.Path)
    args = ap.parse_args()

    lines = args.tsv.read_text(encoding="utf-8").splitlines()
    header = lines[0].split("\t")
    writes: dict[int, list[tuple]] = collections.defaultdict(list)
    names: dict[int, str] = {}
    for line in lines[1:]:
        row = dict(zip(header, line.split("\t")))
        npc = int(row["npc"])
        names[npc] = row["pattern"]
        writes[npc].append((row["name"], int(row["set"]), int(row["modify"])))

    total = sum(len(v) for v in writes.values())
    with args.out.open("w", encoding="utf-8", newline="\n") as out:
        out.write(HEADER.format(patterns=len(set(names.values())), npcs=len(writes), writes=total))
        for npc in sorted(writes):
            body = ", ".join(f'new Write("{n}", {s}, {m})' for n, s, m in writes[npc])
            out.write(f"        [{npc}] = [{body}],  // {names[npc]}\n")
        out.write(FOOTER)

    print(f"{len(set(names.values()))} patterns, {len(writes)} npcs, {total} writes -> {args.out}")


if __name__ == "__main__":
    main()
