"""Turn the extracted pull calls into the C# table the guards read.

CLI:
    python emit_pull_calls_table.py out/pull_calls.tsv <out.cs>
"""
from __future__ import annotations

import argparse
import collections
import pathlib

HEADER = '''// <auto-generated>
//     Generated by tools/client-extract/emit_pull_calls_table.py from the retail AI patterns.
//     Do not edit by hand: re-run the extractor instead. See docs/retail-ai-fidelity.md.
// </auto-generated>
#nullable enable

using Aion.GameServer.Ai.Pattern;

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// What a guard shouts when it is pulled: retail's <c>41000</c>, <c>41001</c>, <c>41100</c>,
/// <c>41101</c> and <c>23200</c>.
/// </summary>
/// <remarks>
/// {rows} calls across {npcs} npcs. **The answering half of this was already ported and the sending half
/// was not** -- 552 npcs listen for 41101 alone, and sixteen sent it.
/// <para>
/// {spread}
/// </para>
/// <para>
/// <b>The call and its range are per npc, not per class.</b> One <c>panesterra_patrol</c> covers guards
/// that shout at thirteen metres and guards that shout at twenty-five; <c>base_protector</c> covers
/// garrison chiefs that shout 41101 and base bosses that shout nothing at all. A constant in a class
/// cannot say that.
/// </para>
/// <para>
/// <b>Some guards shout twice.</b> <c>Gab1_Gaurd_Ra_An_Broad</c> broadcasts 41100 at thirteen metres and
/// again at twenty-five -- a near call and a far one in the same rung -- so this is a list per npc
/// rather than one entry.
/// </para>
/// </remarks>
internal static class PullCalls
{{
    /// <param name="Call">Retail's message number. The captain calls (41001, 41101) are obeyed; the
    /// guard calls (41000, 41100) are only noted.</param>
    /// <param name="Range">Retail's <c>range_as_meter</c>.</param>
    internal readonly record struct Pull(int Call, float Range);

    internal static readonly IReadOnlyDictionary<int, Pull[]> ByNpc = new Dictionary<int, Pull[]>
    {{
'''

FOOTER = '''    };

    private static readonly System.Collections.Concurrent.ConcurrentDictionary<int, PatternBranch[]>
        Built = new System.Collections.Concurrent.ConcurrentDictionary<int, PatternBranch[]>();

    /// <summary>
    /// The enter-combat rung for one guard, or nothing for an npc that is pulled in silence.
    /// </summary>
    /// <remarks>
    /// <b>One branch carrying every call</b>, never one branch each. Branch lists are first-match-wins,
    /// so two unconditional branches would leave the second dead -- which is exactly the bug found twice
    /// in the fortress killers, and retail writes these as one rung with two broadcasts anyway.
    /// </remarks>
    internal static PatternBranch[] RungFor(int npcId) => Built.GetOrAdd(npcId, static id =>
    {
        if (!ByNpc.TryGetValue(id, out Pull[]? calls))
            return [];

        PatternAction[] actions = new PatternAction[calls.Length];
        for (int i = 0; i < calls.Length; i++)
            actions[i] = Do.Broadcast(calls[i].Call, calls[i].Range, aboutTarget: true);

        return [new PatternBranch(7, "pulled -- tell the guards around me", [], actions)];
    });

    /// <summary>
    /// Broadcasts this npc's pull calls directly, for classes that are not <c>PatternAi</c>.
    /// </summary>
    /// <remarks>
    /// <b>Sixty of these npcs are garrison chiefs on <c>BaseProtectorAI</c></b>, which derives from
    /// <c>AggressiveNpcAI</c> and cannot be handed a pattern branch. Its <c>HandleCreatureAggro</c>
    /// already latches -- it broadcasts 30002 there once per fight -- so the call goes beside that one.
    /// <para>
    /// Call it from a latched hook. Retail's rung is <c>on_enter_attack_state</c>, which fires once when
    /// a fight starts; an aggro hook without a latch fires per creature and would shout the whole fight.
    /// </para>
    /// </remarks>
    internal static void Shout(Aion.GameServer.Model.GameObjects.Npc guard)
    {
        if (!ByNpc.TryGetValue(guard.GetNpcId(), out Pull[]? calls))
            return;

        foreach (Pull call in calls)
        {
            Aion.GameServer.Ai.NpcMessageBus.Broadcast(
                guard, call.Call, guard.GetTarget(), call.Range);
        }
    }
}
'''


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("tsv", type=pathlib.Path)
    ap.add_argument("out", type=pathlib.Path)
    args = ap.parse_args()

    by_npc: dict[int, list[tuple[int, int]]] = collections.defaultdict(list)
    pattern_of: dict[int, str] = {}
    shapes: collections.Counter[str] = collections.Counter()
    for line in args.tsv.read_text(encoding="utf-8").splitlines()[1:]:
        npc, call, reach, _names, pattern = line.split("\t")
        by_npc[int(npc)].append((int(call), int(reach)))
        pattern_of[int(npc)] = pattern
        shapes[f"{call} at {reach} metres"] += 1

    spread = "; ".join(f"{n} npcs shout {m}" for m, n in sorted(shapes.items()))
    header = HEADER.format(rows=sum(len(v) for v in by_npc.values()), npcs=len(by_npc), spread=spread)

    with args.out.open("w", encoding="utf-8", newline="\n") as out:
        out.write(header)
        for npc in sorted(by_npc):
            calls = ", ".join(f"new Pull({c}, {r}f)" for c, r in sorted(by_npc[npc]))
            out.write(f"        [{npc}] = [{calls}],  // {pattern_of[npc]}\n")
        out.write(FOOTER)

    print(f"{len(by_npc)} npcs -> {args.out}")


if __name__ == "__main__":
    main()
