"""Turn the extracted guard reinforcement table into the C# table the AI reads.

Kept separate from `extract_guard_reinforcements.py` so the TSV stays the thing a
human reviews: the extraction is the claim about what retail does, and this is only
a transcription of it. Re-run both when the binding table is regenerated.

CLI:
    python emit_guard_table.py out/guard_reinforcements.tsv <out.cs>
"""
from __future__ import annotations

import argparse
import collections
import pathlib

HEADER = '''// <auto-generated>
//     Generated by tools/client-extract/emit_guard_table.py from the retail AI patterns.
//     Do not edit by hand: re-run the extractor instead. See docs/retail-ai-fidelity.md.
// </auto-generated>

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// Which reinforcements each abyss guard calls up, and in which health band.
/// </summary>
/// <remarks>
/// Read straight out of the retail <c>[DL]Guard_*</c> patterns — {rows} rows for {guards} guards
/// across {patterns} pattern variants, all running the same mechanic with a different pair of summons
/// per level bracket and faction. The bands are retail's own guards verbatim, gaps included: a guard
/// written as <c>is_hp_lower_than 35</c> and <c>is_hp_in_boundary 36..70</c> matches nothing at
/// exactly 35, and that is left alone rather than tidied.
/// </remarks>
internal static class GuardReinforcements
{{
    /// <summary>One health band: who is called, how many, and how often.</summary>
    /// <param name="Low">Inclusive lower bound, as retail writes it.</param>
    /// <param name="High">Inclusive upper bound.</param>
    /// <param name="Chance">Percent chance the call happens at all on a given tick.</param>
    /// <param name="OnTarget">
    /// True when retail uses <c>spawn_on_target</c> — the wave lands on whoever the guard is
    /// fighting rather than at the guard's own feet, which is a different fight for the raid.
    /// </param>
    /// <param name="LiveSeconds">
    /// Retail's <c>live_time</c>. Not uniform across the family: the abyss guards give their
    /// reinforcements ten minutes, the drakan guards a hundred seconds.
    /// </param>
    /// <param name="Range">Retail's <c>spawn_range</c>, one to three metres depending on the guard.</param>
    /// <param name="AttackHate">
    /// Retail's <c>hatepoints_to_add</c> where the spawn also carries
    /// <c>attack_target_after_spawn</c>, and 0 where it does not. Non-zero means the summon arrives
    /// <b>already fighting whoever it landed on</b> rather than waiting to be walked into — which for
    /// the rangers' traps and the wizards' frost pillars is the whole mechanic. The values retail
    /// gives here are 1 and 100: enough to start the fight, not enough to hold aggro against a raid.
    /// </param>
    /// <param name="Summons">npc id and count, in the order the pattern lists them.</param>
    internal readonly record struct Band(
        int Low, int High, int Chance, bool OnTarget, int LiveSeconds, float Range, int AttackHate,
        (int NpcId, int Count)[] Summons);

    internal static readonly IReadOnlyDictionary<int, Band[]> ByGuard = new Dictionary<int, Band[]>
    {{
'''

FOOTER = '''    };
}
'''


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("tsv")
    ap.add_argument("out")
    args = ap.parse_args()

    by_guard: dict[int, list[tuple]] = collections.defaultdict(list)
    patterns: set[str] = set()
    rows = 0
    for line in pathlib.Path(args.tsv).read_text(encoding="utf-8").splitlines():
        parts = line.split("\t")
        if not parts or parts[0] in ("guard_npc_id", ""):
            continue
        (guard, pattern, low, high, chance, placement, live, rng, hate, summons) = parts
        patterns.add(pattern)
        pairs = []
        for chunk in summons.split(","):
            npc_id, count = chunk.split("*")
            pairs.append((int(npc_id), int(count)))
        by_guard[int(guard)].append(
            (int(low), int(high), int(chance), placement, int(live), int(rng), int(hate), pairs, pattern))
        rows += 1

    lines = [HEADER.format(rows=rows, guards=len(by_guard), patterns=len(patterns))]
    for guard in sorted(by_guard):
        bands = sorted(by_guard[guard], key=lambda b: -b[0])
        pattern = bands[0][7]
        rendered = []
        for low, high, chance, placement, live, rng, hate, pairs, _p in bands:
            summons = ", ".join(f"({npc}, {count})" for npc, count in pairs)
            on_target = "true" if placement == "TARGET" else "false"
            rendered.append(
                f"new Band({low}, {high}, {chance}, {on_target}, {live}, {rng}f, {hate}, [{summons}])")
        body = ", ".join(rendered)
        lines.append(f"        // {pattern}\n        [{guard}] = [{body}],\n")
    lines.append(FOOTER)
    pathlib.Path(args.out).write_text("".join(lines), encoding="utf-8")
    print(f"{rows} rows -> {len(by_guard)} guards, {len(patterns)} patterns")


if __name__ == "__main__":
    main()
