"""Transcribe tiamat_beacons.tsv into TiamatBeacons.cs. See extract_tiamat_beacons.py for the claim."""
from __future__ import annotations

import argparse
import collections
import pathlib

HEADER = '''// <auto-generated>
//     Generated by tools/client-extract/emit_tiamat_beacons_table.py from out/tiamat_beacons.tsv.
//     Do not edit by hand; edit the extractor and re-run.
// </auto-generated>
using Aion.GameServer.Ai.Pattern;

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// What each Tiamat breath beacon puts on the ground when its timer fires: {rows} placements across
/// {beacons} beacons.
/// </summary>
/// <remarks>
/// The second half of a two-step telegraph. The rotation places the beacon a raid runs out of; the
/// beacon then waits {delay}ms and spawns the damage npcs along the line it marked. This port had the
/// first half only, so every breath in the encounter landed with the warning and none of the damage.
/// <para>
/// The coordinates are absolute in retail (<c>SPAWN_LOCATION_ABSOLUTE</c>) and are carried verbatim
/// rather than derived from the beacon's position. A middle beacon lays eleven in a line and lives two
/// seconds; the left and right ones lay a single wider hit and live three.
/// </para>
/// </remarks>
internal static class TiamatBeacons
{{
    /// <summary>One beacon's answer: the damage npc, how long it lives, and where it lands.</summary>
    internal readonly record struct Breath(int DamageNpc, int LiveSeconds, int DelayMillis,
        bool AtTheBeacon, SpawnSpot[] Spots);

    /// <summary>Every beacon, by npc id.</summary>
    internal static readonly IReadOnlyDictionary<int, Breath> ByBeacon = new Dictionary<int, Breath>
    {{
'''

FOOTER = '''    };

    /// <summary>Retail's own spawn group for these, so the boss can clear them.</summary>
    internal const int Placed = 1;

    /// <summary>
    /// The rung a beacon runs when it lands, or empty for an npc that is not one.
    /// </summary>
    internal static PatternBranch[] WakeRungFor(int npcId)
        => ByBeacon.TryGetValue(npcId, out Breath breath)
            ? [AiPattern.Branch(2, "landed -- start the count", When.Always,
                Do.SetIdleTimer(breath.DelayMillis))]
            : [];

    /// <summary>
    /// The rung that puts the damage down, or empty for an npc that is not a beacon.
    /// </summary>
    internal static PatternBranch[] BreathRungFor(int npcId)
        => ByBeacon.TryGetValue(npcId, out Breath breath)
            ? [AiPattern.Branch(1, "the breath lands", When.Always,
                breath.AtTheBeacon
                    // SPAWN_LOCATION_MY_POINT: the left and right breaths land on the marker itself,
                    // and their blocks carry no coordinates at all.
                    ? Do.SpawnOffset(breath.DamageNpc, Placed, 0f, 0f, breath.LiveSeconds)
                    : Do.SpawnAt(breath.DamageNpc, Placed, breath.LiveSeconds, breath.Spots))]
            : [];
}
'''


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("tsv", type=pathlib.Path)
    ap.add_argument("out", type=pathlib.Path)
    args = ap.parse_args()

    by_beacon: dict[int, list] = collections.defaultdict(list)
    meta: dict[int, tuple] = {}
    names: dict[int, str] = {}
    for line in args.tsv.read_text(encoding="utf-8").splitlines()[1:]:
        beacon, delay, damage, live, at_self, x, y, z, pattern = (line.split("\t") + [""] * 9)[:9]
        by_beacon[int(beacon)].append((float(x), float(y), float(z)))
        meta[int(beacon)] = (int(damage), int(live), int(delay), int(at_self))
        names[int(beacon)] = pattern

    rows = sum(len(v) for v in by_beacon.values())
    delays = {m[2] for m in meta.values()}
    with args.out.open("w", encoding="utf-8", newline="\n") as out:
        out.write(HEADER.format(rows=rows, beacons=len(by_beacon),
                                delay=sorted(delays)[0] if len(delays) == 1 else "2000"))
        for beacon in sorted(by_beacon):
            damage, live, delay, at_self = meta[beacon]
            spots = "" if at_self else ", ".join(
                f"new SpawnSpot({x}f, {y}f, {z}f)" for x, y, z in by_beacon[beacon])
            out.write(f"        [{beacon}] = new Breath({damage}, {live}, {delay}, "
                      f"{'true' if at_self else 'false'}, [{spots}]),"
                      f"  // {names[beacon]}\n")
        out.write(FOOTER)

    print(f"{rows} placements across {len(by_beacon)} beacons -> {args.out}")


if __name__ == "__main__":
    main()
