"""Transcribe npc_autonomous_skills.tsv into retail_autonomous.xml.

See extract_npc_autonomous_skills.py for what `skill_rate` means and how that was settled.
"""
from __future__ import annotations

import argparse
import collections
import pathlib

HEADER = '''<?xml version="1.0" encoding="UTF-8"?>
<!--
    Generated by tools/client-extract/emit_npc_autonomous_skills.py from
    out/npc_autonomous_skills.tsv. Do not edit by hand; edit the extractor and re-run.

    Retail's own skill lists for npcs this port had none for: {npcs} npcs, {skills} skills, of which
    {casting} npcs cast at least one on their own.

    `prob` is retail's `skill_rate` converted from per mille and clamped at 100. `cd` is the skill's
    own `delay_time` from skill_base.xml, in milliseconds. Entries with prob="0" are never chosen,
    because Rnd.Chance() is never below zero; they are kept because they put the npc's real ordered
    list in front of When.SkillReady, which is what that condition reads.

    Npcs this port already had a list for are deliberately absent. Those carry aionemu's own tuning
    and this file does not overwrite it.
-->
<npc_skill_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="npc_skills.xsd">
'''

FOOTER = "</npc_skill_templates>\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("tsv", type=pathlib.Path)
    ap.add_argument("out", type=pathlib.Path)
    args = ap.parse_args()

    lines = args.tsv.read_text(encoding="utf-8").splitlines()
    header = lines[0].split("\t")
    by_npc: dict[int, list[tuple]] = collections.defaultdict(list)
    for line in lines[1:]:
        row = dict(zip(header, line.split("\t")))
        by_npc[int(row["npc"])].append(
            (int(row["index"]), int(row["skill"]), int(row["level"]),
             int(row["prob"]), int(row["cooldown"])))

    skills = sum(len(v) for v in by_npc.values())
    casting = sum(1 for v in by_npc.values() if any(e[3] > 0 for e in v))
    with args.out.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(HEADER.format(npcs=len(by_npc), skills=skills, casting=casting))
        for npc in sorted(by_npc):
            handle.write(f'\t<npc_skills npc_ids="{npc}">\n')
            for _, skill, level, prob, cooldown in sorted(by_npc[npc]):
                handle.write(f'\t\t<npc_skill id="{skill}" lv="{level}" '
                             f'prob="{prob}" cd="{cooldown}" />\n')
            handle.write("\t</npc_skills>\n")
        handle.write(FOOTER)

    print(f"{len(by_npc)} npcs, {skills} skills, {casting} casting -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
