"""Turn the extracted death-call roster into the C# table the siege protectors read.

Kept separate from `extract_siege_death_calls.py` so the TSV stays the thing a human reviews: the
extraction is the claim about what retail does, and this is only a transcription of it.

CLI:
    python emit_siege_death_calls_table.py out/siege_death_calls.tsv <out.cs>
"""
from __future__ import annotations

import argparse
import collections
import pathlib

HEADER = '''// <auto-generated>
//     Generated by tools/client-extract/emit_siege_death_calls_table.py from the retail AI patterns.
//     Do not edit by hand: re-run the extractor instead. See docs/retail-ai-fidelity.md.
// </auto-generated>
#nullable enable

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// Which npcs announce their own death with retail's message <c>30003</c>.
/// </summary>
/// <remarks>
/// {rows} npcs across {patterns} retail patterns, and the point of the table is everything it leaves
/// out. <see cref="AbstractSiegeProtectorAI"/> used to broadcast 30003 from every death it handled --
/// 1,219 npcs -- where retail sends it from a small minority of them. <c>FortressKillerAI</c> answers
/// 30003 by standing down, so the surplus was not a spare message: it was fortress killers being called
/// off by protectors that in retail die quietly.
/// <para>
/// Retail spells the trigger three ways and all three are collected here: <c>on_die</c>, used by the
/// artifact guards, and the pair <c>on_killed_by_user</c> / <c>on_killed_by_npc</c>, used by the village
/// chiefs. A pattern that only <em>listens</em> for 30003 is excluded -- that is what the killers do,
/// and including them would hand the message to the npcs meant to answer it.
/// </para>
/// <para>
/// The range is a column rather than a constant even though it is fifty everywhere it appears: {ranges}.
/// A hard-coded range in this project has been wrong twice, and carrying the real one costs nothing.
/// </para>
/// </remarks>
internal static class SiegeDeathCalls
{{
    /// <summary>Range in metres, by npc id. An npc absent from this table does not announce its death.</summary>
    internal static readonly IReadOnlyDictionary<int, float> ByNpc = new Dictionary<int, float>
    {{
'''

FOOTER = '''    };

    /// <summary>
    /// Broadcasts retail's <c>30003</c> for <paramref name="dying"/>, if its pattern carries the rung.
    /// </summary>
    /// <remarks>
    /// <b>Three unrelated classes own npcs in this table</b> -- the two siege protectors, the base
    /// protectors and the simple abyss guards -- so the check lives with the data rather than being
    /// copied into each death handler. An npc absent from the table is silent, which is the default and
    /// the common case: 475 npcs in the whole dump announce their death and everything else dies quietly.
    /// <para>
    /// Call it <b>first</b> in a death handler. Retail puts the broadcast at the head of its rung, and
    /// everything after it in these classes reaches a service -- siege, base capture -- that can fail
    /// or return early, which would swallow the message.
    /// </para>
    /// </remarks>
    internal static void Announce(Aion.GameServer.Model.GameObjects.Npc dying)
    {
        if (ByNpc.TryGetValue(dying.GetNpcId(), out float reach))
        {
            Aion.GameServer.Ai.NpcMessageBus.Broadcast(
                dying, AbstractSiegeProtectorAI.ProtectorDown, dying, reach);
        }
    }
}
'''


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("tsv", type=pathlib.Path)
    ap.add_argument("out", type=pathlib.Path)
    args = ap.parse_args()

    rows: list[tuple[int, int, str]] = []
    patterns: set[str] = set()
    ranges: collections.Counter[int] = collections.Counter()
    for line in args.tsv.read_text(encoding="utf-8").splitlines()[1:]:
        npc, reach, pattern = line.split("\t")
        rows.append((int(npc), int(reach), pattern))
        patterns.add(pattern)
        ranges[int(reach)] += 1

    spread = ", ".join(f"{n} of them at {m} metres" for m, n in sorted(ranges.items()))
    header = HEADER.format(rows=len(rows), patterns=len(patterns), ranges=spread)

    with args.out.open("w", encoding="utf-8", newline="\n") as out:
        out.write(header)
        for npc, reach, pattern in rows:
            out.write(f"        [{npc}] = {reach}f,  // {pattern}\n")
        out.write(FOOTER)

    print(f"{len(rows)} rows -> {args.out}")


if __name__ == "__main__":
    main()
