"""Transcribe death_spawns.tsv into DeathSpawns.g.cs. See extract_death_spawns.py for the claim."""
from __future__ import annotations

import argparse
import collections
import pathlib
import xml.dom.minidom
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from emit_battle_cycles_table import action_code, guard_code  # noqa: E402

XML_HEADER = '''<?xml version="1.0" encoding="UTF-8"?>
<!--
    Generated by tools/client-extract/emit_death_spawns_table.py from out/death_spawns.tsv.
    Do not edit by hand; edit the extractor and re-run.

    What an npc leaves behind when it dies: {patterns} retail patterns across {npcs} npcs,
    {actions} actions.

    Branch order is the order written here and is not sorted by priority. Retail's lists are
    first-match-wins and this table emits a handler's rungs together, so re-ordering would change
    which one fires. PatternTableData preserves it.

    This was 12,656 lines of generated C#. See PatternTableLoader for how a guard token and an
    action row become the guards and actions a PatternAi runs.
-->
<pattern_table>
'''


def escape(value: str) -> str:
    """XML attribute escaping. `kind` and `place` carry colons and underscores, never markup, but
    the pattern names in comments are retail's and are not ours to trust."""
    return (value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;"))

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("tsv", type=pathlib.Path)
    ap.add_argument("out", type=pathlib.Path)
    args = ap.parse_args()

    lines = args.tsv.read_text(encoding="utf-8").splitlines()
    header = lines[0].split("\t")
    branches: dict[int, dict[tuple[str, int], list[dict]]] = collections.defaultdict(
        lambda: collections.defaultdict(list))
    meta: dict[tuple[int, str, int], tuple[int, str, str]] = {}
    names: dict[int, str] = {}
    actions = 0
    for line in lines[1:]:
        row = dict(zip(header, line.split("\t")))
        npc, branch = int(row["npc"]), int(row["branch"])
        key = (row["handler"], branch)
        names[npc] = row["pattern"]
        meta[(npc, row["handler"], branch)] = (int(row["priority"]), row["guards"], row["killer"])
        branches[npc][key].append(row)
        actions += 1


    with args.out.open("w", encoding="utf-8", newline="\n") as out:
        out.write(XML_HEADER.format(patterns=len(set(names.values())), npcs=len(names), actions=actions))
        for npc in sorted(names):
            label = names[npc].replace("--", "-")
            out.write(f'\t<npc id="{npc}">  <!-- {label} -->\n')
            for handler, branch in sorted(branches[npc]):
                priority, guards, killer = meta[(npc, handler, branch)]
                tokens = [t for t in guards.split("|") if t]
                # The killer handlers are on_die plus a question about who did it.
                if killer != "ANY":
                    tokens.insert(0, "who:" + killer)
                out.write(f'\t\t<branch priority="{priority}" comment="{handler} {branch}">\n')
                for token in tokens:
                    out.write(f'\t\t\t<guard token="{escape(token)}" />\n')
                for row in branches[npc][(handler, branch)]:
                    out.write(
                        f'\t\t\t<action kind="{escape(row["kind"])}"'
                        f' a1="{row["a1"]}" a2="{row["a2"]}" a3="{row["a3"]}"'
                        f' place="{escape(row["place"])}"'
                        f' x="{row["x"]}" y="{row["y"]}" z="{row["z"]}"'
                        f' group="{row["group"]}" />\n')
                out.write(f'\t\t</branch>\n')
            out.write(f'\t</npc>\n')
        out.write("</pattern_table>" + "\n")

    # Parse what was written. A double dash in a comment is an XML error that reads as two thousand
    # unrelated red tests, because DataManager cannot load at all.
    xml.dom.minidom.parse(str(args.out))

    print(f"{len(set(names.values()))} patterns, {len(names)} npcs, {actions} actions -> {args.out}")


if __name__ == "__main__":
    main()
