"""Transcribe idle_cycles.tsv into IdleCycles.cs. See extract_idle_cycles.py for the claim."""
from __future__ import annotations

import argparse
import collections
import pathlib

HEADER = '''// <auto-generated>
//     Generated by tools/client-extract/emit_idle_cycles_table.py from out/idle_cycles.tsv.
//     Do not edit by hand; edit the extractor and re-run.
// </auto-generated>
using Aion.GameServer.Ai.Pattern;

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// Guarded, multi-branch idle cycles: {patterns} retail patterns across {npcs} npcs, {actions} actions.
/// </summary>
/// <remarks>
/// The wave controllers <see cref="IdleSpawns"/> could not express. Those are a single unguarded rung;
/// these carry two to ten branches guarded by retail's flag idiom or a probability roll, and between
/// them they hold most of the <c>set_condition_spawn_variable</c> writers the conditional spawn engine
/// was waiting for.
/// <para>
/// <b>Branches are emitted in retail's own order and so are the actions inside them.</b> Branch lists
/// are first-match-wins, and a rung that spawns and then despawns itself means nothing in the other
/// order -- the extractor carries an explicit sequence for exactly that reason.
/// </para>
/// <para>
/// Flags are numbered by family: ALPHA, BETA, DELTA, EPSILON, GAMMA, ZETA times five, plus n-1, which
/// fits retail's thirty indicators into its thirty-two slots.
/// </para>
/// </remarks>
internal static class IdleCycles
{{
    /// <summary>Retail's <c>SPAWN_ID_NONE</c> on these rungs: the cycle does not track what it placed.</summary>
    internal const int Untracked = 0;

    /// <summary>How long after waking the cycle first fires, by npc.</summary>
    internal static readonly IReadOnlyDictionary<int, int> WakeMillis = new Dictionary<int, int>
    {{
'''

MIDDLE = '''    };

    /// <summary>The rung that starts the cycle, or empty for an npc that has none.</summary>
    internal static PatternBranch[] WakeRungFor(int npcId)
        => WakeMillis.TryGetValue(npcId, out int delay)
            ? [AiPattern.Branch(7, "start the cycle", When.Always, Do.SetIdleTimer(delay))]
            : [];

    /// <summary>Everything the cycle does when it fires, in retail's order.</summary>
    internal static PatternBranch[] CycleRungsFor(int npcId)
        => Rungs.TryGetValue(npcId, out PatternBranch[]? rungs) ? rungs : [];

    private static readonly IReadOnlyDictionary<int, PatternBranch[]> Rungs =
        new Dictionary<int, PatternBranch[]>
    {
'''

FOOTER = '''    };
}
'''


def guard_code(token: str) -> str:
    kind, _, argument = token.partition(":")
    if kind == "count":
        slot, low, high, at_bound = argument.split(":")
        return f"When.Counting({slot}, {low}, {high}, {'true' if at_bound == '1' else 'false'})"
    if kind == "set_flag_var":
        return f"When.FirstTime({argument})"
    if kind == "unset_flag_var":
        return f"When.Consuming({argument})"
    if kind == "set_world_flag_var":
        return f"When.FirstTimeInWorld({argument})"
    if kind == "unset_world_flag_var":
        return f"When.ConsumingWorld({argument})"
    if kind == "is_world_flag_var":
        return f"When.WorldFlagSet({argument})"
    if kind == "chance":
        return f"When.Chance({argument})"
    raise ValueError(f"unknown guard {token}")


def action_code(row: dict) -> str:
    kind = row["kind"]
    if kind == "spawn":
        npc, count, live = row["a1"], row["a2"], row["a3"]
        place, x, y, z = row["place"], row["x"], row["y"], row["z"]
        if place == "self":
            return f"Do.SpawnNear({npc}, Untracked, {count}, 0f, {live})"
        if place == "offset":
            return f"Do.SpawnOffset({npc}, Untracked, {x}f, {y}f, {live}, {z}f)"
        spots = ", ".join(f"new SpawnSpot({x}f, {y}f, {z}f)" for _ in range(max(1, int(count))))
        return f"Do.SpawnAt({npc}, Untracked, {live}, {spots})"
    if kind == "timer":
        return f"Do.SetIdleTimer({row['a1']})"
    if kind == "var":
        return f'Do.SetSpawnVariable("{row["place"]}", {row["a1"]}, {row["a2"]})'
    if kind == "say":
        return f"Do.Say({row['a1']}, {row['a2']})"
    if kind == "sysmsg":
        return f"Do.SystemMessage({row['a1']}, {row['a2']})"
    if kind == "despawn_self":
        return "Do.DespawnSelf()"
    if kind == "broadcast":
        return f"Do.Broadcast({row['a1']}, {row['a2']}f)"
    raise ValueError(f"unknown action {kind}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("tsv", type=pathlib.Path)
    ap.add_argument("out", type=pathlib.Path)
    args = ap.parse_args()

    lines = args.tsv.read_text(encoding="utf-8").splitlines()
    header = lines[0].split("\t")
    branches: dict[int, dict[int, list[dict]]] = collections.defaultdict(
        lambda: collections.defaultdict(list))
    wake: dict[int, int] = {}
    meta: dict[tuple[int, int], tuple[int, str]] = {}
    names: dict[int, str] = {}
    actions = 0
    for line in lines[1:]:
        row = dict(zip(header, line.split("\t")))
        npc = int(row["npc"])
        branch = int(row["branch"])
        wake[npc] = int(row["wake_ms"])
        names[npc] = row["pattern"]
        meta[(npc, branch)] = (int(row["priority"]), row["guards"])
        branches[npc][branch].append(row)
        actions += 1

    with args.out.open("w", encoding="utf-8", newline="\n") as out:
        out.write(HEADER.format(patterns=len(set(names.values())), npcs=len(wake), actions=actions))
        for npc in sorted(wake):
            out.write(f"        [{npc}] = {wake[npc]},  // {names[npc]}\n")

        out.write(MIDDLE)
        for npc in sorted(branches):
            out.write(f"        [{npc}] = [  // {names[npc]}\n")
            for branch in sorted(branches[npc]):
                priority, guards = meta[(npc, branch)]
                tokens = [guard_code(t) for t in guards.split("|") if t]
                condition = "When.Always" if not tokens else "[" + ", ".join(tokens) + "]"
                body = ",\n".join("                " + action_code(r)
                                  for r in branches[npc][branch])
                out.write(f'            AiPattern.Branch({priority}, "rung {branch}", {condition},\n')
                out.write(body + "),\n")
            out.write("        ],\n")
        out.write(FOOTER)

    print(f"{len(set(names.values()))} patterns, {len(wake)} npcs, {actions} actions -> {args.out}")


if __name__ == "__main__":
    main()
