#!/usr/bin/env python3
"""Re-run every generator that feeds committed data, and report crashes and drift.

WHY THIS EXISTS
---------------
Five scripts here write tables into `out/`, which are then emitted as generated C# and shipped. All
five are invoked by hand, and nothing re-runs them. So a script can stop working and stay broken:

> `extract_gate_squads.py` raised `ValueError: too many values to unpack` on **every** run for as long
> as it had existed. `Carry attack_target_after_spawn through the guard table` added a sixth field to
> `spawns_in()` ten minutes after `Wire the fortress gates` started importing it and unpacking exactly
> five. The committed table was fine -- it predated the sixth field -- so nothing looked wrong, and the
> gates simply could not be regenerated. The next person to try would have blamed their own change.

This runs all five and diffs each against what is committed. It is the check that would have caught
that the same day.

WHAT DRIFT MEANS
----------------
A drift report is **not** automatically a defect. It means the committed table no longer matches what
the current script produces from the current patterns, which happens for three quite different reasons:

* the script was fixed and the table has not been regenerated -- regenerate it;
* the script was changed and the change was wrong -- fix the script;
* the table was hand-edited after generation -- which the `<auto-generated>` headers forbid, and this
  is how you would find out.

It cannot tell you which. It tells you the three files that need looking at instead of eighty.

Exits non-zero if anything crashed or drifted, so it can be wired into CI once the client XML is
available there. It needs the retail pattern dump, so it is a developer command rather than a test.

Usage:  python regen_check.py [--xml DIR]
"""
import argparse
import pathlib
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
BINDING = HERE / "out" / "ai_binding.tsv"

# (script, committed table, extra args). The tiamat extractor is listed twice because normal and hard
# mode are one script with a --pattern switch and two committed tables; running only the default would
# leave the hard table unchecked, which is exactly the kind of gap this script exists to close.
GENERATORS = [
    ("extract_guard_reinforcements.py", "guard_reinforcements.tsv", []),
    ("extract_gate_squads.py", "gate_squads.tsv", []),
    ("extract_vritra_callers.py", "vritra_callers.tsv", []),
    ("extract_tiamat_rotation.py", "tiamat_rotation.tsv", []),
    ("extract_tiamat_rotation.py", "tiamat_rotation_hard.tsv",
     ["--pattern", "IDTiamat_Hard_Tiamat_Dragon_Dying"]),
]

# Same job, different CLI: it takes the output path positionally and has no --out.
POSITIONAL_OUT = [("extract_guard_calls.py", "guard_calls.tsv")]


def run(script, args):
    result = subprocess.run([sys.executable, str(HERE / script), *args],
                            capture_output=True, text=True, errors="replace")
    return result.returncode, result.stderr


def compare(label, produced, committed, problems):
    if not committed.exists():
        problems.append(f"{label}: no committed table at {committed.name}")
        return
    want = sorted(committed.read_text(encoding="utf-8").splitlines())
    got = sorted(produced.read_text(encoding="utf-8").splitlines())
    if want == got:
        print(f"  ok       {label}")
        return
    added = len([ln for ln in got if ln not in set(want)])
    removed = len([ln for ln in want if ln not in set(got)])
    problems.append(f"{label}: DRIFT, {added} rows added and {removed} removed vs {committed.name}")
    print(f"  DRIFT    {label}  (+{added} -{removed})")


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--xml", default="D:/Aion58ServerTesting/Server/Map/XML")
    args = ap.parse_args()

    if not pathlib.Path(args.xml).is_dir():
        print(f"retail pattern dump not found at {args.xml}; nothing to check", file=sys.stderr)
        return 2

    problems = []
    with tempfile.TemporaryDirectory() as tmp:
        tmpdir = pathlib.Path(tmp)
        for script, table, extra in GENERATORS:
            out = tmpdir / table
            code, err = run(script, [args.xml, str(BINDING), "--out", str(out), *extra])
            if code != 0:
                tail = "\n      ".join(err.strip().splitlines()[-3:])
                problems.append(f"{script} -> {table}: CRASHED\n      {tail}")
                print(f"  CRASH    {script} -> {table}")
                continue
            compare(f"{script} -> {table}", out, HERE / "out" / table, problems)

        for script, table in POSITIONAL_OUT:
            out = tmpdir / table
            code, err = run(script, [args.xml, str(BINDING), str(out)])
            if code != 0:
                tail = "\n      ".join(err.strip().splitlines()[-3:])
                problems.append(f"{script} -> {table}: CRASHED\n      {tail}")
                print(f"  CRASH    {script} -> {table}")
                continue
            compare(f"{script} -> {table}", out, HERE / "out" / table, problems)

    print()
    if not problems:
        print("every generator runs and reproduces its committed table")
        return 0
    print(f"{len(problems)} problem(s):")
    for p in problems:
        print(f"  {p}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
