using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;

namespace Aion.GameServer.World.Spawns;

/// <summary>
/// The conditional spawn groups retail keeps in its world files, read from
/// <c>spawns/gated/gated_spawns.tsv</c>.
/// </summary>
/// <remarks>
/// 21,096 placements across 97 maps, extracted by <c>tools/client-extract/extract_gated_spawns.py</c>
/// from 78,865 that retail gates. The rest name npcs this port has no template for (50,841) or sit in
/// worlds <c>world_maps.xml</c> does not name (3,916) — a world with no map id cannot be loaded however
/// good its data is.
/// <para>
/// <b>A tab-separated file rather than XML</b>, which is this project's usual shape for game data.
/// It is generated wholesale from the client and regenerated by the extractor, never hand-edited, and
/// twenty-one thousand rows of XML would be several megabytes to parse at every start for no gain. The
/// extractor is the schema.
/// </para>
/// <para>
/// <b>Only about 7% hold on an empty store</b> — 1,447 of them — so loading this places roughly that
/// many npcs at world start and leaves the rest waiting on a condition. That number is worth knowing
/// before wondering why a world looks emptier than the file suggests.
/// </para>
/// </remarks>
public static class GatedSpawnData
{
	/// <summary>Where the file lives, relative to the data root.</summary>
	public const string RelativePath = "spawns/gated/gated_spawns.tsv";

	/// <summary>Reads the file and groups it by map, skipping rows retail itself ships broken.</summary>
	/// <param name="path">The file; callers usually build this from the configured data root.</param>
	/// <returns>Map id to the groups on that map.</returns>
	public static IReadOnlyDictionary<int, IReadOnlyList<GatedSpawn>> Load(string path)
	{
		ArgumentException.ThrowIfNullOrEmpty(path);

		var byMap = new Dictionary<int, List<GatedSpawn>>();
		if (!File.Exists(path))
			return byMap.ToDictionary(e => e.Key, e => (IReadOnlyList<GatedSpawn>)e.Value);

		foreach (string line in File.ReadLines(path).Skip(1))
		{
			string[] fields = line.Split('\t');
			if (fields.Length < 10)
				continue;

			if (!int.TryParse(fields[0], out int mapId) || !int.TryParse(fields[2], out int npcId))
				continue;

			SpawnCondition gate;
			try
			{
				gate = SpawnCondition.Parse(fields[9]);
			}
			catch (FormatException)
			{
				// Nine gates in the dump are truncated or pasted into themselves by retail. Guessing at
				// what they meant would invent a mechanic; the group stays unplaced.
				continue;
			}

			var group = new GatedSpawn(npcId,
				Number(fields[3]), Number(fields[4]), Number(fields[5]),
				(byte)(int)Number(fields[6]),
				int.TryParse(fields[7], out int respawn) ? respawn : 0,
				string.Equals(fields[8], "TRUE", StringComparison.OrdinalIgnoreCase),
				gate);

			if (!byMap.TryGetValue(mapId, out List<GatedSpawn>? groups))
				byMap[mapId] = groups = new List<GatedSpawn>();

			groups.Add(group);
		}

		return byMap.ToDictionary(e => e.Key, e => (IReadOnlyList<GatedSpawn>)e.Value);
	}

	private static float Number(string text)
		=> float.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out float value)
			? value
			: 0f;
}
