// <auto-generated>
//     Generated by tools/client-extract/emit_battle_cycles_table.py from out/battle_cycles.tsv.
//     Do not edit by hand; edit the extractor and re-run.
// </auto-generated>
using Aion.GameServer.Ai.Pattern;

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// Combat rotations: 10 retail patterns across 15 npcs, 50 actions.
/// </summary>
/// <remarks>
/// What a boss does <b>during</b> the fight, as opposed to <see cref="IdleCycles"/>, which is what an
/// npc does while nothing is happening. Retail arms a battle timer on entering combat and every timer
/// branch arms the next link itself, so a fight is a chain of timers rather than an HP ladder.
/// <para>
/// The arming rung runs on <c>on_enter_attack_state</c>; the cycle rungs run when the timer fires and
/// are guarded by its indicator, so two rotations on different indicators do not disturb each other.
/// <see cref="PatternAi"/> cancels every timer when the fight ends, which is why nothing here needs to
/// clean up after itself.
/// </para>
/// <para>
/// <b>Spawn groups are real here.</b> The idle table spawns into <c>Untracked</c> because nothing there
/// refers back to what it placed; a rotation that despawns its adds needs the group it spawned into.
/// </para>
/// </remarks>
internal static class BattleCycles
{
    /// <summary>What the npc does on entering combat -- normally arming the first timer.</summary>
    internal static PatternBranch[] ArmingRungsFor(int npcId)
        => Arming.TryGetValue(npcId, out PatternBranch[]? rungs) ? rungs : [];

    /// <summary>What each timer does when it fires, in retail's order.</summary>
    internal static PatternBranch[] CycleRungsFor(int npcId)
        => Cycle.TryGetValue(npcId, out PatternBranch[]? rungs) ? rungs : [];

    /// <summary>Every npc this table drives.</summary>
    internal static IEnumerable<int> Npcs => Cycle.Keys;

    /// <summary>Arms the first timer when the fight starts.</summary>
    private static readonly IReadOnlyDictionary<int, PatternBranch[]> Arming =
        new Dictionary<int, PatternBranch[]>
    {
        [219549] = [  // IDAbRe_Core_FlyingWorm_02
            AiPattern.Branch(2, "rung 0", When.Always,
                Do.ArmTimer(0, 10000)),
        ],
        [219560] = [  // IDAbRe_Core_FlyingWorm_02
            AiPattern.Branch(2, "rung 0", When.Always,
                Do.ArmTimer(0, 10000)),
        ],
        [280968] = [  // ND2_GKSum1
            AiPattern.Branch(7, "rung 0", When.Always,
                Do.ArmTimer(0, 10000)),
        ],
        [282141] = [  // IDAbRe_Core_Summon4
            AiPattern.Branch(2, "rung 0", When.Always,
                Do.ArmTimer(0, 3000)),
        ],
        [282142] = [  // IDAbRe_Core_Summon4_3
            AiPattern.Branch(2, "rung 0", When.Always,
                Do.ArmTimer(0, 3000)),
        ],
        [282143] = [  // IDAbRe_Core_Summon4_6
            AiPattern.Branch(2, "rung 0", When.Always,
                Do.ArmTimer(0, 3000)),
        ],
        [282144] = [  // IDAbRe_Core_Summon4_Low
            AiPattern.Branch(2, "rung 0", When.Always,
                Do.ArmTimer(0, 9000)),
        ],
        [282183] = [  // IDHouse_Zadra_Blaze_Move
            AiPattern.Branch(3, "rung 0", When.Always,
                Do.ArmTimer(0, 1000),
                Do.SpawnNear(282184, 1, 1, 0f, 38)),
        ],
        [282264] = [  // D3_NeP_S
            AiPattern.Branch(19, "rung 0", When.Always,
                Do.ArmTimer(0, 2000)),
        ],
        [282307] = [  // IDForest_Prime_Sum1
            AiPattern.Branch(2, "rung 0", When.Always,
                Do.ArmTimer(0, 3000)),
        ],
        [283106] = [  // IDTiamat_Tahabata_Blaze
            AiPattern.Branch(2, "rung 0", When.Always,
                Do.ArmTimer(0, 2000)),
        ],
        [283107] = [  // IDTiamat_Tahabata_Blaze
            AiPattern.Branch(2, "rung 0", When.Always,
                Do.ArmTimer(0, 2000)),
        ],
        [283230] = [  // IDAbRe_Core_Summon4
            AiPattern.Branch(2, "rung 0", When.Always,
                Do.ArmTimer(0, 3000)),
        ],
        [283231] = [  // IDAbRe_Core_Summon4_3
            AiPattern.Branch(2, "rung 0", When.Always,
                Do.ArmTimer(0, 3000)),
        ],
        [283232] = [  // IDAbRe_Core_Summon4_6
            AiPattern.Branch(2, "rung 0", When.Always,
                Do.ArmTimer(0, 3000)),
        ],
    };

    /// <summary>The rotation itself, chosen by which timer fired.</summary>
    private static readonly IReadOnlyDictionary<int, PatternBranch[]> Cycle =
        new Dictionary<int, PatternBranch[]>
    {
        [219549] = [  // IDAbRe_Core_FlyingWorm_02
            AiPattern.Branch(1, "rung 0", [When.Timer(0)],
                Do.SpawnNear(283215, 1, 1, 0f, 60),
                Do.SpawnNear(283215, 1, 1, 0f, 60),
                Do.SpawnNear(283216, 1, 1, 0f, 60),
                Do.ArmTimer(0, 15000)),
        ],
        [219560] = [  // IDAbRe_Core_FlyingWorm_02
            AiPattern.Branch(1, "rung 0", [When.Timer(0)],
                Do.SpawnNear(283215, 1, 1, 0f, 60),
                Do.SpawnNear(283215, 1, 1, 0f, 60),
                Do.SpawnNear(283216, 1, 1, 0f, 60),
                Do.ArmTimer(0, 15000)),
        ],
        [280968] = [  // ND2_GKSum1
            AiPattern.Branch(7, "rung 0", [When.Timer(0)],
                Do.SpawnNear(280969, 1, 2, 0f, 60)),
        ],
        [282141] = [  // IDAbRe_Core_Summon4
            AiPattern.Branch(1, "rung 0", [When.Timer(0)],
                Do.SpawnAt(281903, 1, 70, new SpawnSpot(309.95f, 738.02f, 217.12f)),
                Do.ArmTimer(0, 12000)),
        ],
        [282142] = [  // IDAbRe_Core_Summon4_3
            AiPattern.Branch(1, "rung 0", [When.Timer(0)],
                Do.SpawnAt(281903, 1, 70, new SpawnSpot(331.33f, 722.18f, 212.93f)),
                Do.ArmTimer(0, 12000)),
        ],
        [282143] = [  // IDAbRe_Core_Summon4_6
            AiPattern.Branch(1, "rung 0", [When.Timer(0)],
                Do.SpawnAt(281903, 1, 70, new SpawnSpot(348.55f, 741.76f, 212.93f)),
                Do.ArmTimer(0, 12000)),
        ],
        [282144] = [  // IDAbRe_Core_Summon4_Low
            AiPattern.Branch(1, "rung 0", [When.Timer(0)],
                Do.SpawnNear(281904, 1, 1, 0f, 13),
                Do.ArmTimer(0, 9000)),
        ],
        [282183] = [  // IDHouse_Zadra_Blaze_Move
            AiPattern.Branch(1, "rung 0", [When.Timer(0)],
                Do.ArmTimer(0, 2000),
                Do.SpawnNear(282184, 1, 1, 0f, 38)),
        ],
        [282264] = [  // D3_NeP_S
            AiPattern.Branch(1, "rung 0", [When.Timer(0)],
                Do.SpawnNear(282184, 1, 1, 0f, 0),
                Do.ArmTimer(0, 1000)),
        ],
        [282307] = [  // IDForest_Prime_Sum1
            AiPattern.Branch(1, "rung 0", [When.Timer(0)],
                Do.SpawnNear(282465, 1, 1, 0f, 6),
                Do.SpawnNear(282308, 1, 1, 0f, 0),
                Do.DespawnSelf()),
        ],
        [283106] = [  // IDTiamat_Tahabata_Blaze
            AiPattern.Branch(1, "rung 0", [When.Timer(0)],
                Do.ArmTimer(0, 1000),
                Do.SpawnNear(283108, 1, 1, 0f, 3)),
        ],
        [283107] = [  // IDTiamat_Tahabata_Blaze
            AiPattern.Branch(1, "rung 0", [When.Timer(0)],
                Do.ArmTimer(0, 1000),
                Do.SpawnNear(283108, 1, 1, 0f, 3)),
        ],
        [283230] = [  // IDAbRe_Core_Summon4
            AiPattern.Branch(1, "rung 0", [When.Timer(0)],
                Do.SpawnAt(281903, 1, 70, new SpawnSpot(309.95f, 738.02f, 217.12f)),
                Do.ArmTimer(0, 12000)),
        ],
        [283231] = [  // IDAbRe_Core_Summon4_3
            AiPattern.Branch(1, "rung 0", [When.Timer(0)],
                Do.SpawnAt(281903, 1, 70, new SpawnSpot(331.33f, 722.18f, 212.93f)),
                Do.ArmTimer(0, 12000)),
        ],
        [283232] = [  // IDAbRe_Core_Summon4_6
            AiPattern.Branch(1, "rung 0", [When.Timer(0)],
                Do.SpawnAt(281903, 1, 70, new SpawnSpot(348.55f, 741.76f, 212.93f)),
                Do.ArmTimer(0, 12000)),
        ],
    };

}
