// <auto-generated>
//     Generated by tools/client-extract/emit_death_spawns_table.py from out/death_spawns.tsv.
//     Do not edit by hand; edit the extractor and re-run.
// </auto-generated>
using Aion.GameServer.Ai.Pattern;
using Aion.GameServer.Controllers.Attack;
using Aion.GameServer.Model.Templates.Npcskill;

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// What a retail npc leaves behind when it dies: 109 patterns across 265 npcs, 960 actions.
/// </summary>
/// <remarks>
/// The encounters no rotation table can reach. <see cref="BattleCycles"/> reads <c>on_die</c> too, but
/// it is keyed on a battle-timer chain, and <b>179 of the encounters still missing an add have no
/// rotation at all</b> -- there is nothing there to hang a death handler off. A death spawn is not part
/// of a rotation; it needs a table keyed on dying, which is this one.
/// <para>
/// Retail splits <c>on_die</c> from <c>on_killed_by_user</c>: the first fires however the npc died, the
/// second only when a player did it. This port has one slot and <see cref="When.KilledByPlayer"/>,
/// which is exactly that distinction, so the second is emitted as the first plus that guard.
/// </para>
/// <para>
/// <see cref="DeathSpawnAI"/>'s own nine hand-read npcs are excluded from generation and keep their
/// entries: they carry curated notes, and one of them encodes a judgement about a betrayer npc that is
/// worth not regenerating over.
/// </para>
/// </remarks>
internal static class DeathSpawns
{
    /// <summary>What this npc leaves behind, or empty for one that leaves nothing.</summary>
    internal static PatternBranch[] RungsFor(int npcId)
        => Rungs.TryGetValue(npcId, out PatternBranch[]? rungs) ? rungs : [];

    /// <summary>Every npc this table drives.</summary>
    internal static IEnumerable<int> Npcs => Rungs.Keys;

    private static readonly IReadOnlyDictionary<int, PatternBranch[]> Rungs =
        BuildRungs();

    private static Dictionary<int, PatternBranch[]> BuildRungs()
    {
        Dictionary<int, PatternBranch[]> rungs = new Dictionary<int, PatternBranch[]>();
        Rungs0(rungs);
        Rungs1(rungs);
        Rungs2(rungs);
        return rungs;
    }

    private static void Rungs0(Dictionary<int, PatternBranch[]> rungs)
    {
        rungs[213778] = [  // IDDF3_NamedNWi
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnAtForTheFight(282155, 2, 10, new SpawnSpot(488.0f, 412.0f, 615.0f)),
                Do.SetSpawnVariable("lastboss", 0, 1)),
            AiPattern.Branch(8, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Despawn(1)),
        ];
        rungs[213779] = [  // IDDF3_NamedNKn
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnAtForTheFight(282155, 2, 10, new SpawnSpot(488.0f, 412.0f, 615.0f)),
                Do.SetSpawnVariable("lastboss", 0, 1)),
        ];
        rungs[213802] = [  // IDDF3_NamedNCh
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnAtForTheFight(282155, 2, 10, new SpawnSpot(488.0f, 412.0f, 615.0f)),
                Do.SetSpawnVariable("lastboss", 0, 1)),
        ];
        rungs[213905] = [  // LF2A_TBox
            AiPattern.Branch(1, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(341026, 0),
                Do.SpawnNearForTheFight(280722, 1, 1, 0f, 600)),
        ];
        rungs[214024] = [  // LF2A_TBox
            AiPattern.Branch(1, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(341026, 0),
                Do.SpawnNearForTheFight(280722, 1, 1, 0f, 600)),
        ];
        rungs[214532] = [  // Event_Santa_L
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer, When.Chance(25)],
                Do.SpawnNearForTheFight(280820, 0, 1, 0f, 18)),
        ];
        rungs[214533] = [  // Event_Santa_D
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer, When.Chance(25)],
                Do.SpawnNearForTheFight(280821, 0, 1, 0f, 18)),
        ];
        rungs[215079] = [  // IDSlk_KK
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(281197, 1, 1, 0f, 6),
                Do.SetSpawnVariable("Lever", 2, 0)),
        ];
        rungs[217119] = [  // Cromede_Named_ScaredQ
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.Despawn(1),
                Do.SpawnAtForTheFight(282115, 0, 60, new SpawnSpot(749.8f, 628.18f, 198.37f)),
                Do.SpawnAtForTheFight(282115, 0, 60, new SpawnSpot(512.55f, 574.35f, 217.6f)),
                Do.SpawnAtForTheFight(282115, 0, 60, new SpawnSpot(568.19f, 833.13f, 226.33f))),
        ];
        rungs[217234] = [  // IDForest_Prime_Boss
            AiPattern.Branch(16, "on_die 0", When.Always,
                Do.SetSpawnVariable("FARMER_DESPAWN", 1, 0),
                Do.SpawnNearForTheFight(282983, 1, 1, 0f, 10),
                Do.Say(1500457, 0)),
        ];
        rungs[217235] = [  // IDForest_Rollingstone_Boss
            AiPattern.Branch(12, "on_die 0", When.Always,
                Do.Say(1500444, 0),
                Do.SetSpawnVariable("STONE_DESPAWN", 0, 1),
                Do.SpawnNearForTheFight(205495, 1, 1, 0f, 0),
                Do.SpawnAtForTheFight(701009, 1, 0, new SpawnSpot(451.706f, 534.313f, 131.979f))),
        ];
        rungs[217236] = [  // IDForest_Rollingstone_Boss
            AiPattern.Branch(12, "on_die 0", When.Always,
                Do.Say(1500444, 0),
                Do.SetSpawnVariable("STONE_DESPAWN", 0, 1),
                Do.SpawnNearForTheFight(205495, 1, 1, 0f, 0),
                Do.SpawnAtForTheFight(701009, 1, 0, new SpawnSpot(451.706f, 534.313f, 131.979f))),
        ];
        rungs[217245] = [  // IDForest_Prime_Boss
            AiPattern.Branch(16, "on_die 0", When.Always,
                Do.SetSpawnVariable("FARMER_DESPAWN", 1, 0),
                Do.SpawnNearForTheFight(282983, 1, 1, 0f, 10),
                Do.Say(1500457, 0)),
        ];
        rungs[217246] = [  // IDForest_Rollingstone_Boss
            AiPattern.Branch(12, "on_die 0", When.Always,
                Do.Say(1500444, 0),
                Do.SetSpawnVariable("STONE_DESPAWN", 0, 1),
                Do.SpawnNearForTheFight(205495, 1, 1, 0f, 0),
                Do.SpawnAtForTheFight(701009, 1, 0, new SpawnSpot(451.706f, 534.313f, 131.979f))),
        ];
        rungs[217247] = [  // IDForest_Rollingstone_Boss
            AiPattern.Branch(12, "on_die 0", When.Always,
                Do.Say(1500444, 0),
                Do.SetSpawnVariable("STONE_DESPAWN", 0, 1),
                Do.SpawnNearForTheFight(205495, 1, 1, 0f, 0),
                Do.SpawnAtForTheFight(701009, 1, 0, new SpawnSpot(451.706f, 534.313f, 131.979f))),
        ];
        rungs[217263] = [  // IDForest_Nr_Golem_Ranger
            AiPattern.Branch(3, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(282465, 1, 1, 0f, 10),
                Do.SpawnNearForTheFight(282441, 1, 1, 0f, 0)),
        ];
        rungs[217279] = [  // Event_Santa_L
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer, When.Chance(25)],
                Do.SpawnNearForTheFight(280820, 0, 1, 0f, 18)),
        ];
        rungs[217280] = [  // Event_Santa_D
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer, When.Chance(25)],
                Do.SpawnNearForTheFight(280821, 0, 1, 0f, 18)),
        ];
        rungs[217301] = [  // IDYun_Temp_22
            AiPattern.Branch(1, "on_die 0", [When.Chance(35)],
                Do.SpawnNearForTheFight(282384, 1, 3, 0f, 30),
                Do.SpawnNearForTheFight(282382, 1, 1, 0f, 30)),
        ];
        rungs[217314] = [  // IDYun_hiddennm
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(701009, 0, 1, 0f, 0)),
        ];
        rungs[217327] = [  // IDYun_Temp_19
            AiPattern.Branch(1, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(282551, 1, 1, 0f, 10)),
        ];
        rungs[217371] = [  // Station_HugenNM
            AiPattern.Branch(15, "on_die 0", When.Always,
                Do.Say(1500583, 0),
                Do.SpawnNearForTheFight(730374, 0, 1, 0f, 0),
                Do.SpawnNearForTheFight(730412, 0, 1, 0f, 12)),
        ];
        rungs[217553] = [  // IDArena_S4_Named_R3
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SetSpawnVariable("Condition_S5_D", 0, 1),
                Do.SpawnNearForTheFight(281197, 1, 1, 0f, 6)),
        ];
        rungs[217555] = [  // IDArena_S4_Named_R5
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SetSpawnVariable("Condition_S5_D", 0, 1),
                Do.SpawnAtForTheFight(281335, 2, 6, new SpawnSpot(0.0f, 0.0f, 0.0f))),
        ];
        rungs[217568] = [  // IDArena_S6_Monster_1
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SetSpawnVariable("Condition_S6", 0, 1),
                Do.SpawnNearForTheFight(205413, 1, 1, 0f, 0)),
        ];
        rungs[217569] = [  // IDArena_S6_Monster_2
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SetSpawnVariable("Condition_S6", 0, 1),
                Do.SpawnNearForTheFight(205414, 1, 1, 0f, 0)),
        ];
        rungs[217570] = [  // IDArena_S6_Monster_3
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SetSpawnVariable("Condition_S6", 0, 1),
                Do.SpawnNearForTheFight(217571, 1, 5, 0f, 30)),
        ];
        rungs[217592] = [  // IDArena_S8_Named_5
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SetSpawnVariable("Condition_S8", 0, 1)),
            AiPattern.Branch(14, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(341127, 0),
                Do.SpawnNearForTheFight(280790, 1, 1, 0f, 120)),
        ];
        rungs[218616] = [  // IDCTH_Rudra
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnAtForTheFight(730287, 5, 0, new SpawnSpot(564.0f, 1335.0f, 224.0f)),
                Do.Say(1500092, 0),
                Do.SpawnNearForTheFight(702658, 0, 1, 0f, 0),
                Do.Despawn(1)),
        ];
        rungs[218618] = [  // IDAbRe_Core_NamedA1
            AiPattern.Branch(9, "on_die 0", When.Always,
                Do.SpawnAtForTheFight(282011, 1, 60, new SpawnSpot(448.99f, 694.32f, 433.06f))),
        ];
        rungs[218782] = [  // LDF4a_SandWarm_Monarch
            AiPattern.Branch(90, "on_die 0", When.Always,
                Do.Despawn(1),
                Do.Say(1500274, 0),
                Do.SpawnAtForTheFight(730497, 0, 0, new SpawnSpot(474.0f, 489.0f, 105.0f))),
        ];
        rungs[218916] = [  // LDF4b_DragonTurret
            AiPattern.Branch(1, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(218921, 1, 1, 0f, 6)),
        ];
        rungs[218917] = [  // LDF4b_DragonTurret
            AiPattern.Branch(1, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(218921, 1, 1, 0f, 6)),
        ];
        rungs[218918] = [  // LDF4b_DragonTurret
            AiPattern.Branch(1, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(218921, 1, 1, 0f, 6)),
        ];
        rungs[218919] = [  // LDF4b_DragonTurret
            AiPattern.Branch(1, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(218921, 1, 1, 0f, 6)),
        ];
        rungs[218927] = [  // LDF4b_Cavalry_Pagati_Fighter_58
            AiPattern.Branch(9, "on_die 0", When.Always,
                Do.SpawnNear(282798, 0, 1, 0f, 10)),
        ];
        rungs[218930] = [  // LDF4b_Cavalry_Pagati_Fighter_58
            AiPattern.Branch(9, "on_die 0", When.Always,
                Do.SpawnNear(282798, 0, 1, 0f, 10)),
        ];
        rungs[219165] = [  // LDF4a_WindPath_Control_Monster
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(207087, 0, 1, 0f, 0),
                Do.Broadcast(7299, 200f)),
        ];
        rungs[219200] = [  // TDown_DrakanWi_Noble_60_Ae_Link
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(282975, 1, 1, 0f, 10),
                Do.Despawn(1)),
        ];
        rungs[219380] = [  // IDTiamat_S2_StealthUnit_60_Ae
            AiPattern.Branch(3, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(283046, 1, 1, 0f, 5),
                Do.Despawn(1)),
        ];
        rungs[219569] = [  // IDAbRe_Core_Summon6
            AiPattern.Branch(8, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(281925, 1, 1, 0f, 10)),
        ];
        rungs[219621] = [  // GM_Event_LDF4b_Golden_Gururu
            AiPattern.Branch(21, "on_die 0", When.Always,
                Do.Despawn(1),
                Do.Say(1500503, 0),
                Do.SpawnNearForTheFight(701652, 3, 24, 0f, 600)),
        ];
        rungs[230422] = [  // IDF5_Under_01_Boss
            AiPattern.Branch(97, "on_die 0", [When.FirstTimeInWorld(5)],
                Do.SpawnAtForTheFight(702659, 0, 0, new SpawnSpot(335.3f, 489.5f, 607.5f)),
                Do.SetSpawnVariable("IDLDF5_Under_01_Entrance_Out", 1, 0),
                Do.SetSpawnVariable("cBox", 2, 0),
                Do.SetSpawnVariable("cWeapon", 3, 0)),
        ];
        rungs[230854] = [  // IDVritra_Base_Boss5
            AiPattern.Branch(32, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Despawn(1),
                Do.SpawnAtForTheFight(801967, 0, 0, new SpawnSpot(125.0f, 889.0f, 414.0f)),
                Do.Broadcast(22258, 50f)),
        ];
        rungs[230855] = [  // IDVritra_Base_Boss4
            AiPattern.Branch(16, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SetSpawnVariable("BOSS2_SUM_01", 0, -1),
                Do.SetSpawnVariable("BOSS2_SUM_02", 0, -1),
                Do.SetSpawnVariable("BOSS2_SUM_03", 0, -1),
                Do.SpawnAtForTheFight(801967, 0, 0, new SpawnSpot(321.0f, 886.0f, 414.0f)),
                Do.Broadcast(22258, 50f)),
        ];
        rungs[230856] = [  // IDVritra_Base_Boss3
            AiPattern.Branch(32, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnAtForTheFight(801967, 0, 0, new SpawnSpot(519.0f, 889.0f, 414.0f)),
                Do.Broadcast(22258, 50f)),
        ];
        rungs[236283] = [  // IDYun_Drakan_ND3
            AiPattern.Branch(4, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(282528, 1, 1, 0f, 10)),
        ];
        rungs[236290] = [  // IDYun_info_07
            AiPattern.Branch(4, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(856481, 1, 1, 0f, 10)),
        ];
        rungs[251045] = [  // FD2_FrA_S
            AiPattern.Branch(17, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(290116, 1, 1, 0f, 20)),
        ];
        rungs[260224] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[260225] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[260226] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[263255] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[263256] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[263257] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[263557] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[263558] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[263559] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[264757] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[264758] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[264759] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[266542] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[266543] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[266544] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[268040] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[268041] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[268042] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[269240] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[269241] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[269242] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[270140] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[270141] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[270142] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[271042] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[271043] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[271044] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[277400] = [  // BGuard_Chief_Gab1_L
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277401] = [  // BGuard_Chief_Gab1_L
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277402] = [  // BGuard_Chief_Gab1_L
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277403] = [  // BGuard_Chief_Gab1_L
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277404] = [  // BGuard_Chief_Gab1_L
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277405] = [  // BGuard_Chief_Gab1_D
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277406] = [  // BGuard_Chief_Gab1_D
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277407] = [  // BGuard_Chief_Gab1_D
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277408] = [  // BGuard_Chief_Gab1_D
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277409] = [  // BGuard_Chief_Gab1_D
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277410] = [  // BGuard_Chief_Gab1_Dr
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277411] = [  // BGuard_Chief_Gab1_Dr
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277412] = [  // BGuard_Chief_Gab1_Dr
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277413] = [  // BGuard_Chief_Gab1_Dr
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277414] = [  // BGuard_Chief_Gab1_Dr
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277415] = [  // BGuard_Chief_Gab1_L
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277416] = [  // BGuard_Chief_Gab1_L
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277417] = [  // BGuard_Chief_Gab1_L
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277418] = [  // BGuard_Chief_Gab1_L
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277419] = [  // BGuard_Chief_Gab1_L
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277420] = [  // BGuard_Chief_Gab1_D
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277421] = [  // BGuard_Chief_Gab1_D
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277422] = [  // BGuard_Chief_Gab1_D
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277423] = [  // BGuard_Chief_Gab1_D
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
    }

    private static void Rungs1(Dictionary<int, PatternBranch[]> rungs)
    {
        rungs[277424] = [  // BGuard_Chief_Gab1_D
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277425] = [  // BGuard_Chief_Gab1_Dr
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277426] = [  // BGuard_Chief_Gab1_Dr
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277427] = [  // BGuard_Chief_Gab1_Dr
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277428] = [  // BGuard_Chief_Gab1_Dr
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277429] = [  // BGuard_Chief_Gab1_Dr
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277430] = [  // BGuard_Chief_Gab1_L
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277431] = [  // BGuard_Chief_Gab1_L
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277432] = [  // BGuard_Chief_Gab1_L
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277433] = [  // BGuard_Chief_Gab1_L
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277434] = [  // BGuard_Chief_Gab1_L
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277435] = [  // BGuard_Chief_Gab1_D
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277436] = [  // BGuard_Chief_Gab1_D
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277437] = [  // BGuard_Chief_Gab1_D
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277438] = [  // BGuard_Chief_Gab1_D
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277439] = [  // BGuard_Chief_Gab1_D
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277440] = [  // BGuard_Chief_Gab1_Dr
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277441] = [  // BGuard_Chief_Gab1_Dr
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277442] = [  // BGuard_Chief_Gab1_Dr
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277443] = [  // BGuard_Chief_Gab1_Dr
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277444] = [  // BGuard_Chief_Gab1_Dr
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277445] = [  // BGuard_Chief_Gab1_L
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277446] = [  // BGuard_Chief_Gab1_L
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277447] = [  // BGuard_Chief_Gab1_L
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277448] = [  // BGuard_Chief_Gab1_L
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277449] = [  // BGuard_Chief_Gab1_L
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277450] = [  // BGuard_Chief_Gab1_D
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277451] = [  // BGuard_Chief_Gab1_D
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277452] = [  // BGuard_Chief_Gab1_D
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277453] = [  // BGuard_Chief_Gab1_D
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277454] = [  // BGuard_Chief_Gab1_D
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277455] = [  // BGuard_Chief_Gab1_Dr
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277456] = [  // BGuard_Chief_Gab1_Dr
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277457] = [  // BGuard_Chief_Gab1_Dr
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277458] = [  // BGuard_Chief_Gab1_Dr
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277459] = [  // BGuard_Chief_Gab1_Dr
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(295092, 1, 1, 0f, 12),
                Do.SetSpawnVariable("v05", 22, 0),
                Do.SetSpawnVariable("v06", 22, 0),
                Do.SetSpawnVariable("v07", 22, 0),
                Do.SetSpawnVariable("v08", 22, 0),
                Do.SetSpawnVariable("v09", 22, 0),
                Do.SetSpawnVariable("v10", 22, 0),
                Do.SetSpawnVariable("v11", 22, 0),
                Do.SetSpawnVariable("v12", 22, 0)),
        ];
        rungs[277548] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277549] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277550] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277551] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277552] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277553] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277554] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277555] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277556] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277557] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277558] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277559] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277560] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277561] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277562] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277563] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277564] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277565] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277566] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277567] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277572] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277573] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277574] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277575] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277904] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277905] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277906] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277907] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277908] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277909] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277910] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277911] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277912] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277913] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277914] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277915] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277916] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277917] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277918] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[277919] = [  // NoAction_AbyssDoor
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296337, 0, 1, 0f, 12)),
        ];
        rungs[280358] = [  // ND2_CheatboxSu
            AiPattern.Branch(6, "on_killed_by_user 0", [When.KilledByPlayer, When.Chance(1), When.FirstTime(0)],
                Do.SpawnNearForTheFight(211800, 1, 1, 0f, 9600),
                Do.DespawnSelf()),
            AiPattern.Branch(5, "on_killed_by_user 1", [When.KilledByPlayer, When.Chance(20), When.FirstTime(0)],
                Do.SpawnNearForTheFight(211799, 1, 6, 0f, 9600),
                Do.DespawnSelf()),
            AiPattern.Branch(4, "on_killed_by_user 2", [When.KilledByPlayer, When.Chance(20), When.FirstTime(0)],
                Do.SpawnNearForTheFight(211797, 3, 1, 0f, 9600),
                Do.SpawnNearForTheFight(211796, 3, 1, 0f, 9600),
                Do.SpawnNearForTheFight(211795, 3, 1, 0f, 9600),
                Do.DespawnSelf()),
            AiPattern.Branch(3, "on_killed_by_user 3", [When.KilledByPlayer, When.Chance(20), When.FirstTime(0)],
                Do.SpawnNearForTheFight(211794, 2, 1, 0f, 9600),
                Do.SpawnNearForTheFight(211793, 2, 1, 0f, 9600),
                Do.DespawnSelf()),
            AiPattern.Branch(2, "on_killed_by_user 4", [When.KilledByPlayer, When.Chance(9), When.FirstTime(0)],
                Do.SpawnNearForTheFight(211798, 1, 1, 0f, 9600),
                Do.DespawnSelf()),
            AiPattern.Branch(1, "on_killed_by_user 5", [When.KilledByPlayer, When.FirstTime(0)],
                Do.SpawnNearForTheFight(211792, 1, 1, 0f, 9600),
                Do.DespawnSelf()),
        ];
        rungs[280695] = [  // BLehpar_FhA
            AiPattern.Branch(14, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(341127, 0),
                Do.SpawnNearForTheFight(280714, 1, 1, 0f, 120)),
        ];
        rungs[280720] = [  // LF2A_TBox
            AiPattern.Branch(1, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(341026, 0),
                Do.SpawnNearForTheFight(280722, 1, 1, 0f, 600)),
        ];
        rungs[280789] = [  // NLehpar_BhA
            AiPattern.Branch(14, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(341127, 0),
                Do.SpawnNearForTheFight(280790, 1, 1, 0f, 120)),
        ];
        rungs[280970] = [  // ND2_WhG
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(341563, 0),
                Do.SpawnAtForTheFight(281032, 1, 0, new SpawnSpot(392.28f, 754.11f, 190.0f))),
        ];
        rungs[281117] = [  // Bionic_EhA
            AiPattern.Branch(21, "on_die 0", When.Always,
                Do.Despawn(1),
                Do.Despawn(2),
                Do.SpawnAtForTheFight(281230, 3, 0, new SpawnSpot(227.0f, 420.0f, 107.0f))),
            AiPattern.Branch(20, "on_killed_by_user 0", [When.KilledByPlayer, When.HpBelow(0)],
                Do.Despawn(1),
                Do.Despawn(2),
                Do.SpawnAtForTheFight(281230, 3, 0, new SpawnSpot(227.0f, 420.0f, 107.0f))),
        ];
        rungs[281124] = [  // IDSlk_KK
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(281197, 1, 1, 0f, 6),
                Do.SetSpawnVariable("Lever", 2, 0)),
        ];
        rungs[281128] = [  // IDSlk_KKFoodA
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(281196, 1, 1, 0f, 6)),
        ];
        rungs[281129] = [  // IDSlk_KKFoodB
            AiPattern.Branch(7, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(281196, 1, 1, 0f, 6)),
        ];
        rungs[281211] = [  // IDSlk_Gunner
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnAtForTheFight(281335, 2, 6, new SpawnSpot(0.0f, 0.0f, 0.0f))),
        ];
        rungs[281257] = [  // Dragon_G1
            AiPattern.Branch(23, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Despawn(1),
                Do.Despawn(2),
                Do.Despawn(3),
                Do.SpawnNear(281265, 4, 1, 0f, 0),
                Do.SpawnNearForTheFight(702658, 0, 1, 0f, 0)),
        ];
        rungs[281266] = [  // Dragon_G2
            AiPattern.Branch(23, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Despawn(1),
                Do.Despawn(2),
                Do.Despawn(3),
                Do.SpawnNearForTheFight(702658, 0, 1, 0f, 0)),
        ];
        rungs[281450] = [  // LF4_Dramata
            AiPattern.Branch(7, "on_die 0", [When.Chance(33)],
                Do.Despawn(1),
                Do.Despawn(2),
                Do.Despawn(3),
                Do.SpawnAtForTheFight(281928, 0, 12, new SpawnSpot(0.0f, 0.0f, 0.0f)),
                Do.SystemMessage(1500110, 0)),
            AiPattern.Branch(6, "on_die 1", [When.Chance(66)],
                Do.Despawn(1),
                Do.Despawn(2),
                Do.Despawn(3),
                Do.SpawnAtForTheFight(281928, 0, 12, new SpawnSpot(0.0f, 0.0f, 0.0f)),
                Do.SystemMessage(1500111, 0)),
            AiPattern.Branch(5, "on_die 2", When.Always,
                Do.Despawn(1),
                Do.Despawn(2),
                Do.Despawn(3),
                Do.SpawnAtForTheFight(281928, 0, 12, new SpawnSpot(0.0f, 0.0f, 0.0f)),
                Do.SystemMessage(1500112, 0)),
        ];
        rungs[281768] = [  // IDCT_Rudra
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnAtForTheFight(730287, 5, 0, new SpawnSpot(564.0f, 1335.0f, 224.0f)),
                Do.SpawnNearForTheFight(702658, 0, 1, 0f, 0),
                Do.Say(1500092, 0),
                Do.Despawn(1)),
        ];
        rungs[281772] = [  // IDCTH_Rudra
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnAtForTheFight(730287, 5, 0, new SpawnSpot(564.0f, 1335.0f, 224.0f)),
                Do.Say(1500092, 0),
                Do.SpawnNearForTheFight(702658, 0, 1, 0f, 0),
                Do.Despawn(1)),
        ];
        rungs[281897] = [  // IDAbRe_Core_NamedA1
            AiPattern.Branch(9, "on_die 0", When.Always,
                Do.SpawnAtForTheFight(282011, 1, 60, new SpawnSpot(448.99f, 694.32f, 433.06f))),
        ];
        rungs[281898] = [  // IDAbRe_Core_NamedA2
            AiPattern.Branch(9, "on_die 0", When.Always,
                Do.SpawnAtForTheFight(282012, 1, 60, new SpawnSpot(448.99f, 694.32f, 433.06f))),
        ];
        rungs[281899] = [  // IDAbRe_Core_NamedB
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SetSpawnVariable("NmdB_BoxSpawn", 0, 1),
                Do.SpawnAtForTheFight(281926, 1, 10, new SpawnSpot(634.7f, 557.1f, 424.0f))),
        ];
        rungs[281941] = [  // DF4_DramataG4
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnAtForTheFight(281942, 1, 12, new SpawnSpot(0.0f, 0.0f, 0.0f))),
        ];
        rungs[281974] = [  // Cromede_Torture
            AiPattern.Branch(100, "on_die 0", When.Always,
                Do.Say(1500153, 0),
                Do.SpawnAtForTheFight(282112, 0, 0, new SpawnSpot(662.28f, 774.47f, 216.85f))),
        ];
        rungs[281994] = [  // Cromede_Assijudge
            AiPattern.Branch(20, "on_die 0", When.Always,
                Do.Say(342248, 0),
                Do.SpawnAtForTheFight(282114, 0, 60, new SpawnSpot(662.28f, 774.43f, 216.85f))),
        ];
        rungs[281997] = [  // Cromede_Named_Scared
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.Despawn(1),
                Do.SpawnAtForTheFight(282115, 0, 60, new SpawnSpot(749.8f, 628.18f, 198.37f)),
                Do.SpawnAtForTheFight(282115, 0, 60, new SpawnSpot(512.55f, 574.35f, 217.6f)),
                Do.SpawnAtForTheFight(282115, 0, 60, new SpawnSpot(568.19f, 833.13f, 226.33f))),
        ];
        rungs[281998] = [  // Cromede_Named_Angry
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnAtForTheFight(282115, 0, 60, new SpawnSpot(749.8f, 628.18f, 198.37f)),
                Do.SpawnAtForTheFight(282115, 0, 60, new SpawnSpot(512.55f, 574.35f, 217.6f)),
                Do.SpawnAtForTheFight(282115, 0, 60, new SpawnSpot(568.19f, 833.13f, 226.33f)),
                Do.Despawn(1),
                Do.Despawn(2),
                Do.Despawn(3)),
        ];
        rungs[282054] = [  // IDAbRe_Core_Egg2
            AiPattern.Branch(10, "on_die 0", [When.FirstTime(0)],
                Do.SpawnNearForTheFight(281388, 1, 1, 0f, 5)),
        ];
    }

    private static void Rungs2(Dictionary<int, PatternBranch[]> rungs)
    {
        rungs[282055] = [  // IDAbRe_Core_Egg3
            AiPattern.Branch(10, "on_die 0", [When.FirstTime(0)],
                Do.SpawnNearForTheFight(281388, 1, 1, 0f, 5)),
        ];
        rungs[282056] = [  // IDAbRe_Core_Egg4
            AiPattern.Branch(10, "on_die 0", [When.FirstTime(0)],
                Do.SpawnNearForTheFight(281388, 1, 1, 0f, 5)),
        ];
        rungs[282165] = [  // IDForest_hidden
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(701009, 0, 1, 0f, 0)),
        ];
        rungs[282187] = [  // IDHouse_Zadra_Deform_Fire
            AiPattern.Branch(1, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(282188, 1, 1, 0f, 0)),
        ];
        rungs[282190] = [  // IDForest_Wave_Spaky_Normal
            AiPattern.Branch(2, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(282247, 1, 1, 0f, 2)),
        ];
        rungs[282194] = [  // IDForest_Wave_Laphilima_Normal
            AiPattern.Branch(2, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(282250, 1, 1, 0f, 2)),
        ];
        rungs[282198] = [  // IDForest_Wave_Wisp
            AiPattern.Branch(2, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(282199, 1, 1, 0f, 2)),
        ];
        rungs[282216] = [  // IDForest_hidden
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(701009, 0, 1, 0f, 0)),
        ];
        rungs[282261] = [  // IDElemental_Ex3
            AiPattern.Branch(7, "on_die 0", [When.Chance(50)],
                Do.SpawnAtForTheFight(217235, 0, 0, new SpawnSpot(377.13f, 446.91f, 157.0f)),
                Do.SpawnAtForTheFight(217236, 0, 0, new SpawnSpot(383.57f, 440.75f, 157.0f))),
            AiPattern.Branch(6, "on_die 1", When.Always,
                Do.SpawnAtForTheFight(217236, 0, 0, new SpawnSpot(377.13f, 445.91f, 157.0f)),
                Do.SpawnAtForTheFight(217235, 0, 0, new SpawnSpot(383.57f, 445.91f, 157.0f))),
        ];
        rungs[282262] = [  // IDElemental_Ex4
            AiPattern.Branch(7, "on_die 0", [When.Chance(50)],
                Do.SpawnAtForTheFight(217246, 0, 0, new SpawnSpot(377.13f, 446.91f, 157.0f)),
                Do.SpawnAtForTheFight(217247, 0, 0, new SpawnSpot(383.57f, 440.75f, 157.0f))),
            AiPattern.Branch(6, "on_die 1", When.Always,
                Do.SpawnAtForTheFight(217247, 0, 0, new SpawnSpot(377.13f, 445.91f, 157.0f)),
                Do.SpawnAtForTheFight(217246, 0, 0, new SpawnSpot(383.57f, 445.91f, 157.0f))),
        ];
        rungs[282265] = [  // IDHouse_Zadra_Phantom
            AiPattern.Branch(3, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(282252, 1, 1, 0f, 5)),
        ];
        rungs[282302] = [  // IDForest_ManduriT_Sum1
            AiPattern.Branch(5, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(282252, 1, 1, 0f, 2)),
        ];
        rungs[282303] = [  // IDForest_ManduriT_Sum2
            AiPattern.Branch(5, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(282252, 1, 1, 0f, 2)),
        ];
        rungs[282361] = [  // IDElemental_Ex6
            AiPattern.Branch(99, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(282252, 1, 1, 0f, 5)),
        ];
        rungs[282526] = [  // LDF4a_SandWarm_Monarch
            AiPattern.Branch(90, "on_die 0", When.Always,
                Do.Despawn(1),
                Do.Say(1500274, 0),
                Do.SpawnAtForTheFight(730497, 0, 0, new SpawnSpot(474.0f, 489.0f, 105.0f))),
        ];
        rungs[282623] = [  // LDF4a_Owllau_Chieftain_001
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(282622, 0, 1, 0f, 0)),
        ];
        rungs[282976] = [  // LDF4a_SandWarm_Monarch_Summon_1
            AiPattern.Branch(10, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(282539, 1, 1, 0f, 30)),
        ];
        rungs[283072] = [  // TiamatDown_TiamatAgent_SumBomb
            AiPattern.Branch(3, "on_die 0", When.Always,
                Do.SystemMessage(1401463, 0),
                Do.SpawnNearForTheFight(283073, 1, 1, 0f, 5)),
        ];
        rungs[283074] = [  // TiamatDown_TiamatAgent_SumBomb2
            AiPattern.Branch(3, "on_die 0", When.Always,
                Do.SystemMessage(1401463, 0),
                Do.SpawnNearForTheFight(283073, 1, 1, 0f, 5)),
        ];
        rungs[283076] = [  // TiamatDown_TiamatAgent_SumBomb3
            AiPattern.Branch(3, "on_die 0", When.Always,
                Do.SystemMessage(1401463, 0),
                Do.SpawnNearForTheFight(283073, 1, 1, 0f, 5)),
        ];
        rungs[283194] = [  // IDAbRe_Core_NamedA1
            AiPattern.Branch(9, "on_die 0", When.Always,
                Do.SpawnAtForTheFight(282011, 1, 60, new SpawnSpot(448.99f, 694.32f, 433.06f))),
        ];
        rungs[283195] = [  // IDAbRe_Core_NamedA2
            AiPattern.Branch(9, "on_die 0", When.Always,
                Do.SpawnAtForTheFight(282012, 1, 60, new SpawnSpot(448.99f, 694.32f, 433.06f))),
        ];
        rungs[283196] = [  // IDAbRe_Core_NamedB
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SetSpawnVariable("NmdB_BoxSpawn", 0, 1),
                Do.SpawnAtForTheFight(281926, 1, 10, new SpawnSpot(634.7f, 557.1f, 424.0f))),
        ];
        rungs[283199] = [  // IDAbRe_Core_Egg_02
            AiPattern.Branch(10, "on_die 0", [When.FirstTime(0)],
                Do.SpawnNearForTheFight(281388, 1, 1, 0f, 5)),
        ];
        rungs[283225] = [  // IDAbRe_Core_Egg3_02
            AiPattern.Branch(10, "on_die 0", [When.FirstTime(0)],
                Do.SpawnNearForTheFight(281388, 1, 1, 0f, 5)),
        ];
        rungs[283226] = [  // IDAbRe_Core_Egg4_02
            AiPattern.Branch(10, "on_die 0", [When.FirstTime(0)],
                Do.SpawnNearForTheFight(281388, 1, 1, 0f, 5)),
        ];
        rungs[284263] = [  // Coffin_N_65_Ae
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(284262, 1, 1, 0f, 0),
                Do.DespawnSelf()),
        ];
        rungs[284264] = [  // Coffin_N_65_Ae
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(284262, 1, 1, 0f, 0),
                Do.DespawnSelf()),
        ];
        rungs[284265] = [  // Coffin_N_65_Ae
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(284262, 1, 1, 0f, 0),
                Do.DespawnSelf()),
        ];
        rungs[284266] = [  // Coffin_N_65_Ae
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(284262, 1, 1, 0f, 0),
                Do.DespawnSelf()),
        ];
        rungs[284267] = [  // Coffin_N_65_Ae
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(284262, 1, 1, 0f, 0),
                Do.DespawnSelf()),
        ];
        rungs[284365] = [  // IDF5_Under_01_Boss
            AiPattern.Branch(97, "on_die 0", [When.FirstTimeInWorld(5)],
                Do.SpawnAtForTheFight(702659, 0, 0, new SpawnSpot(335.3f, 489.5f, 607.5f)),
                Do.SetSpawnVariable("IDLDF5_Under_01_Entrance_Out", 1, 0),
                Do.SetSpawnVariable("cBox", 2, 0),
                Do.SetSpawnVariable("cWeapon", 3, 0)),
        ];
        rungs[284430] = [  // IDVritra_Base_Boss1
            AiPattern.Branch(58, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(1500778, 0),
                Do.Broadcast(22258, 50f),
                Do.SpawnAtForTheFight(801967, 0, 0, new SpawnSpot(916.0f, 889.0f, 414.0f)),
                Do.SpawnNearForTheFight(702659, 0, 1, 0f, 0),
                Do.Despawn(1),
                Do.Despawn(2)),
        ];
        rungs[284431] = [  // IDVritra_Base_Boss2
            AiPattern.Branch(43, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Despawn(1),
                Do.SpawnAtForTheFight(801967, 0, 0, new SpawnSpot(719.0f, 889.0f, 414.0f)),
                Do.SpawnNearForTheFight(702659, 0, 1, 0f, 0),
                Do.Broadcast(22258, 50f)),
        ];
        rungs[284432] = [  // IDVritra_Base_Boss3
            AiPattern.Branch(32, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnAtForTheFight(801967, 0, 0, new SpawnSpot(519.0f, 889.0f, 414.0f)),
                Do.Broadcast(22258, 50f)),
        ];
        rungs[284433] = [  // IDVritra_Base_Boss4
            AiPattern.Branch(16, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SetSpawnVariable("BOSS2_SUM_01", 0, -1),
                Do.SetSpawnVariable("BOSS2_SUM_02", 0, -1),
                Do.SetSpawnVariable("BOSS2_SUM_03", 0, -1),
                Do.SpawnAtForTheFight(801967, 0, 0, new SpawnSpot(321.0f, 886.0f, 414.0f)),
                Do.Broadcast(22258, 50f)),
        ];
        rungs[284434] = [  // IDVritra_Base_Boss5
            AiPattern.Branch(32, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Despawn(1),
                Do.SpawnAtForTheFight(801967, 0, 0, new SpawnSpot(125.0f, 889.0f, 414.0f)),
                Do.Broadcast(22258, 50f)),
        ];
        rungs[284510] = [  // IDRuneWP_Main_Charger_65_e
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnAt(855001, 2, 40, new SpawnSpot(107.04f, 137.37f, 133.0f))),
        ];
        rungs[284858] = [  // BIDF5_U3_Boss
            AiPattern.Branch(52, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SetSpawnVariable("BOSS", 10, 0),
                Do.Broadcast(22542, 50f),
                Do.SpawnNearForTheFight(702659, 0, 1, 0f, 0),
                Do.Despawn(1),
                Do.Despawn(2),
                Do.Despawn(3)),
        ];
        rungs[284919] = [  // ND2_AhC_1
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.Say(341531, 0),
                Do.SpawnNear(214599, 0, 1, 0f, 0)),
        ];
        rungs[286787] = [  // Bionic_EhA
            AiPattern.Branch(21, "on_die 0", When.Always,
                Do.Despawn(1),
                Do.Despawn(2),
                Do.SpawnAtForTheFight(281230, 3, 0, new SpawnSpot(227.0f, 420.0f, 107.0f))),
            AiPattern.Branch(20, "on_killed_by_user 0", [When.KilledByPlayer, When.HpBelow(0)],
                Do.Despawn(1),
                Do.Despawn(2),
                Do.SpawnAtForTheFight(281230, 3, 0, new SpawnSpot(227.0f, 420.0f, 107.0f))),
        ];
        rungs[286918] = [  // IDHouse_first_sum_general_EX
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(211757, 0, 1, 0f, 0)),
        ];
        rungs[286934] = [  // Test_JM_Monster_9
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnAtForTheFight(286935, 1, 0, new SpawnSpot(234.49f, 229.65f, 161.0f)),
                Do.SetSpawnVariable("condition_4", 3, 0)),
        ];
        rungs[286935] = [  // Test_JM_Monster_10
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SetSpawnVariable("condition_5", 3, 0),
                Do.SpawnNearForTheFight(286926, 1, 1, 0f, 0)),
        ];
        rungs[287015] = [  // Test_Basic_Monster_AI_KDG_2
            AiPattern.Branch(25, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(218724, 1, 1, 0f, 0)),
        ];
        rungs[287090] = [  // Test_Basic_Monster_AI_KMD_2
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(287086, 1, 1, 0f, 0)),
        ];
        rungs[287217] = [  // Test_Monster_SNR_02
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(287218, 0, 1, 0f, 0)),
        ];
        rungs[287224] = [  // Test_Monster_KYJ_02
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(831574, 1, 1, 0f, 0)),
        ];
        rungs[290115] = [  // FD2_FrA
            AiPattern.Branch(17, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(290116, 1, 1, 0f, 20)),
        ];
        rungs[294551] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[294552] = [  // BGuard_BombMan
            AiPattern.Branch(3, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340926, 0),
                Do.SpawnNearForTheFight(294561, 0, 1, 0f, 360)),
        ];
        rungs[294555] = [  // LGuard_FhA_Officer
            AiPattern.Branch(10, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340925, 0),
                Do.SpawnNearForTheFight(294564, 0, 1, 0f, 360)),
        ];
        rungs[294556] = [  // DGuard_FhA_Officer
            AiPattern.Branch(10, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.Say(340925, 0),
                Do.SpawnNearForTheFight(294563, 0, 1, 0f, 360)),
        ];
        rungs[296437] = [  // DrGuard_FhB_F20
            AiPattern.Branch(100, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(296443, 1, 1, 0f, 48)),
        ];
        rungs[701137] = [  // LDF4b_FOBJ_LavaRock1
            AiPattern.Branch(1, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(282751, 1, 1, 0f, 10)),
        ];
        rungs[701138] = [  // LDF4b_FOBJ_LavaRock1
            AiPattern.Branch(1, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(282751, 1, 1, 0f, 10)),
        ];
        rungs[701139] = [  // LDF4b_FOBJ_LavaRock1
            AiPattern.Branch(1, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(282751, 1, 1, 0f, 10)),
        ];
        rungs[701712] = [  // LDF5b_6021_Explosion_Box_04
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnAtForTheFight(701777, 0, 0, new SpawnSpot(2718.0f, 2588.0f, 255.0f)),
                Do.Broadcast(31014, 50f)),
        ];
        rungs[701717] = [  // LDF5b_6021_Explosion_Box_09
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnAtForTheFight(701778, 0, 0, new SpawnSpot(2601.0f, 2798.0f, 255.0f)),
                Do.Broadcast(31019, 50f)),
        ];
        rungs[831572] = [  // IDDF2Flying_event01_B_RatmanWarriorM_55_Ae
            AiPattern.Branch(7, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(831581, 1, 1, 0f, 0),
                Do.Broadcast(1997, 100f)),
        ];
        rungs[855536] = [  // IDLDF5_Under_02_Summon03
            AiPattern.Branch(1000, "on_die 0", When.Always,
                Do.SetSpawnVariable("cSetPortal", 3, 0)),
            AiPattern.Branch(1050, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(702659, 0, 1, 0f, 0)),
        ];
        rungs[855537] = [  // IDLDF5_Under_02_Summon04
            AiPattern.Branch(1000, "on_die 0", When.Always,
                Do.SetSpawnVariable("cSetPortal", 3, 0)),
            AiPattern.Branch(1050, "on_killed_by_user 0", [When.KilledByPlayer],
                Do.SpawnNearForTheFight(702659, 0, 1, 0f, 0)),
        ];
        rungs[855865] = [  // IDForest_Wave_Laphilima_Normal
            AiPattern.Branch(2, "on_die 0", When.Always,
                Do.SpawnNearForTheFight(282250, 1, 1, 0f, 2)),
        ];
        rungs[856026] = [  // IDTiamat_Hard_Kalrindy
            AiPattern.Branch(16, "on_die 0", When.Always,
                Do.SpawnAtForTheFight(283187, 1, 10, new SpawnSpot(467.8f, 514.3f, 418.0f)),
                Do.SetSpawnVariable("IDTIAMAT_TELEPORT_T2", 0, 1),
                Do.SetSpawnVariable("TIAMATSHEILD_SPAWN", 0, 1),
                Do.Despawn(1),
                Do.Despawn(2),
                Do.Say(1500719, 0)),
        ];
        rungs[856029] = [  // IDTiamat_Hard_Tiamat_Dragon_Dying
            AiPattern.Branch(49, "on_die 0", When.Always,
                Do.SetSpawnVariable("TIAMAT_TREASUREBOX", 0, 1),
                Do.Broadcast(201, 100f),
                Do.SetSpawnVariable("KAHRUN_SPAWN", 4, 0),
                Do.SetSpawnVariable("RELIC_SPAWN", 2, 0),
                Do.Despawn(1),
                Do.SpawnAtForTheFight(283183, 1, 60, new SpawnSpot(478.0f, 514.0f, 418.0f)),
                Do.Say(1500734, 0),
                Do.SpawnAtForTheFight(702659, 0, 0, new SpawnSpot(480.0f, 508.0f, 419.0f))),
        ];
    }

}
