// <auto-generated>
//     Generated by tools/client-extract/emit_gate_table.py from the retail AI patterns.
//     Do not edit by hand: re-run the extractor instead. See docs/retail-ai-fidelity.md.
// </auto-generated>

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// The squad each fortress gate puts out, wave by wave.
/// </summary>
/// <remarks>
/// Read out of the retail <c>BGuard_*Gate*</c> patterns — 153 steps for 69 gates across
/// 62 pattern variants. A gate is attacked, waits, and puts out waves on a fixed chain; most
/// then remove themselves, and some cycle back to the first wave instead and keep going for as long
/// as the fight lasts.
/// </remarks>
internal static class GateSquads
{
    /// <summary>One wave.</summary>
    /// <param name="DelayMillis">How long after the previous wave — or after being attacked, for the first.</param>
    /// <param name="OnTarget">True when retail places the wave on whoever the gate is fighting.</param>
    /// <param name="Summons">npc id and count, in the order the pattern lists them.</param>
    internal readonly record struct Wave(int DelayMillis, bool OnTarget, (int NpcId, int Count)[] Summons);

    /// <summary>One gate's chain.</summary>
    /// <param name="Waves">In order.</param>
    /// <param name="DespawnAfterMillis">How long the gate stands after its last wave, or 0 if it loops.</param>
    /// <param name="LoopsTo">The wave the chain returns to, or -1 when the gate removes itself instead.</param>
    internal readonly record struct Squad(Wave[] Waves, int DespawnAfterMillis, int LoopsTo);

    internal static readonly IReadOnlyDictionary<int, Squad> ByGate = new Dictionary<int, Squad>
    {
        // BGuard_GateKimeiaA
        [207540] = new Squad([new Wave(20000, false, [(207545, 1)]), new Wave(40000, false, [(207545, 1), (207546, 1)]), new Wave(40000, false, [(207545, 2), (207546, 1)]), new Wave(40000, false, [(207545, 1), (207546, 2)])], 3000, -1),
        // BGuard_GateKimeiaB
        [207541] = new Squad([new Wave(20000, false, [(207547, 1)]), new Wave(40000, false, [(207545, 1), (207547, 1)]), new Wave(40000, false, [(207545, 1), (207546, 1), (207547, 1)]), new Wave(40000, false, [(207545, 1), (207547, 2)])], 3000, -1),
        // BGuard_GateKimeiaC
        [207542] = new Squad([new Wave(20000, false, [(207548, 1)]), new Wave(40000, false, [(207548, 1), (207545, 1)]), new Wave(40000, false, [(207548, 1), (207547, 1), (207545, 1)]), new Wave(40000, false, [(207548, 2), (207547, 1)])], 3000, -1),
        // BGuard_GateKimeiaA
        [207549] = new Squad([new Wave(20000, false, [(207545, 1)]), new Wave(40000, false, [(207545, 1), (207546, 1)]), new Wave(40000, false, [(207545, 2), (207546, 1)]), new Wave(40000, false, [(207545, 1), (207546, 2)])], 3000, -1),
        // BGuard_GateKimeiaB
        [207550] = new Squad([new Wave(20000, false, [(207547, 1)]), new Wave(40000, false, [(207545, 1), (207547, 1)]), new Wave(40000, false, [(207545, 1), (207546, 1), (207547, 1)]), new Wave(40000, false, [(207545, 1), (207547, 2)])], 3000, -1),
        // BGuard_GateKimeiaC
        [207551] = new Squad([new Wave(20000, false, [(207548, 1)]), new Wave(40000, false, [(207548, 1), (207545, 1)]), new Wave(40000, false, [(207548, 1), (207547, 1), (207545, 1)]), new Wave(40000, false, [(207548, 2), (207547, 1)])], 3000, -1),
        // BGuard_LGate_L43
        [207612] = new Squad([new Wave(10000, false, [(207613, 1), (207615, 1)]), new Wave(30000, false, [(207616, 1), (207614, 1), (207615, 1)])], 5000, -1),
        // BGuard_DGate_L43
        [207617] = new Squad([new Wave(10000, false, [(207618, 1), (207620, 1)]), new Wave(30000, false, [(207621, 1), (207619, 1), (207620, 1)])], 5000, -1),
        // BGuard_LGate_L53
        [207622] = new Squad([new Wave(10000, false, [(207623, 1), (207625, 1)]), new Wave(30000, false, [(207626, 1), (207624, 1), (207625, 1)])], 5000, -1),
        // BGuard_DGate_L53
        [207627] = new Squad([new Wave(10000, false, [(207628, 1), (207630, 1)]), new Wave(30000, false, [(207631, 1), (207629, 1), (207630, 1)])], 5000, -1),
        // BGuard_LGate_L56
        [207699] = new Squad([new Wave(10000, false, [(207700, 1), (207702, 1)]), new Wave(30000, false, [(207703, 1), (207701, 1), (207702, 1)])], 5000, -1),
        // BGuard_LGate_L58
        [207704] = new Squad([new Wave(10000, false, [(207705, 1), (207707, 1)]), new Wave(30000, false, [(207708, 1), (207706, 1), (207707, 1)])], 5000, -1),
        // BGuard_DGate_L56
        [207712] = new Squad([new Wave(10000, false, [(207713, 1), (207715, 1)]), new Wave(30000, false, [(207716, 1), (207714, 1), (207715, 1)])], 5000, -1),
        // BGuard_DGate_L58
        [207717] = new Squad([new Wave(10000, false, [(207718, 1), (207720, 1)]), new Wave(30000, false, [(207721, 1), (207719, 1), (207720, 1)])], 5000, -1),
        // BGuard_LGate_L45
        [207816] = new Squad([new Wave(10000, false, [(207817, 1), (207819, 1)]), new Wave(30000, false, [(207820, 1), (207818, 1), (207819, 1)])], 5000, -1),
        // BGuard_DGate_L45
        [207827] = new Squad([new Wave(10000, false, [(207828, 1), (207830, 1)]), new Wave(30000, false, [(207831, 1), (207829, 1), (207830, 1)])], 5000, -1),
        // BGuard_DrGateChiefD
        [281226] = new Squad([new Wave(5000, false, [(281227, 1), (281229, 1)]), new Wave(30000, false, [(281228, 1), (281229, 2)])], 5000, -1),
        // BGuard_LGate
        [294718] = new Squad([new Wave(10000, false, [(294722, 1), (294728, 1)]), new Wave(30000, false, [(294731, 1), (294725, 1), (294728, 1)])], 5000, -1),
        // BGuard_LGate
        [294719] = new Squad([new Wave(10000, false, [(294722, 1), (294728, 1)]), new Wave(30000, false, [(294731, 1), (294725, 1), (294728, 1)])], 5000, -1),
        // BGuard_LGate
        [294720] = new Squad([new Wave(10000, false, [(294722, 1), (294728, 1)]), new Wave(30000, false, [(294731, 1), (294725, 1), (294728, 1)])], 5000, -1),
        // BGuard_DGate
        [294751] = new Squad([new Wave(10000, false, [(294755, 1), (294761, 1)]), new Wave(30000, false, [(294764, 1), (294758, 1), (294761, 1)])], 5000, -1),
        // BGuard_DGate
        [294752] = new Squad([new Wave(10000, false, [(294755, 1), (294761, 1)]), new Wave(30000, false, [(294764, 1), (294758, 1), (294761, 1)])], 5000, -1),
        // BGuard_DGate
        [294753] = new Squad([new Wave(10000, false, [(294755, 1), (294761, 1)]), new Wave(30000, false, [(294764, 1), (294758, 1), (294761, 1)])], 5000, -1),
        // BGuard_LGateChiefA
        [294892] = new Squad([new Wave(5000, false, [(295107, 1), (295109, 1)]), new Wave(35000, false, [(295108, 1), (295110, 2)])], 5000, -1),
        // BGuard_DGateChiefA
        [294893] = new Squad([new Wave(5000, false, [(295112, 1), (295114, 1)]), new Wave(35000, false, [(295113, 1), (295115, 2)])], 5000, -1),
        // BGuard_DrGateChiefA
        [294894] = new Squad([new Wave(5000, false, [(295117, 1), (295119, 1)]), new Wave(35000, false, [(295118, 1), (295120, 2)])], 5000, -1),
        // BGuard_LGateChiefB
        [295122] = new Squad([new Wave(5000, false, [(294880, 2), (294882, 1)]), new Wave(25000, false, [(294881, 1), (294882, 2)])], 5000, -1),
        // BGuard_DGateChiefB
        [295123] = new Squad([new Wave(5000, false, [(294884, 2), (294886, 1)]), new Wave(25000, false, [(294885, 1), (294886, 2)])], 5000, -1),
        // BGuard_DrGateChiefB
        [295124] = new Squad([new Wave(5000, false, [(294888, 2), (294890, 1)]), new Wave(25000, false, [(294889, 1), (294890, 2)])], 5000, -1),
        // BGuard_LGateChiefC
        [295125] = new Squad([new Wave(5000, false, [(294880, 2), (294882, 1)]), new Wave(30000, false, [(294881, 1), (294882, 2)])], 5000, -1),
        // BGuard_DGateChiefC
        [295126] = new Squad([new Wave(5000, false, [(294884, 2), (294886, 1)]), new Wave(30000, false, [(294885, 1), (294886, 2)])], 5000, -1),
        // BGuard_DrGateChiefC
        [295127] = new Squad([new Wave(5000, false, [(294888, 2), (294890, 1)]), new Wave(30000, false, [(294889, 1), (294890, 2)])], 5000, -1),
        // BGuard_LGate_L50
        [295135] = new Squad([new Wave(10000, false, [(295136, 1), (295138, 1)]), new Wave(30000, false, [(295139, 1), (295137, 1), (295138, 1)])], 5000, -1),
        // BGuard_DGate_L50
        [295146] = new Squad([new Wave(10000, false, [(295147, 1), (295149, 1)]), new Wave(30000, false, [(295150, 1), (295148, 1), (295149, 1)])], 5000, -1),
        // BGuard_LGateChiefA_L50
        [295212] = new Squad([new Wave(5000, false, [(295187, 1), (295188, 1), (295186, 1)]), new Wave(35000, false, [(295185, 1), (295188, 2), (295186, 1)])], 5000, -1),
        // BGuard_DGateChiefA_L50
        [295213] = new Squad([new Wave(5000, false, [(295192, 1), (295193, 1), (295191, 1)]), new Wave(35000, false, [(295190, 1), (295193, 2), (295191, 1)])], 5000, -1),
        // BGuard_DrGateChiefA_L50
        [295214] = new Squad([new Wave(5000, false, [(295195, 1), (295197, 1)]), new Wave(35000, false, [(295196, 1), (295198, 2)])], 5000, -1),
        // BGuard_LGateChiefB_L50
        [295215] = new Squad([new Wave(5000, false, [(295185, 1), (295188, 1)]), new Wave(35000, false, [(295186, 1), (295188, 1), (295187, 1)])], 5000, -1),
        // BGuard_DGateChiefB_L50
        [295216] = new Squad([new Wave(5000, false, [(295190, 1), (295193, 1)]), new Wave(35000, false, [(295191, 1), (295193, 1), (295192, 1)])], 5000, -1),
        // BGuard_DrGateChiefB_L50
        [295217] = new Squad([new Wave(5000, false, [(295208, 2), (295210, 1)]), new Wave(25000, false, [(295209, 1), (295210, 2)])], 5000, -1),
        // BGuard_LGateChiefC_L50
        [295218] = new Squad([new Wave(5000, false, [(295200, 2), (295202, 1)]), new Wave(30000, false, [(295201, 1), (295202, 1)])], 5000, -1),
        // BGuard_DGateChiefC_L50
        [295219] = new Squad([new Wave(5000, false, [(295204, 2), (295206, 1)]), new Wave(30000, false, [(295205, 1), (295206, 2)])], 5000, -1),
        // BGuard_DrGateChiefC_L50
        [295220] = new Squad([new Wave(5000, false, [(295208, 2), (295210, 1)]), new Wave(30000, false, [(295209, 1), (295210, 2)])], 5000, -1),
        // BGuard_LGateChiefA_L50M
        [296052] = new Squad([new Wave(5000, false, [(296028, 1), (296026, 1), (296027, 1)]), new Wave(35000, false, [(296025, 1), (296026, 1), (296028, 1)])], 5000, -1),
        // BGuard_DGateChiefA_L50M
        [296053] = new Squad([new Wave(5000, false, [(296032, 1), (296031, 1), (296033, 1)]), new Wave(35000, false, [(296030, 1), (296031, 1), (296033, 1)])], 5000, -1),
        // BGuard_DrGateChiefA_L50M
        [296054] = new Squad([new Wave(5000, false, [(296038, 1), (296036, 1), (296037, 1)]), new Wave(35000, false, [(296035, 1), (296036, 1), (296038, 1)])], 5000, -1),
        // BGuard_LGateChiefB_L50M
        [296055] = new Squad([new Wave(5000, false, [(296040, 2), (296042, 1)]), new Wave(35000, false, [(296041, 1), (296042, 1), (296040, 1)])], 5000, -1),
        // BGuard_DGateChiefB_L50M
        [296056] = new Squad([new Wave(5000, false, [(296044, 2), (296046, 1)]), new Wave(35000, false, [(296045, 1), (296046, 1), (296044, 1)])], 5000, -1),
        // BGuard_DrGateChiefB_L50M
        [296057] = new Squad([new Wave(5000, false, [(296048, 2), (296050, 1)]), new Wave(35000, false, [(296049, 1), (296050, 1), (296048, 1)])], 5000, -1),
        // BGuard_LGateChiefC_L50M
        [296058] = new Squad([new Wave(5000, false, [(296040, 2), (296042, 1)]), new Wave(30000, false, [(296041, 1), (296042, 2)])], 5000, -1),
        // BGuard_DGateChiefC_L50M
        [296059] = new Squad([new Wave(5000, false, [(296044, 2), (296046, 1)]), new Wave(30000, false, [(296045, 1), (296046, 2)])], 5000, -1),
        // BGuard_DrGateChiefC_L50M
        [296060] = new Squad([new Wave(5000, false, [(296048, 2), (296050, 1)]), new Wave(30000, false, [(296049, 1), (296050, 2)])], 5000, -1),
        // BGuard_LGate_L50M
        [296065] = new Squad([new Wave(10000, false, [(296066, 1), (296068, 1)]), new Wave(30000, false, [(296069, 1), (296067, 1), (296068, 1)])], 5000, -1),
        // BGuard_DGate_L50M
        [296076] = new Squad([new Wave(10000, false, [(296077, 1), (296079, 1)]), new Wave(30000, false, [(296080, 1), (296078, 1), (296079, 1)])], 5000, -1),
        // BGuard_LGateChiefF4A
        [296526] = new Squad([new Wave(5000, false, [(296531, 1), (296528, 1)]), new Wave(40000, false, [(296530, 1), (296529, 1), (296532, 1)]), new Wave(40000, false, [(296529, 1), (296531, 1), (296532, 1)])], 0, 0),
        // BGuard_LGateChiefF4B
        [296527] = new Squad([new Wave(5000, false, [(296531, 1), (296528, 1)]), new Wave(30000, false, [(296530, 1), (296532, 1)]), new Wave(30000, false, [(296529, 1), (296528, 1)])], 0, 0),
        // BGuard_DGateChiefF4A
        [296533] = new Squad([new Wave(5000, false, [(296538, 1), (296535, 1)]), new Wave(40000, false, [(296537, 1), (296536, 1), (296539, 1)]), new Wave(40000, false, [(296536, 1), (296538, 1), (296539, 1)])], 0, 0),
        // BGuard_DGateChiefF4B
        [296534] = new Squad([new Wave(5000, false, [(296538, 1), (296535, 1)]), new Wave(30000, false, [(296537, 1), (296539, 1)]), new Wave(30000, false, [(296536, 1), (296535, 1)])], 0, 0),
        // BGuard_DrGateChiefF4A
        [296540] = new Squad([new Wave(5000, false, [(296545, 1), (296542, 1)]), new Wave(40000, false, [(296544, 1), (296543, 1), (296545, 1)]), new Wave(40000, false, [(296543, 1), (296545, 1), (296544, 1)])], 0, 0),
        // BGuard_DrGateChiefF4B
        [296541] = new Squad([new Wave(5000, false, [(296545, 1), (296542, 1)]), new Wave(30000, false, [(296543, 1), (296545, 1)]), new Wave(30000, false, [(296545, 1), (296544, 1)])], 0, 0),
        // BGuard_LGate_L57
        [296634] = new Squad([new Wave(10000, false, [(296635, 1), (296637, 1)]), new Wave(30000, false, [(296638, 1), (296636, 1), (296637, 1)])], 5000, -1),
        // BGuard_LGate_L60
        [296639] = new Squad([new Wave(10000, false, [(296640, 1), (296642, 1)]), new Wave(30000, false, [(296643, 1), (296641, 1), (296642, 1)])], 5000, -1),
        // BGuard_DGate_L57
        [296744] = new Squad([new Wave(10000, false, [(296745, 1), (296747, 1)]), new Wave(30000, false, [(296748, 1), (296746, 1), (296747, 1)])], 5000, -1),
        // BGuard_DGate_L60
        [296749] = new Squad([new Wave(10000, false, [(296750, 1), (296752, 1)]), new Wave(30000, false, [(296753, 1), (296751, 1), (296752, 1)])], 5000, -1),
        // BGuard_LGate_L55
        [296870] = new Squad([new Wave(10000, false, [(296871, 1), (296873, 1)]), new Wave(30000, false, [(296874, 1), (296872, 1), (296873, 1)])], 5000, -1),
        // BGuard_DGate_L55
        [296878] = new Squad([new Wave(10000, false, [(296879, 1), (296881, 1)]), new Wave(30000, false, [(296882, 1), (296880, 1), (296881, 1)])], 5000, -1),
        // BGuard_ChiefA_Renew_Gate_Li
        [297117] = new Squad([new Wave(5000, false, [(297111, 1), (297112, 1)])], 5000, -1),
        // BGuard_ChiefA_Renew_Gate_Da
        [297118] = new Squad([new Wave(5000, false, [(297113, 1), (297114, 1)])], 5000, -1),
        // BGuard_ChiefA_Renew_Gate_Dr
        [297119] = new Squad([new Wave(5000, false, [(297115, 1), (297116, 1)])], 5000, -1),
    };
}
