// <auto-generated>
//     Generated by tools/client-extract/emit_guard_answers_table.py from out/guard_answers.tsv.
//     Do not edit by hand; edit the extractor and re-run.
// </auto-generated>
using Aion.GameServer.Ai;
using Aion.GameServer.Ai.Pattern;
using Aion.GameServer.Model.GameObjects;

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// Who answers a guard's call for help, and with what weight: 641 answers across 641 spawnable
/// npcs.
/// </summary>
/// <remarks>
/// The answering half of the whole call family. Retail gives it exactly two rungs and no third:
/// <c>is_npc_state NPC_STATE_ATTACK</c> answers with <c>switch_target</c>, and the unguarded rung with
/// <c>add_hate_point</c> followed by <c>attack_most_hating</c>. 637 of the 641 answers carry
/// the common 1/100 pair; the 4 that do not are carried at their own values rather than flattened.
/// <para>
/// A table rather than a constant because <b>which</b> call an npc answers is per npc, not per class:
/// 102 artifact protectors answer <c>23100</c> while keeping a class that has no
/// <c>on_message</c> of its own, which is why <see cref="ProtectorCalls"/> folds these rungs in.
/// </para>
/// </remarks>
internal static class GuardAnswers
{
    /// <summary>One call an npc answers. <c>Busy</c> is -1 when retail gives it no fighting rung.</summary>
    internal readonly record struct Answer(int Call, int Idle, int Busy);

    /// <summary>Every answer, by npc id.</summary>
    internal static readonly IReadOnlyDictionary<int, Answer[]> ByNpc = new Dictionary<int, Answer[]>
    {
        [209415] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Defend_PM_Ke2
        [209416] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Charge_PM_Fe2
        [209417] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Watch_PR_Re2
        [209418] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Strike_MRArea_We2
        [209419] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Support_HBuff_Pe2
        [209420] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Defend_PM_Ke2
        [209421] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Charge_PM_Fe2
        [209422] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Watch_PR_Re2
        [209423] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Strike_MRArea_We2
        [209424] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Support_HBuff_Pe2
        [209425] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Defend_PM_Ke2
        [209426] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Charge_PM_Fe2
        [209427] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Watch_PR_Re2
        [209428] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Strike_MRArea_We2
        [209429] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Support_HBuff_Pe2
        [209430] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Defend_PM_Ke2
        [209431] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Charge_PM_Fe2
        [209432] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Watch_PR_Re2
        [209433] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Strike_MRArea_We2
        [209434] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Support_HBuff_Pe2
        [209435] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Defend_PM_Ke2
        [209436] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Charge_PM_Fe2
        [209437] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Watch_PR_Re2
        [209438] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Strike_MRArea_We2
        [209439] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Support_HBuff_Pe2
        [209440] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Defend_PM_Ke2
        [209441] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Charge_PM_Fe2
        [209442] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Watch_PR_Re2
        [209443] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Strike_MRArea_We2
        [209444] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Support_HBuff_Pe2
        [209445] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Defend_PM_Ke2
        [209446] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Charge_PM_Fe2
        [209447] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Watch_PR_Re2
        [209448] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Strike_MRArea_We2
        [209449] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Support_HBuff_Pe2
        [209450] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Defend_PM_Ke2
        [209451] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Charge_PM_Fe2
        [209452] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Watch_PR_Re2
        [209453] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Strike_MRArea_We2
        [209454] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Support_HBuff_Pe2
        [209458] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvRLight_Support_Deform_Ee
        [209470] = [new Answer(23000, 1, 100)],  // LDF5_DGuard_DisputeRvRLight_Support_Deform_Ee
        [209473] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvRLight_Support_Deform_Ee
        [209475] = [new Answer(23000, 1, 100)],  // LDF5_DGuard_DisputeRvR_Support_Heal_Pe
        [209476] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvRLight_Defend_PM_Ke
        [209480] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Charge_PM_Fe
        [209483] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Charge_PM_Fe
        [209534] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Defend_PM_Ke2
        [209537] = [new Answer(23000, 1, 100)],  // DirectPortal_LGuard_Strike_MRArea_We2
        [209549] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Defend_PM_Ke2
        [209552] = [new Answer(23000, 1, 100)],  // DirectPortal_DGuard_Strike_MRArea_We2
        [209669] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [209675] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [219829] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_Safety_Chase_Fn
        [219830] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_Safety_Chase_Fn
        [219831] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_Safety_Chase_Fn
        [219832] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_Safety_Chase_Fn
        [219833] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_Safety_Hold_Rn
        [219834] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_Safety_Hold_Rn
        [219835] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_Safety_Hold_Rn
        [219836] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_Safety_Hold_Rn
        [219837] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Defend_PM_Kn
        [219838] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Defend_PM_Kn
        [219839] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Defend_PM_Kn
        [219840] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Defend_PM_Kn
        [219841] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_PR_Ge
        [219842] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_PR_Ge
        [219843] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_PR_Ge
        [219844] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_PR_Ge
        [219845] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [219846] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [219847] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [219848] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [219849] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [219850] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [219851] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [219868] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [219875] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [219881] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [219888] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [219894] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [219900] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [219907] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [219920] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [220063] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_Safety_Chase_Fn
        [220064] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [220065] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [220066] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [220067] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_PR_Ge
        [220068] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_Safety_Chase_Fn
        [220069] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [220070] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [220071] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [220072] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_PR_Ge
        [220073] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [220077] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [220085] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [220089] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [220093] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [220097] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [220106] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [220108] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [220139] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [220143] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [220145] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [220151] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [220152] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [220157] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [220160] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [220163] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [220166] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [220169] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [220193] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [220197] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [220201] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [220205] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [220209] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [220213] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [220217] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [220221] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [220223] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [220227] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [220231] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [220235] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [220239] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [220243] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [220247] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [220251] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [232846] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [232852] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Defend_PM_Ke
        [232857] = [new Answer(23100, 1, 100)],  // F5_RvR_LGuard_Kn_Ae
        [232858] = [new Answer(23100, 1, 100)],  // F5_RvR_LGuard_Kn_Ae
        [233127] = [new Answer(23100, 1000, -1)],  // IDF5_U2_Light_Wi_party_65_Ae
        [233128] = [new Answer(23100, 1000, -1)],  // IDF5_U2_Light_Pr_party_65_Ae
        [233130] = [new Answer(23200, 1000, -1)],  // IDF5_U2_Dark_Wi_party_65_Ae
        [233131] = [new Answer(23200, 1000, -1)],  // IDF5_U2_Dark_Pr_party_65_Ae
        [234044] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Defend_PM_Kn
        [234045] = [new Answer(23100, 1, 100)],  // F5_PvPLight_LGuard_Kn_An
        [234046] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [234047] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [234050] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Rn
        [234059] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Defend_PM_Kn
        [234062] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [234068] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_Wn
        [234074] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Defend_PM_Ke
        [234075] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [234076] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [234077] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [234080] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Re
        [234083] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [234086] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [234089] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Defend_PM_Ke
        [234090] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [234091] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [234092] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [234095] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Re
        [234098] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [234101] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [234136] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [234139] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [234966] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [234967] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [235172] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [235178] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [235184] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [235187] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [235190] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [235193] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [235196] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [235202] = [new Answer(23200, 1, 100)],  // F5_PvP_DGuard_Kn_Ae
        [235921] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_Safety_Chase_Fn
        [235922] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_Safety_Hold_Rn
        [235923] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Defend_PM_Kn
        [235924] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_PR_Ge
        [235925] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [235926] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [235927] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_Safety_Chase_Fn
        [235928] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_Safety_Hold_Rn
        [235929] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Defend_PM_Kn
        [235930] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_PR_Ge
        [235931] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [235932] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [235933] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_Safety_Chase_Fn
        [235934] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_Safety_Hold_Rn
        [235935] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Defend_PM_Kn
        [235936] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_PR_Ge
        [235937] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [235938] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [236029] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [236042] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [236062] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [236068] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [236250] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [236253] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [236254] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_PR_Ge
        [236256] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_Wn
        [236257] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [236261] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [236262] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_PR_Ge
        [236264] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [236265] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_Wn
        [236673] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [236677] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [236681] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [236685] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [236689] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [236693] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [236697] = [new Answer(23100, 1, 100)],  // F5_PvP_LGuard_Kn_Ae
        [236701] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_Safety_Chase_Fn
        [236702] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_Safety_Hold_Rn
        [236703] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_PR_Ge
        [251086] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [251094] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [251097] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Re
        [251099] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_PR_Ge
        [251102] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [251107] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [251110] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [251113] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Re
        [251115] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_PR_Ge
        [251118] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [251123] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [251126] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [251129] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Re
        [251151] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [251152] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_Wn
        [251153] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Rn
        [251154] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [251160] = [new Answer(23000, 1, 100)],  // AB1_DrGuard_Artifact_Killer
        [251179] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [251180] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_Wn
        [251181] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Rn
        [251182] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [251206] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [251207] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_Wn
        [251208] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Rn
        [251209] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [251233] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [251234] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_Wn
        [251235] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Rn
        [251260] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [251261] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_Wn
        [251262] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Rn
        [251263] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [251287] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [251288] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_Wn
        [251289] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Rn
        [251314] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [251315] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_Wn
        [251316] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Rn
        [251317] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [251450] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [251455] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [251456] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Re
        [251457] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [251461] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_Wn
        [251467] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [251480] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [251493] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [251498] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [251499] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Re
        [251500] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [251504] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_Wn
        [251510] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [251523] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [251536] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [251541] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [251542] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Re
        [251543] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [251547] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_Wn
        [251553] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [251566] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [251843] = [new Answer(23100, 1, 100)],  // F5_RvR_LGuard_Kn_Ae
        [251883] = [new Answer(23100, 1, 100)],  // F5_RvR_LGuard_Kn_Ae
        [251923] = [new Answer(23200, 1, 100)],  // F5_RvR_DGuard_Kn_Ae
        [251963] = [new Answer(23200, 1, 100)],  // F5_RvR_DGuard_Kn_Ae
        [252003] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Defend_PM_Ke
        [252008] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Charge_PM_Fe
        [252013] = [new Answer(23000, 1, 100)],  // LDF5_DisputeRvR_Watch_NoBroad_Ra
        [252018] = [new Answer(23000, 1, 100)],  // LDF5_DisputeRvR_Watch_NoBroad_Ra
        [252028] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Support_Heal_Pe
        [252033] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Support_Mez_We
        [252038] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Support_Deform_Ee
        [252043] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Defend_PM_Ke
        [252048] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Charge_PM_Fe
        [252053] = [new Answer(23000, 1, 100)],  // LDF5_DisputeRvR_Watch_NoBroad_Ra
        [252058] = [new Answer(23000, 1, 100)],  // LDF5_DisputeRvR_Watch_NoBroad_Ra
        [252063] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Strike_PR_Ge
        [252068] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Support_Heal_Pe
        [252073] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Support_Mez_We
        [252078] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Support_Deform_Ee
        [252083] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Strike_PR_Ge
        [252088] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Strike_PR_Ge
        [252181] = [new Answer(23100, 1, 100)],  // LDF5_Fortress_LDGuard_Artifact
        [252186] = [new Answer(23100, 1, 100)],  // LDF5_Fortress_LDGuard_Artifact
        [252191] = [new Answer(23100, 1, 100)],  // LDF5_Fortress_DrGuard_Artifact
        [252196] = [new Answer(23100, 1, 100)],  // LDF5_Fortress_LDGuard_Artifact
        [252201] = [new Answer(23100, 1, 100)],  // LDF5_Fortress_LDGuard_Artifact
        [252206] = [new Answer(23100, 1, 100)],  // LDF5_Fortress_DrGuard_Artifact
        [252211] = [new Answer(23100, 1, 100)],  // LDF5_Fortress_LDGuard_Artifact
        [252216] = [new Answer(23100, 1, 100)],  // LDF5_Fortress_LDGuard_Artifact
        [252221] = [new Answer(23100, 1, 100)],  // LDF5_Fortress_DrGuard_Artifact
        [252223] = [new Answer(23100, 1, 100)],  // F5_RvR_LGuard_Kn_Ae
        [252227] = [new Answer(23200, 1, 100)],  // F5_RvR_DGuard_Kn_Ae
        [252231] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Defend_PM_Ke
        [252232] = [new Answer(23000, 1, 100)],  // LDF5_DisputeRvR_Watch_NoBroad_Ra
        [252233] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Support_Heal_Pe
        [252234] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Support_Mez_We
        [252235] = [new Answer(23100, 1, 100)],  // F5_RvR_LGuard_Kn_Ae
        [252239] = [new Answer(23200, 1, 100)],  // F5_RvR_DGuard_Kn_Ae
        [252243] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Charge_PM_Fe
        [252244] = [new Answer(23000, 1, 100)],  // LDF5_DisputeRvR_Watch_NoBroad_Ra
        [252245] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Support_Heal_Pe
        [252246] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Support_Mez_We
        [252247] = [new Answer(23100, 1, 100)],  // F5_RvR_LGuard_Kn_Ae
        [252251] = [new Answer(23200, 1, 100)],  // F5_RvR_DGuard_Kn_Ae
        [252255] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Charge_PM_Fe
        [252256] = [new Answer(23000, 1, 100)],  // LDF5_DisputeRvR_Watch_NoBroad_Ra
        [252257] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Support_Heal_Pe
        [252258] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Support_Mez_We
        [252272] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Charge_PM_Fe
        [252287] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Charge_PM_Fe
        [252431] = [new Answer(23000, 1, 100)],  // LDF5_Fortress_DrGuard_Artifact_Killer
        [252432] = [new Answer(23000, 1, 100)],  // LDF5_Fortress_DrGuard_Artifact_Killer
        [252433] = [new Answer(23000, 1, 100)],  // LDF5_Fortress_DrGuard_Artifact_Killer
        [252434] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [252439] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [252444] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [252449] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [252454] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [252459] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [252464] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [252469] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [252474] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [252479] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [252484] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [252489] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [256697] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [256700] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [256703] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [256706] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [256709] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [256712] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [256715] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [256718] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [256721] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [256724] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [256727] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [256730] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [256733] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [256736] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [256739] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [256742] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [257038] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [257044] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [257047] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [257056] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [257059] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [257062] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [257065] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Rn
        [257068] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_Wn
        [257071] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pn
        [257102] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [257107] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [257112] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [257119] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [257122] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [257128] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [257131] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [257147] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [257152] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [257157] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [257164] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [257167] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [257173] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [257176] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [257332] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [257341] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [257344] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [257347] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [257353] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [257356] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [257359] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [257362] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [257365] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Rn
        [257368] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_Wn
        [257371] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pn
        [257402] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [257407] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [257412] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [257419] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [257422] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [257428] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [257431] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [257447] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [257452] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [257457] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [257464] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [257467] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [257473] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [257476] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [257529] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pn
        [257530] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [257659] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [257662] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [257668] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_Wn
        [257671] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pn
        [257674] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [257677] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [257683] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [257686] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [257689] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [257692] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [257695] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Rn
        [257698] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_Wn
        [257701] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pn
        [257702] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [257707] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [257712] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [257719] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [257722] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [257728] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [257731] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [257747] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [257752] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [257757] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [257764] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [257767] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [257773] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [257776] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [257830] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [257959] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [257962] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [257968] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_Wn
        [257971] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pn
        [257974] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [257977] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [257983] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [257986] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [257989] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [257992] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [257995] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Rn
        [257998] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_Wn
        [258001] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pn
        [258002] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [258007] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [258012] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [258019] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [258022] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [258028] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [258031] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [258047] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [258052] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [258057] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [258064] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [258067] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [258073] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [258076] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [258129] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pn
        [258130] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [260301] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [260309] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [260313] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [260604] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [260609] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [260612] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [260903] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [260909] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [260913] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [261204] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [261209] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [261213] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [261505] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [261509] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [261511] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [261804] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [261808] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [261811] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [262104] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [262109] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [262113] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [262404] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [262409] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [262414] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [262704] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [262709] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [262713] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [268103] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [268108] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [268113] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [268401] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [268406] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [268411] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [268703] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [268708] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [268713] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [269303] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [269308] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [269313] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [269603] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [269608] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [269613] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [270203] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [270208] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [270213] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [270505] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [270510] = [new Answer(23100, 1, 100)],  // AB1_LDGuard_Artifact
        [270515] = [new Answer(23100, 1, 100)],  // AB1_DrGuard_Artifact
        [277187] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Defend_PM_Ke
        [277188] = [new Answer(23000, 1, 100)],  // LDF5_DisputeRvR_Hide_As
        [277193] = [new Answer(23000, 1, 100)],  // LDF5_DisputeRvR_Debuff_Ba
        [277195] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Hide_PM_Ae
        [277196] = [new Answer(23000, 1, 100)],  // LDF5_DisputePvP_Strike_Gu
        [277198] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [277199] = [new Answer(23000, 1, 100)],  // LDF5_DisputePvP_Debuff_Ba
        [277200] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Defend_PM_Ke
        [277209] = [new Answer(23000, 1, 100)],  // LDF5_DisputePvP_Strike_Gu
        [277210] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pn
        [277211] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [277212] = [new Answer(23000, 1, 100)],  // LDF5_DisputePvP_Debuff_Ba
        [277242] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [277771] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [277775] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [277779] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [277783] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [279660] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [279685] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [279700] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [279715] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Re
        [279725] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_PR_Ge
        [279732] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Charge_PM_Fe
        [279754] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [279779] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [279794] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [279809] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Re
        [279819] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_PR_Ge
        [279829] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Charge_PM_Fe
        [279858] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [279883] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pe
        [279898] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_We
        [279913] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Re
        [279923] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_PR_Ge
        [279926] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Charge_PM_Fe
        [297115] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Charge_PM_Fe
        [297116] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Support_Deform_Ee
        [297190] = [new Answer(23000, 1, 100)],  // Gab1_Sub_Pod_Sum_Vri_Fi
        [297191] = [new Answer(23000, 1, 100)],  // Gab1_Sub_Pod_Sum_Vri_As
        [297192] = [new Answer(23000, 1, 100)],  // Gab1_Sub_Pod_Sum_Vri_Wi
        [800511] = [new Answer(23000, 1, 100)],  // LDF5_DGuard_DisputeRvR_Defend_PM_Ke
        [800512] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputeRvR_Defend_PM_Ke
        [801280] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [801281] = [new Answer(23100, 1, 100)],  // F5_PvPLight_LGuard_Kn_An
        [802054] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802328] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802329] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802330] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802331] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802332] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802333] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802334] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802335] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802336] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802337] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802338] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802339] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802340] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802341] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802342] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802343] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802344] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802345] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802346] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802347] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802348] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802349] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802377] = [new Answer(23100, 1, 100)],  // F5_PvPLight_LGuard_Kn_An
        [802383] = [new Answer(23100, 1, 100)],  // F5_PvPLight_LGuard_Kn_An
        [802384] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802427] = [new Answer(23100, 1, 100)],  // F5_PvPLight_LGuard_Kn_An
        [802428] = [new Answer(23100, 1, 100)],  // F5_PvPLight_LGuard_Kn_An
        [802429] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802430] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [802431] = [new Answer(23100, 1, 100)],  // F5_PvPLight_LGuard_Kn_An
        [802433] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [804584] = [new Answer(23100, 1, 100)],  // F5_PvPLight_LGuard_Kn_An
        [804585] = [new Answer(23100, 1, 100)],  // F5_PvPLight_LGuard_Kn_An
        [804586] = [new Answer(23100, 1, 100)],  // F5_PvPLight_LGuard_Kn_An
        [804587] = [new Answer(23100, 1, 100)],  // F5_PvPLight_LGuard_Kn_An
        [804588] = [new Answer(23100, 1, 100)],  // F5_PvPLight_LGuard_Kn_An
        [804589] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [804590] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [804591] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [804593] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805269] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805270] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805271] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805272] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805273] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805274] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805275] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805276] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805277] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805278] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805279] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805280] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805281] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805282] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805283] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805284] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805285] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805286] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805287] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805288] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805289] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805290] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805291] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805292] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805293] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [805294] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [832840] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [832841] = [new Answer(23200, 1, 100)],  // F5_PvPLight_DGuard_Kn_An
        [880751] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [880755] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [880759] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [880763] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [880767] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [880771] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [880775] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [880779] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [880783] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [880787] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [880791] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [880795] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fn
        [881738] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [881753] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Rn
        [881768] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_Wn
        [881783] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Support_HBuff_Pn
        [881798] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [881858] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Charge_PM_Fe
        [881873] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Watch_PR_Rn
        [881888] = [new Answer(23000, 1, 100)],  // LDF5_LGuard_DisputePvP_Strike_MRArea_Wn
    };

    /// <summary>
    /// The rungs one npc answers with, highest priority first, or empty for an npc that answers nothing.
    /// </summary>
    /// <remarks>
    /// The fighting rung is emitted <b>before</b> the idle one for the same call, because branch lists
    /// are first-match-wins and the idle rung's conditions are a subset of the fighting rung's -- emitted
    /// the other way round, a guard already in combat would take the idle answer and never switch.
    /// </remarks>
    internal static PatternBranch[] RungsFor(int npcId)
    {
        if (!ByNpc.TryGetValue(npcId, out Answer[]? answers))
            return [];

        List<PatternBranch> rungs = new List<PatternBranch>(answers.Length * 2);
        int priority = answers.Length * 2;
        foreach (Answer answer in answers)
        {
            if (answer.Busy >= 0)
            {
                rungs.Add(AiPattern.Branch(priority--, "a call, and I am already fighting",
                    [When.MessageParamIsEnemy, When.Message(answer.Call), When.Fighting],
                    Do.HateMessageTarget(answer.Busy)));
            }

            if (answer.Idle >= 0)
            {
                rungs.Add(AiPattern.Branch(priority--, "a call, and I am not",
                    [When.MessageParamIsEnemy, When.Message(answer.Call)],
                    Do.HateMessageParam(answer.Idle),
                    Do.AttackMostHating()));
            }
        }

        return rungs.ToArray();
    }

    /// <summary>
    /// The same two rungs for a listener that is <b>not</b> pattern-driven, applied directly.
    /// </summary>
    /// <remarks>
    /// Sixteen Ahserion npcs and four others answer <c>23000</c> in retail on classes that run plain
    /// <c>aggressive</c> with cast rotations this work cannot resolve, so there is no pattern to fold
    /// the rungs into. This is the same shape as <see cref="PullCalls"/>.<c>Shout</c>, which exists for
    /// the sending half and for the same reason.
    /// <para>
    /// The idle rung goes through <see cref="SummonOrder"/>, which <b>is</b> <c>add_hate_point</c>
    /// followed by <c>attack_most_hating</c> -- the same pair, already written and already reasoned
    /// about. The fighting rung is a <c>switch_target</c> and cannot use it: that one turns the npc
    /// whether or not the named player is the one it now hates most.
    /// </para>
    /// </remarks>
    /// <returns>true if this npc had an answer for the message, whether or not it landed.</returns>
    internal static bool AnswerCall(Npc listener, Npc sender, int messageType, VisibleObject? param)
    {
        if (listener.IsDead() || ReferenceEquals(sender, listener))
            return false;

        if (!ByNpc.TryGetValue(listener.GetNpcId(), out Answer[]? answers))
            return false;

        foreach (Answer answer in answers)
        {
            if (answer.Call != messageType)
                continue;

            // is_enemy, in the direction the pattern conditions use.
            if (param is not Creature named || named.IsDead() || !named.IsEnemy(listener))
                return true;

            if (answer.Busy >= 0 && listener.GetAi().IsInState(AIState.FIGHT))
            {
                listener.GetAggroList().AddHate(named, answer.Busy);
                listener.SetTarget(named);
                return true;
            }

            if (answer.Idle >= 0)
                SummonOrder.Take(listener, named, answer.Idle);

            return true;
        }

        return false;
    }
}
