// <auto-generated>
//     Generated by tools/client-extract/emit_panesterra_pulls_table.py from the retail AI patterns.
//     Do not edit by hand: re-run the extractor instead. See docs/retail-ai-fidelity.md.
// </auto-generated>

using Aion.GameServer.Ai.Pattern;

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// What an Ashunatal guard shouts when it is pulled: retail's <c>41000</c>, <c>41001</c>, <c>41100</c>
/// and <c>41101</c>.
/// </summary>
/// <remarks>
/// 474 calls across 474 npcs. **The answering half of this was already ported and the sending half
/// was not** -- 552 npcs listen for 41101 alone, and sixteen sent it.
/// <para>
/// 66 npcs shout 41000 at 13 metres; 66 npcs shout 41000 at 25 metres; 17 npcs shout 41001 at 13 metres; 129 npcs shout 41100 at 13 metres; 129 npcs shout 41100 at 25 metres; 67 npcs shout 41101 at 13 metres
/// </para>
/// <para>
/// <b>The call and its range are per npc, not per class.</b> One <c>panesterra_patrol</c> covers guards
/// that shout at thirteen metres and guards that shout at twenty-five; <c>base_protector</c> covers
/// garrison chiefs that shout 41101 and base bosses that shout nothing at all. A constant in a class
/// cannot say that.
/// </para>
/// <para>
/// <b>Some guards shout twice.</b> <c>Gab1_Gaurd_Ra_An_Broad</c> broadcasts 41100 at thirteen metres and
/// again at twenty-five -- a near call and a far one in the same rung -- so this is a list per npc
/// rather than one entry.
/// </para>
/// </remarks>
internal static class PanesterraPulls
{
    /// <param name="Call">Retail's message number. The captain calls (41001, 41101) are obeyed; the
    /// guard calls (41000, 41100) are only noted.</param>
    /// <param name="Range">Retail's <c>range_as_meter</c>.</param>
    internal readonly record struct Pull(int Call, float Range);

    internal static readonly IReadOnlyDictionary<int, Pull[]> ByNpc = new Dictionary<int, Pull[]>
    {
        [277576] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [277577] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [277578] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [277579] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [277580] = [new Pull(41001, 13f)],  // Gab1_VritraGuard_Boss_01
        [277581] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [277582] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [277583] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [277584] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [277585] = [new Pull(41001, 13f)],  // Gab1_VritraGuard_Boss_01
        [277586] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [277587] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [277588] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [277589] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [277590] = [new Pull(41001, 13f)],  // Gab1_VritraGuard_Boss_01
        [277591] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [277592] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [277593] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [277594] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [277595] = [new Pull(41001, 13f)],  // Gab1_VritraGuard_Boss_01
        [277656] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277657] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277658] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277659] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277660] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [277661] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277662] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277663] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277664] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277665] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [277666] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277667] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277668] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277669] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277670] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [277671] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277672] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277673] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277674] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277675] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [277676] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277677] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277678] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277679] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277680] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [277681] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277682] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277683] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277684] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277685] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [277686] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277687] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277688] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277689] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277690] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [277691] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277692] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277693] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277694] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277695] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [277720] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277721] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277722] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277723] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277724] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [277725] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [277726] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277727] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277728] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277729] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277730] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [277731] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [277732] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277733] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277734] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277735] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277736] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [277737] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [277738] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277739] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277740] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277741] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [277742] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [277743] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [277744] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277745] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277746] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277747] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277748] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [277749] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [277750] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277751] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277752] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277753] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277754] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [277755] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [277756] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277757] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277758] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277759] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277760] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [277761] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [277762] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277763] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277764] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277765] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [277766] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [277767] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [297435] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [297436] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [297440] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [297441] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [297442] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [297443] = [new Pull(41001, 13f)],  // Gab1_VritraGuard_Boss_01
        [297513] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [297514] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [702333] = [new Pull(41101, 13f)],  // Gab1_SetCond_Noshow_08
        [702337] = [new Pull(41101, 13f)],  // Gab1_SetCond_Noshow_08
        [880132] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880133] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880134] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880135] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880136] = [new Pull(41001, 13f)],  // Gab1_VritraGuard_Boss_01
        [880137] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880138] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880139] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880140] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880141] = [new Pull(41001, 13f)],  // Gab1_VritraGuard_Boss_01
        [880142] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880143] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880144] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880145] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880146] = [new Pull(41001, 13f)],  // Gab1_VritraGuard_Boss_01
        [880147] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880148] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880149] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880150] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880151] = [new Pull(41001, 13f)],  // Gab1_VritraGuard_Boss_01
        [880152] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880153] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880154] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880155] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880156] = [new Pull(41001, 13f)],  // Gab1_VritraGuard_Boss_01
        [880157] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880158] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880159] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880160] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880161] = [new Pull(41001, 13f)],  // Gab1_VritraGuard_Boss_01
        [880162] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880163] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880164] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880165] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880166] = [new Pull(41001, 13f)],  // Gab1_VritraGuard_Boss_01
        [880167] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880168] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880169] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880170] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880171] = [new Pull(41001, 13f)],  // Gab1_VritraGuard_Boss_01
        [880172] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880173] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880174] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880175] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880176] = [new Pull(41001, 13f)],  // Gab1_VritraGuard_Boss_01
        [880177] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880178] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880179] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880180] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880181] = [new Pull(41001, 13f)],  // Gab1_VritraGuard_Boss_01
        [880182] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880183] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880184] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880185] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880186] = [new Pull(41001, 13f)],  // Gab1_VritraGuard_Boss_01
        [880187] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880188] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880189] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880190] = [new Pull(41101, 13f)],  // Gab1_LGuard_Boss_01
        [880191] = [new Pull(41001, 13f)],  // Gab1_VritraGuard_Boss_01
        [880372] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880373] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880374] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880375] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880376] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880377] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880378] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880379] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880380] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880381] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880382] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880383] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880384] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880385] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880386] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880387] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880388] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880389] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880390] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880391] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880392] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880393] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880394] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880395] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880396] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880397] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880398] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880399] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880400] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880401] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880402] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880403] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880404] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880405] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880406] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880407] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880408] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880409] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880410] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880411] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880412] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880413] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880414] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880415] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880416] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880417] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880418] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880419] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880420] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880421] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880422] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880423] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880424] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880425] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880426] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880427] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880428] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880429] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880430] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880431] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880432] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880433] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880434] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880435] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880436] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880437] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880438] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880439] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880440] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880441] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880442] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880443] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880444] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880445] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880446] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880447] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880448] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880449] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880450] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880451] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880452] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880453] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880454] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880455] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880456] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880457] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880458] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880459] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880460] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880461] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880462] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880463] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880464] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880465] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880466] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880467] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880468] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880469] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880470] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880471] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880472] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880473] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880474] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880475] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880476] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880477] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880478] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880479] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880480] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880481] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880482] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880483] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880484] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880485] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880486] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880487] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880488] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880489] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880490] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880491] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880580] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880581] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880582] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880583] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880584] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880585] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880586] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880587] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880588] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880589] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880590] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880591] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880592] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880593] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880594] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880595] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880596] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880597] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880598] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880599] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880600] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880601] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880602] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880603] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880604] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880605] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880606] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880607] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880608] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880609] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880610] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880611] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880612] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880613] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880614] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880615] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880616] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880617] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880618] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880619] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880620] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880621] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880622] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880623] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880624] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880625] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880626] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880627] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880628] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880629] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880630] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880631] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880632] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880633] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880634] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880635] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880636] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880637] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880638] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880639] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880640] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880641] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880642] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880643] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880644] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880645] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880646] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880647] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880648] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880649] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880650] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880651] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880652] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880653] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880654] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880655] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880656] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880657] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880658] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880659] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880660] = [new Pull(41100, 25f)],  // Gab1_Gaurd_Ra_An_Broad
        [880661] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880662] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880663] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880664] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880665] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880666] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880667] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880668] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880669] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880670] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880671] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880672] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880673] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880674] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880675] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880676] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880677] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880678] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880679] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880680] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880681] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880682] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880683] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880684] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880685] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880686] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880687] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880688] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880689] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880690] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880691] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880692] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880693] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880694] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880695] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880696] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880697] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880698] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880699] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880700] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880701] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880702] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880703] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880704] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880705] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880706] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880707] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880708] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880709] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880710] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880711] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880712] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880713] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880714] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880715] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880716] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880717] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880718] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880719] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880720] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880721] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880722] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880723] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880724] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880725] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880726] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880727] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880728] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880729] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880730] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880731] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880732] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880733] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880734] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880735] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880736] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880737] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880738] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880739] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880740] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880741] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880742] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880743] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880744] = [new Pull(41100, 13f)],  // Gab1_LGuard_05
        [880745] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880746] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880747] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880796] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880797] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880798] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880799] = [new Pull(41000, 25f)],  // Gab1_Gaurd_Watch_PR_Rn
        [880800] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880801] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880802] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
        [880803] = [new Pull(41000, 13f)],  // Gab1_Gaurd_An
    };

    private static readonly System.Collections.Concurrent.ConcurrentDictionary<int, PatternBranch[]>
        Built = new System.Collections.Concurrent.ConcurrentDictionary<int, PatternBranch[]>();

    /// <summary>
    /// The enter-combat rung for one guard, or nothing for an npc that is pulled in silence.
    /// </summary>
    /// <remarks>
    /// <b>One branch carrying every call</b>, never one branch each. Branch lists are first-match-wins,
    /// so two unconditional branches would leave the second dead -- which is exactly the bug found twice
    /// in the fortress killers, and retail writes these as one rung with two broadcasts anyway.
    /// </remarks>
    internal static PatternBranch[] RungFor(int npcId) => Built.GetOrAdd(npcId, static id =>
    {
        if (!ByNpc.TryGetValue(id, out Pull[] calls))
            return [];

        PatternAction[] actions = new PatternAction[calls.Length];
        for (int i = 0; i < calls.Length; i++)
            actions[i] = Do.Broadcast(calls[i].Call, calls[i].Range, aboutTarget: true);

        return [new PatternBranch(7, "pulled -- tell the guards around me", [], actions)];
    });
}
