// <auto-generated>
//     Generated by tools/client-extract/emit_protector_calls_table.py from the retail AI patterns.
//     Do not edit by hand: re-run the extractor instead. See docs/retail-ai-fidelity.md.
// </auto-generated>
#nullable enable

using Aion.GameServer.Ai.Pattern;

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// When a siege protector calls its killer to itself: retail's message <c>30002</c>.
/// </summary>
/// <remarks>
/// 754 npcs across 62 retail patterns, and <b>nothing in this port sent it before this
/// table existed</b>. Retail's siege fight is a three-message loop -- the killer wakes and pulls the
/// protectors (30001), a protector calls the killer to itself (30002), a dying protector calls it off
/// (30003) -- and the middle one was missing, so <c>FortressKillerAI</c>'s answer to it had never been
/// reachable. The fight could start and end but never move.
/// <para>
/// <b>The cadence is read out of the timer chain, not assumed.</b> The broadcast hangs off a battle
/// timer several rungs deep, and the chain differs per pattern: 348 npcs first call at 21.5s then every 22s, 176 npcs first call at 27.5s then every 28s, 120 npcs first call at 0s then every 5s, 104 npcs first call at 5s then every 5s. The extractor walks
/// timer -> (next timer, delay) edges from the enter-combat rung to the one that broadcasts, and
/// <b>refuses</b> any chain that only reaches the broadcast through a guarded rung -- a chain gated on
/// health has two cadences, not one, and a single number for it would look measured without being so.
/// </para>
/// <para>
/// Some npcs open at zero: retail's village chiefs broadcast in the enter-combat rung itself and then
/// every five seconds, which their own comment on that rung says in as many words.
/// </para>
/// </remarks>
internal static class ProtectorCalls
{
    /// <param name="First">Milliseconds from entering combat to the first call. Zero means at once.</param>
    /// <param name="Period">Milliseconds between calls thereafter.</param>
    /// <param name="Range">Retail's <c>range_as_meter</c>, which is not the same for every protector.</param>
    internal readonly record struct Call(int First, int Period, float Range);

    internal static readonly IReadOnlyDictionary<int, Call> ByNpc = new Dictionary<int, Call>
    {
        [231630] = new Call(0, 5000, 20f),  // LDF5_Village_chief01
        [231631] = new Call(0, 5000, 20f),  // LDF5_Village_chief01
        [231632] = new Call(0, 5000, 20f),  // LDF5_Village_chief01
        [231633] = new Call(0, 5000, 20f),  // LDF5_Village_chief02
        [231634] = new Call(0, 5000, 20f),  // LDF5_Village_chief02
        [231635] = new Call(0, 5000, 20f),  // LDF5_Village_chief02
        [231636] = new Call(0, 5000, 20f),  // LDF5_Village_chief03
        [231637] = new Call(0, 5000, 20f),  // LDF5_Village_chief03
        [231638] = new Call(0, 5000, 20f),  // LDF5_Village_chief03
        [231639] = new Call(0, 5000, 20f),  // LDF5_Village_chief04
        [231640] = new Call(0, 5000, 20f),  // LDF5_Village_chief04
        [231641] = new Call(0, 5000, 20f),  // LDF5_Village_chief04
        [231642] = new Call(0, 5000, 20f),  // LDF5_Village_chief05
        [231643] = new Call(0, 5000, 20f),  // LDF5_Village_chief05
        [231644] = new Call(0, 5000, 20f),  // LDF5_Village_chief05
        [231645] = new Call(0, 5000, 20f),  // LDF5_Village_chief06
        [231646] = new Call(0, 5000, 20f),  // LDF5_Village_chief06
        [231647] = new Call(0, 5000, 20f),  // LDF5_Village_chief06
        [231648] = new Call(0, 5000, 20f),  // LDF5_Village_chief07
        [231649] = new Call(0, 5000, 20f),  // LDF5_Village_chief07
        [231650] = new Call(0, 5000, 20f),  // LDF5_Village_chief07
        [231651] = new Call(0, 5000, 20f),  // LDF5_Village_chief08
        [231652] = new Call(0, 5000, 20f),  // LDF5_Village_chief08
        [231653] = new Call(0, 5000, 20f),  // LDF5_Village_chief08
        [231654] = new Call(0, 5000, 20f),  // LDF5_Village_chief09
        [231655] = new Call(0, 5000, 20f),  // LDF5_Village_chief09
        [231656] = new Call(0, 5000, 20f),  // LDF5_Village_chief09
        [231657] = new Call(0, 5000, 20f),  // LDF5_Village_chief10
        [231658] = new Call(0, 5000, 20f),  // LDF5_Village_chief10
        [231659] = new Call(0, 5000, 20f),  // LDF5_Village_chief10
        [231660] = new Call(0, 5000, 20f),  // LDF5_Village_chief11
        [231661] = new Call(0, 5000, 20f),  // LDF5_Village_chief11
        [231662] = new Call(0, 5000, 20f),  // LDF5_Village_chief11
        [231663] = new Call(0, 5000, 20f),  // LDF5_Village_chief12
        [231664] = new Call(0, 5000, 20f),  // LDF5_Village_chief12
        [231665] = new Call(0, 5000, 20f),  // LDF5_Village_chief12
        [231666] = new Call(0, 5000, 20f),  // LDF5_Village_chief13
        [231667] = new Call(0, 5000, 20f),  // LDF5_Village_chief13
        [231668] = new Call(0, 5000, 20f),  // LDF5_Village_chief13
        [231669] = new Call(0, 5000, 20f),  // LDF5_Village_chief14
        [231670] = new Call(0, 5000, 20f),  // LDF5_Village_chief14
        [231671] = new Call(0, 5000, 20f),  // LDF5_Village_chief14
        [231672] = new Call(0, 5000, 20f),  // LDF5_Village_chief15
        [231673] = new Call(0, 5000, 20f),  // LDF5_Village_chief15
        [231674] = new Call(0, 5000, 20f),  // LDF5_Village_chief15
        [231675] = new Call(0, 5000, 20f),  // LDF5_Village_chief16
        [231676] = new Call(0, 5000, 20f),  // LDF5_Village_chief16
        [231677] = new Call(0, 5000, 20f),  // LDF5_Village_chief16
        [231678] = new Call(0, 5000, 20f),  // LDF5_Village_chief17
        [231679] = new Call(0, 5000, 20f),  // LDF5_Village_chief17
        [231680] = new Call(0, 5000, 20f),  // LDF5_Village_chief17
        [231681] = new Call(0, 5000, 20f),  // LDF5_Village_chief18
        [231682] = new Call(0, 5000, 20f),  // LDF5_Village_chief18
        [231683] = new Call(0, 5000, 20f),  // LDF5_Village_chief18
        [231684] = new Call(0, 5000, 20f),  // LDF5_Village_chief19
        [231685] = new Call(0, 5000, 20f),  // LDF5_Village_chief19
        [231686] = new Call(0, 5000, 20f),  // LDF5_Village_chief19
        [234032] = new Call(0, 5000, 20f),  // LDF5_Village_chief01
        [234033] = new Call(0, 5000, 20f),  // LDF5_Village_chief01
        [234034] = new Call(0, 5000, 20f),  // LDF5_Village_chief01
        [234035] = new Call(0, 5000, 20f),  // LDF5_Village_chief02
        [234036] = new Call(0, 5000, 20f),  // LDF5_Village_chief02
        [234037] = new Call(0, 5000, 20f),  // LDF5_Village_chief02
        [234038] = new Call(0, 37000, 20f),  // LDF5_Fortress_MistOn_Vil_Chief03
        [234039] = new Call(0, 37000, 20f),  // LDF5_Fortress_MistOn_Vil_Chief03
        [234040] = new Call(0, 37000, 20f),  // LDF5_Fortress_MistOn_Vil_Chief03
        [234041] = new Call(0, 37000, 20f),  // LDF5_Fortress_MistOn_Vil_Chief04
        [234042] = new Call(0, 37000, 20f),  // LDF5_Fortress_MistOn_Vil_Chief04
        [234043] = new Call(0, 37000, 20f),  // LDF5_Fortress_MistOn_Vil_Chief04
        [234162] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_19
        [234164] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_01
        [234166] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_10
        [234196] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_03
        [234197] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_06
        [234198] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_08
        [234199] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_17
        [234200] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_20
        [234201] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_03
        [234202] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_06
        [234203] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_08
        [234204] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_17
        [234205] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_20
        [234206] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_12
        [234207] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_15
        [234208] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_09
        [234209] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_18
        [234210] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_21
        [234211] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_12
        [234212] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_15
        [234213] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_09
        [234214] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_18
        [234215] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_21
        [234616] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_02
        [234617] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_04
        [234618] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_05
        [234619] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_07
        [234620] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_11
        [234621] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_13
        [234622] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_14
        [234623] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_16
        [234624] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_02
        [234625] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_04
        [234626] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_05
        [234627] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_07
        [234628] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_11
        [234629] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_13
        [234630] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_14
        [234631] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_16
        [234632] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_02
        [234633] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_04
        [234634] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_05
        [234635] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_07
        [234636] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_11
        [234637] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_13
        [234638] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_14
        [234639] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_16
        [234640] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_01
        [234641] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_10
        [234642] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_19
        [234643] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_01
        [234644] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_10
        [234645] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_19
        [235066] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_02
        [235067] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_03
        [235068] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_04
        [235069] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_05
        [235070] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_06
        [235071] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_07
        [235072] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_08
        [235073] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_09
        [235141] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_12
        [235142] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_10
        [235143] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_11
        [235144] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_01
        [235145] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_13
        [235146] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_14
        [235147] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_15
        [235148] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_16
        [235149] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_17
        [235150] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_18
        [235151] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_19
        [235152] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_20
        [235153] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_21
        [235154] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_22
        [235155] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_23
        [235156] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_24
        [235157] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_25
        [235158] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_13
        [235159] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_26
        [235160] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_27
        [235161] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_28
        [235162] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_29
        [235163] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_30
        [235164] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_31
        [235165] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_32
        [235166] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_33
        [235167] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_34
        [235168] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_35
        [235169] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_36
        [235170] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_37
        [235171] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_13
        [246061] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [246066] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [251450] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [251451] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [251452] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [251453] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [251454] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [251467] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251468] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251469] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251470] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251471] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251480] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251481] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251482] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251483] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251484] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251493] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [251494] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [251495] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [251496] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [251497] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [251510] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251511] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251512] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251513] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251514] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251523] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251524] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251525] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251526] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251527] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251536] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [251537] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [251538] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [251539] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [251540] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [251553] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251554] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251555] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251556] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251557] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251566] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251567] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251568] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251569] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251570] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251822] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251823] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [251824] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [252178] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252179] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252180] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252181] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252182] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252183] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252184] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252185] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252186] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252187] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252188] = new Call(27500, 28000, 50f),  // LDF5_Fortress_DrGuard_Artifact
        [252189] = new Call(27500, 28000, 50f),  // LDF5_Fortress_DrGuard_Artifact
        [252190] = new Call(27500, 28000, 50f),  // LDF5_Fortress_DrGuard_Artifact
        [252191] = new Call(27500, 28000, 50f),  // LDF5_Fortress_DrGuard_Artifact
        [252192] = new Call(27500, 28000, 50f),  // LDF5_Fortress_DrGuard_Artifact
        [252193] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252194] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252195] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252196] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252197] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252198] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252199] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252200] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252201] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252202] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252203] = new Call(27500, 28000, 50f),  // LDF5_Fortress_DrGuard_Artifact
        [252204] = new Call(27500, 28000, 50f),  // LDF5_Fortress_DrGuard_Artifact
        [252205] = new Call(27500, 28000, 50f),  // LDF5_Fortress_DrGuard_Artifact
        [252206] = new Call(27500, 28000, 50f),  // LDF5_Fortress_DrGuard_Artifact
        [252207] = new Call(27500, 28000, 50f),  // LDF5_Fortress_DrGuard_Artifact
        [252208] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252209] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252210] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252211] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252212] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252213] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252214] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252215] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252216] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252217] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [252218] = new Call(27500, 28000, 50f),  // LDF5_Fortress_DrGuard_Artifact
        [252219] = new Call(27500, 28000, 50f),  // LDF5_Fortress_DrGuard_Artifact
        [252220] = new Call(27500, 28000, 50f),  // LDF5_Fortress_DrGuard_Artifact
        [252221] = new Call(27500, 28000, 50f),  // LDF5_Fortress_DrGuard_Artifact
        [252222] = new Call(27500, 28000, 50f),  // LDF5_Fortress_DrGuard_Artifact
        [252434] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252435] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252436] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252437] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252438] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252439] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252440] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252441] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252442] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252443] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252444] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [252445] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [252446] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [252447] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [252448] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [252449] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252450] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252451] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252452] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252453] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252454] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252455] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252456] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252457] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252458] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252459] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [252460] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [252461] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [252462] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [252463] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [252464] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252465] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252466] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252467] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252468] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252469] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252470] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252471] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252472] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252473] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252474] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [252475] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [252476] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [252477] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [252478] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [252479] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252480] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252481] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252482] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252483] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252484] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252485] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252486] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252487] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252488] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [252489] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [252490] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [252491] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [252492] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [252493] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257102] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257103] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257104] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257105] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257106] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257107] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257108] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257109] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257110] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257111] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257112] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257113] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257114] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257115] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257116] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257147] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257148] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257149] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257150] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257151] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257152] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257153] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257154] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257155] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257156] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257157] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257158] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257159] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257160] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257161] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257402] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257403] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257404] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257405] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257406] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257407] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257408] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257409] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257410] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257411] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257412] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257413] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257414] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257415] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257416] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257447] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257448] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257449] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257450] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257451] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257452] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257453] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257454] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257455] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257456] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257457] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257458] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257459] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257460] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257461] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257702] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257703] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257704] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257705] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257706] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257707] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257708] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257709] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257710] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257711] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257712] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257713] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257714] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257715] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257716] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257747] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257748] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257749] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257750] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257751] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257752] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257753] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257754] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257755] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257756] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [257757] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257758] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257759] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257760] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [257761] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [258002] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [258003] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [258004] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [258005] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [258006] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [258007] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [258008] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [258009] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [258010] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [258011] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [258012] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [258013] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [258014] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [258015] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [258016] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [258047] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [258048] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [258049] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [258050] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [258051] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [258052] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [258053] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [258054] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [258055] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [258056] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [258057] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [258058] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [258059] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [258060] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [258061] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [260301] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260302] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260303] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260304] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260305] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260306] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260307] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260308] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260309] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260310] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260311] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [260312] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [260313] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [260314] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [260315] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [260601] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260602] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260603] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260604] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260605] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260606] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260607] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260608] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260609] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260610] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260611] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [260612] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [260613] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [260614] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [260615] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [260901] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260902] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260903] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260904] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260905] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260906] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260907] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260908] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260909] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260910] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [260911] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [260912] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [260913] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [260914] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [260915] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [261201] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261202] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261203] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261204] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261205] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261206] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261207] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261208] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261209] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261210] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261211] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [261212] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [261213] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [261214] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [261215] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [261501] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261502] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261503] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261504] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261505] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261506] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261507] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261508] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261509] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261510] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261511] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [261512] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [261513] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [261514] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [261515] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [261801] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261802] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261803] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261804] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261805] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261806] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261807] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261808] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261809] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261810] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [261811] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [261812] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [261813] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [261814] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [261815] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [262101] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262102] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262103] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262104] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262105] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262106] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262107] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262108] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262109] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262110] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262111] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [262112] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [262113] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [262114] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [262115] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [262401] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262402] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262403] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262404] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262405] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262406] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262407] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262408] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262409] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262410] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262411] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [262412] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [262413] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [262414] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [262415] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [262701] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262702] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262703] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262704] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262705] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262706] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262707] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262708] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262709] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262710] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [262711] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [262712] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [262713] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [262714] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [262715] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [268101] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268102] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268103] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268104] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268105] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268106] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268107] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268108] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268109] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268110] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268111] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [268112] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [268113] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [268114] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [268115] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [268401] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268402] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268403] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268404] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268405] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268406] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268407] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268408] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268409] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268410] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268411] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [268412] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [268413] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [268414] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [268415] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [268701] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268702] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268703] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268704] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268705] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268706] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268707] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268708] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268709] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268710] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [268711] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [268712] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [268713] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [268714] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [268715] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [269301] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [269302] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [269303] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [269304] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [269305] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [269306] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [269307] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [269308] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [269309] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [269310] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [269311] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [269312] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [269313] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [269314] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [269315] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [269601] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [269602] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [269603] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [269604] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [269605] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [269606] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [269607] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [269608] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [269609] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [269610] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [269611] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [269612] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [269613] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [269614] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [269615] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [270201] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [270202] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [270203] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [270204] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [270205] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [270206] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [270207] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [270208] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [270209] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [270210] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [270211] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [270212] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [270213] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [270214] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [270215] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [270501] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [270502] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [270503] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [270504] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [270505] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [270506] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [270507] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [270508] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [270509] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [270510] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [270511] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [270512] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [270513] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [270514] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [270515] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [277069] = new Call(0, 5000, 20f),  // LDF5_Village_chief01
        [277070] = new Call(0, 5000, 20f),  // LDF5_Village_chief01
        [277071] = new Call(0, 5000, 20f),  // LDF5_Village_chief01
        [277072] = new Call(0, 5000, 20f),  // LDF5_Village_chief02
        [277073] = new Call(0, 5000, 20f),  // LDF5_Village_chief02
        [277074] = new Call(0, 5000, 20f),  // LDF5_Village_chief02
        [277075] = new Call(0, 5000, 20f),  // LDF5_Village_chief03
        [277076] = new Call(0, 5000, 20f),  // LDF5_Village_chief03
        [277077] = new Call(0, 5000, 20f),  // LDF5_Village_chief03
        [277078] = new Call(0, 5000, 20f),  // LDF5_Village_chief04
        [277079] = new Call(0, 5000, 20f),  // LDF5_Village_chief04
        [277080] = new Call(0, 5000, 20f),  // LDF5_Village_chief04
        [277081] = new Call(0, 5000, 20f),  // LDF5_Village_chief05
        [277082] = new Call(0, 5000, 20f),  // LDF5_Village_chief05
        [277083] = new Call(0, 5000, 20f),  // LDF5_Village_chief05
        [277084] = new Call(0, 5000, 20f),  // LDF5_Village_chief06
        [277085] = new Call(0, 5000, 20f),  // LDF5_Village_chief06
        [277086] = new Call(0, 5000, 20f),  // LDF5_Village_chief06
        [277087] = new Call(0, 5000, 20f),  // LDF5_Village_chief07
        [277088] = new Call(0, 5000, 20f),  // LDF5_Village_chief07
        [277089] = new Call(0, 5000, 20f),  // LDF5_Village_chief07
        [277090] = new Call(0, 5000, 20f),  // LDF5_Village_chief08
        [277091] = new Call(0, 5000, 20f),  // LDF5_Village_chief08
        [277092] = new Call(0, 5000, 20f),  // LDF5_Village_chief08
        [277093] = new Call(0, 5000, 20f),  // LDF5_Village_chief09
        [277094] = new Call(0, 5000, 20f),  // LDF5_Village_chief09
        [277095] = new Call(0, 5000, 20f),  // LDF5_Village_chief09
        [277096] = new Call(0, 5000, 20f),  // LDF5_Village_chief10
        [277097] = new Call(0, 5000, 20f),  // LDF5_Village_chief10
        [277098] = new Call(0, 5000, 20f),  // LDF5_Village_chief10
        [277099] = new Call(0, 5000, 20f),  // LDF5_Village_chief11
        [277100] = new Call(0, 5000, 20f),  // LDF5_Village_chief11
        [277101] = new Call(0, 5000, 20f),  // LDF5_Village_chief11
        [277102] = new Call(0, 5000, 20f),  // LDF5_Village_chief12
        [277103] = new Call(0, 5000, 20f),  // LDF5_Village_chief12
        [277104] = new Call(0, 5000, 20f),  // LDF5_Village_chief12
        [277105] = new Call(0, 5000, 20f),  // LDF5_Village_chief13
        [277106] = new Call(0, 5000, 20f),  // LDF5_Village_chief13
        [277107] = new Call(0, 5000, 20f),  // LDF5_Village_chief13
        [277108] = new Call(0, 5000, 20f),  // LDF5_Village_chief14
        [277109] = new Call(0, 5000, 20f),  // LDF5_Village_chief14
        [277110] = new Call(0, 5000, 20f),  // LDF5_Village_chief14
        [277111] = new Call(0, 5000, 20f),  // LDF5_Village_chief15
        [277112] = new Call(0, 5000, 20f),  // LDF5_Village_chief15
        [277113] = new Call(0, 5000, 20f),  // LDF5_Village_chief15
        [277114] = new Call(0, 5000, 20f),  // LDF5_Village_chief16
        [277115] = new Call(0, 5000, 20f),  // LDF5_Village_chief16
        [277116] = new Call(0, 5000, 20f),  // LDF5_Village_chief16
        [277117] = new Call(0, 5000, 20f),  // LDF5_Village_chief17
        [277118] = new Call(0, 5000, 20f),  // LDF5_Village_chief17
        [277119] = new Call(0, 5000, 20f),  // LDF5_Village_chief17
        [277120] = new Call(0, 5000, 20f),  // LDF5_Village_chief18
        [277121] = new Call(0, 5000, 20f),  // LDF5_Village_chief18
        [277122] = new Call(0, 5000, 20f),  // LDF5_Village_chief18
        [277123] = new Call(0, 5000, 20f),  // LDF5_Village_chief19
        [277124] = new Call(0, 5000, 20f),  // LDF5_Village_chief19
        [277125] = new Call(0, 5000, 20f),  // LDF5_Village_chief19
        [297158] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [297159] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [297160] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [297203] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [297204] = new Call(21500, 22000, 50f),  // AB1_LDGuard_Artifact
        [297205] = new Call(27500, 28000, 50f),  // AB1_DrGuard_Artifact
        [297516] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [297517] = new Call(21500, 22000, 50f),  // LDF5_Fortress_LDGuard_Artifact
        [297518] = new Call(27500, 28000, 50f),  // LDF5_Fortress_DrGuard_Artifact
        [855077] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_02
        [855078] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_02
        [855079] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_02
        [855080] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_02
        [855271] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_02
        [855272] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_04
        [855273] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_05
        [855274] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_07
        [855275] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_02
        [855276] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_02
        [855277] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_02
        [855278] = new Call(5000, 5000, 50f),  // LDF4_Advance_village_02
    };

    private static readonly System.Collections.Concurrent.ConcurrentDictionary<int, AiPattern> Built =
        new System.Collections.Concurrent.ConcurrentDictionary<int, AiPattern>();

    private static readonly AiPattern Silent = new AiPattern();

    /// <summary>
    /// The call pattern for one protector, or an empty one for the many that never call.
    /// </summary>
    /// <remarks>
    /// <b>Four unrelated classes own npcs in this table</b> -- the two siege protectors, the base
    /// protectors and the simple abyss guards -- and only the first two share a base. So the pattern is
    /// built here, beside the numbers, and each class returns it from its own <c>Pattern</c> property.
    /// The alternative was the same twenty lines in four places, differing by accident within a year.
    /// </remarks>
    internal static AiPattern PatternFor(int npcId) => Built.GetOrAdd(npcId, static id =>
    {
        // The pull call belongs in the SAME enter-combat branch, not behind it: branch lists are
        // first-match-wins, so a second unconditional branch would be dead -- the bug found twice in the
        // fortress killers. 557 siege protectors shout 23200 when pulled, naming the player to every
        // guard around them, and this class had no part of that.
        PatternBranch[] pull = PullCalls.RungFor(id);
        PatternAction[] pullActions = pull.Length == 0 ? [] : pull[0].Actions;

        // The answering half of the same family. 102 artifact protectors answer 23100 in retail and this
        // class had no `on_message` at all, so these fold in additively -- unlike the pull call above,
        // which had to join an existing branch rather than sit behind it.
        PatternBranch[] answers = GuardAnswers.RungsFor(id);

        if (!ByNpc.TryGetValue(id, out Call call))
        {
            return pullActions.Length == 0 && answers.Length == 0
                ? Silent
                : new AiPattern
                {
                    OnMessage = AiPattern.Of(answers),
                    OnEnterAttack = pullActions.Length == 0
                        ? AiPattern.Of()
                        : AiPattern.Of(
                            AiPattern.Branch(7, "pulled -- tell the guards around me", When.Always,
                                pullActions)),
                };
        }

        return new AiPattern
        {
            OnMessage = AiPattern.Of(answers),

            OnEnterAttack = AiPattern.Of(
                call.First == 0
                    ? AiPattern.Branch(7, "call at once, then keep calling", When.Always,
                        [Do.BroadcastAboutSelf(AbstractSiegeProtectorAI.CallTheKiller, call.Range),
                         Do.ArmTimer(0, call.Period), .. pullActions])
                    : AiPattern.Branch(7, "start the chain that reaches the call", When.Always,
                        [Do.ArmTimer(0, call.First), .. pullActions])),

            OnBattleTimer = AiPattern.Of(
                AiPattern.Branch(7, "call the killer to me", [When.Timer(0)],
                    Do.BroadcastAboutSelf(AbstractSiegeProtectorAI.CallTheKiller, call.Range),
                    Do.ArmTimer(0, call.Period))),
        };
    });
}
