// <auto-generated>
//     Generated by tools/client-extract/emit_tiamat_beacons_table.py from out/tiamat_beacons.tsv.
//     Do not edit by hand; edit the extractor and re-run.
// </auto-generated>
#nullable enable
using Aion.GameServer.Ai.Pattern;

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// What each Tiamat breath beacon puts on the ground when its timer fires: 65 placements across
/// 15 beacons.
/// </summary>
/// <remarks>
/// The second half of a two-step telegraph. The rotation places the beacon a raid runs out of; the
/// beacon then waits 2000ms and spawns the damage npcs along the line it marked. This port had the
/// first half only, so every breath in the encounter landed with the warning and none of the damage.
/// <para>
/// The coordinates are absolute in retail (<c>SPAWN_LOCATION_ABSOLUTE</c>) and are carried verbatim
/// rather than derived from the beacon's position. A middle beacon lays eleven in a line and lives two
/// seconds; the left and right ones lay a single wider hit and live three.
/// </para>
/// </remarks>
internal static class TiamatBeacons
{
    /// <summary>One beacon's answer: the damage npc, how long it lives, and where it lands.</summary>
    internal readonly record struct Breath(int DamageNpc, int LiveSeconds, int DelayMillis,
        bool AtTheBeacon, SpawnSpot[] Spots);

    /// <summary>Every beacon, by npc id.</summary>
    internal static readonly IReadOnlyDictionary<int, Breath> ByBeacon = new Dictionary<int, Breath>
    {
        [283155] = new Breath(283055, 2, 2000, false, [new SpawnSpot(445.0f, 550.7f, 417.4f)]),  // IDTiamat_Breath_Beacon1
        [283156] = new Breath(283068, 2, 2000, false, [new SpawnSpot(457.8f, 514.7f, 417.4f), new SpawnSpot(462.3f, 514.6f, 417.4f), new SpawnSpot(466.6f, 514.6f, 417.4f), new SpawnSpot(469.7f, 514.5f, 417.4f), new SpawnSpot(473.6f, 514.5f, 417.4f), new SpawnSpot(475.8f, 514.4f, 417.4f), new SpawnSpot(479.3f, 514.4f, 417.4f), new SpawnSpot(482.7f, 514.3f, 417.4f), new SpawnSpot(485.2f, 514.3f, 417.4f), new SpawnSpot(488.1f, 514.3f, 417.4f), new SpawnSpot(491.2f, 514.2f, 417.4f)]),  // IDTiamat_Breath_Beacon2
        [283157] = new Breath(283069, 2, 2000, false, [new SpawnSpot(454.1f, 474.9f, 417.4f)]),  // IDTiamat_Breath_Beacon3
        [283234] = new Breath(283235, 3, 2000, true, []),  // IDTiamat_Tiamat_BeaconL4s
        [283236] = new Breath(283237, 3, 2000, true, []),  // IDTiamat_Tiamat_BeaconL8s
        [283238] = new Breath(283239, 2, 2000, false, [new SpawnSpot(457.8f, 514.7f, 417.4f), new SpawnSpot(462.3f, 514.6f, 417.4f), new SpawnSpot(466.6f, 514.6f, 417.4f), new SpawnSpot(469.7f, 514.5f, 417.4f), new SpawnSpot(473.6f, 514.5f, 417.4f), new SpawnSpot(475.8f, 514.4f, 417.4f), new SpawnSpot(479.3f, 514.4f, 417.4f), new SpawnSpot(482.7f, 514.3f, 417.4f), new SpawnSpot(485.2f, 514.3f, 417.4f), new SpawnSpot(488.1f, 514.3f, 417.4f), new SpawnSpot(491.2f, 514.2f, 417.4f)]),  // IDTiamat_Tiamat_BeaconM4s
        [283240] = new Breath(283241, 2, 2000, false, [new SpawnSpot(457.8f, 514.7f, 417.4f), new SpawnSpot(462.3f, 514.6f, 417.4f), new SpawnSpot(466.6f, 514.6f, 417.4f), new SpawnSpot(469.7f, 514.5f, 417.4f), new SpawnSpot(473.6f, 514.5f, 417.4f), new SpawnSpot(475.8f, 514.4f, 417.4f), new SpawnSpot(479.3f, 514.4f, 417.4f), new SpawnSpot(482.7f, 514.3f, 417.4f), new SpawnSpot(485.2f, 514.3f, 417.4f), new SpawnSpot(488.1f, 514.3f, 417.4f), new SpawnSpot(491.2f, 514.2f, 417.4f)]),  // IDTiamat_Tiamat_BeaconM8s
        [283242] = new Breath(283243, 3, 2000, true, []),  // IDTiamat_Tiamat_BeaconR4s
        [283244] = new Breath(283245, 3, 2000, true, []),  // IDTiamat_Tiamat_BeaconR8s
        [856112] = new Breath(856113, 3, 2000, true, []),  // IDTiamat_Hard_BeaconL4s
        [856114] = new Breath(856115, 3, 2000, true, []),  // IDTiamat_Hard_BeaconL8s
        [856116] = new Breath(856117, 2, 2000, false, [new SpawnSpot(457.8f, 514.7f, 417.4f), new SpawnSpot(462.3f, 514.6f, 417.4f), new SpawnSpot(466.6f, 514.6f, 417.4f), new SpawnSpot(469.7f, 514.5f, 417.4f), new SpawnSpot(473.6f, 514.5f, 417.4f), new SpawnSpot(475.8f, 514.4f, 417.4f), new SpawnSpot(479.3f, 514.4f, 417.4f), new SpawnSpot(482.7f, 514.3f, 417.4f), new SpawnSpot(485.2f, 514.3f, 417.4f), new SpawnSpot(488.1f, 514.3f, 417.4f), new SpawnSpot(491.2f, 514.2f, 417.4f)]),  // IDTiamat_Hard_BeaconM4s
        [856118] = new Breath(856119, 2, 2000, false, [new SpawnSpot(457.8f, 514.7f, 417.4f), new SpawnSpot(462.3f, 514.6f, 417.4f), new SpawnSpot(466.6f, 514.6f, 417.4f), new SpawnSpot(469.7f, 514.5f, 417.4f), new SpawnSpot(473.6f, 514.5f, 417.4f), new SpawnSpot(475.8f, 514.4f, 417.4f), new SpawnSpot(479.3f, 514.4f, 417.4f), new SpawnSpot(482.7f, 514.3f, 417.4f), new SpawnSpot(485.2f, 514.3f, 417.4f), new SpawnSpot(488.1f, 514.3f, 417.4f), new SpawnSpot(491.2f, 514.2f, 417.4f)]),  // IDTiamat_Hard_BeaconM8s
        [856120] = new Breath(856121, 3, 2000, true, []),  // IDTiamat_Hard_BeaconR4s
        [856122] = new Breath(856123, 3, 2000, true, []),  // IDTiamat_Hard_BeaconR8s
    };

    /// <summary>Retail's own spawn group for these, so the boss can clear them.</summary>
    internal const int Placed = 1;

    /// <summary>
    /// The rung a beacon runs when it lands, or empty for an npc that is not one.
    /// </summary>
    internal static PatternBranch[] WakeRungFor(int npcId)
        => ByBeacon.TryGetValue(npcId, out Breath breath)
            ? [AiPattern.Branch(2, "landed -- start the count", When.Always,
                Do.SetIdleTimer(breath.DelayMillis))]
            : [];

    /// <summary>
    /// The rung that puts the damage down, or empty for an npc that is not a beacon.
    /// </summary>
    internal static PatternBranch[] BreathRungFor(int npcId)
        => ByBeacon.TryGetValue(npcId, out Breath breath)
            ? [AiPattern.Branch(1, "the breath lands", When.Always,
                breath.AtTheBeacon
                    // SPAWN_LOCATION_MY_POINT: the left and right breaths land on the marker itself,
                    // and their blocks carry no coordinates at all.
                    ? Do.SpawnOffset(breath.DamageNpc, Placed, 0f, 0f, breath.LiveSeconds)
                    : Do.SpawnAt(breath.DamageNpc, Placed, breath.LiveSeconds, breath.Spots))]
            : [];
}
