// <auto-generated>
//     Generated by tools/client-extract/emit_vritra_table.py from the retail AI patterns.
//     Do not edit by hand: re-run the extractor instead. See docs/retail-ai-fidelity.md.
// </auto-generated>

namespace Aion.GameServer.Handlers.AI;

/// <summary>
/// What each Runatorium Vritra caller puts on the floor.
/// </summary>
/// <remarks>
/// Read out of the retail <c>BIDRuneWP_Main_CallVritra*</c> patterns — 52 spawns across
/// 8 controllers. The options are in retail's evaluation order: highest priority first and,
/// within a priority, document order. Evaluation stops at the first option whose roll passes, so a
/// cascade of ten twenty-percent branches is a weighted pick, not ten independent rolls, and the
/// unguarded branch beneath them is the fallback that makes exactly one trooper appear every time.
/// </remarks>
internal static class VritraCallers
{
    /// <summary>One spawn: who, how many, and where.</summary>
    internal readonly record struct Placement(int NpcId, int Count, float X, float Y, float Z);

    /// <summary>One branch of the cascade.</summary>
    /// <param name="Chance">Percent, or 100 for the unguarded fallback.</param>
    internal readonly record struct Option(int Chance, Placement[] Spawns);

    internal static readonly IReadOnlyDictionary<int, Option[]> ByCaller = new Dictionary<int, Option[]>
    {
        // BIDRuneWP_Main_CallVritra02
        [284675] = [new Option(20, [new Placement(231097, 1, 150.03f, 145.5f, 125.2f)]), new Option(20, [new Placement(231096, 1, 150.03f, 145.5f, 125.2f)]), new Option(20, [new Placement(231098, 1, 150.03f, 145.5f, 125.2f)]), new Option(20, [new Placement(233288, 1, 150.03f, 145.5f, 125.2f)]), new Option(50, [new Placement(233289, 1, 150.03f, 145.5f, 125.2f)]), new Option(10, [new Placement(233292, 1, 150.03f, 145.5f, 125.2f)]), new Option(10, [new Placement(233294, 1, 150.03f, 145.5f, 125.2f)]), new Option(10, [new Placement(233295, 1, 150.03f, 145.5f, 125.2f)]), new Option(10, [new Placement(233296, 1, 150.03f, 145.5f, 125.2f)]), new Option(100, [new Placement(233293, 1, 150.03f, 145.5f, 125.2f)])],
        // BIDRuneWP_Main_CallVritra04
        [284676] = [new Option(20, [new Placement(231097, 1, 150.03f, 145.5f, 125.2f)]), new Option(20, [new Placement(231096, 1, 150.03f, 145.5f, 125.2f)]), new Option(20, [new Placement(231098, 1, 150.03f, 145.5f, 125.2f)]), new Option(20, [new Placement(233288, 1, 150.03f, 145.5f, 125.2f)]), new Option(50, [new Placement(233289, 1, 150.03f, 145.5f, 125.2f)]), new Option(10, [new Placement(233292, 1, 150.03f, 145.5f, 125.2f)]), new Option(10, [new Placement(233294, 1, 150.03f, 145.5f, 125.2f)]), new Option(10, [new Placement(233295, 1, 150.03f, 145.5f, 125.2f)]), new Option(10, [new Placement(233296, 1, 150.03f, 145.5f, 125.2f)]), new Option(100, [new Placement(233293, 1, 150.03f, 145.5f, 125.2f)])],
        // BIDRuneWP_Main_CallVritra06
        [284677] = [new Option(100, [new Placement(231096, 1, 150.03f, 145.5f, 125.2f), new Placement(233294, 1, 150.03f, 145.5f, 125.2f), new Placement(233296, 1, 150.03f, 140.5f, 125.2f)])],
        // BIDRuneWP_Main_CallVritra10
        [284678] = [new Option(100, [new Placement(231096, 1, 150.03f, 145.5f, 125.2f), new Placement(233294, 1, 150.03f, 145.5f, 125.2f), new Placement(233295, 1, 150.03f, 140.5f, 125.2f)])],
        // BIDRuneWP_Main_CallVritra02B
        [284679] = [new Option(20, [new Placement(231100, 1, 108.07f, 128.86f, 124.76f)]), new Option(20, [new Placement(231099, 1, 108.07f, 128.86f, 124.76f)]), new Option(20, [new Placement(231101, 1, 108.07f, 128.86f, 124.76f)]), new Option(20, [new Placement(233290, 1, 108.07f, 128.86f, 124.76f)]), new Option(50, [new Placement(233291, 1, 108.07f, 128.86f, 124.76f)]), new Option(10, [new Placement(233297, 1, 108.07f, 128.86f, 124.76f)]), new Option(10, [new Placement(233299, 1, 108.07f, 128.86f, 124.76f)]), new Option(10, [new Placement(233300, 1, 108.07f, 128.86f, 124.76f)]), new Option(10, [new Placement(233301, 1, 108.07f, 128.86f, 124.76f)]), new Option(100, [new Placement(233298, 1, 108.07f, 128.86f, 124.76f)])],
        // BIDRuneWP_Main_CallVritra04B
        [284680] = [new Option(20, [new Placement(231100, 1, 108.07f, 128.86f, 124.76f)]), new Option(20, [new Placement(231099, 1, 108.07f, 128.86f, 124.76f)]), new Option(20, [new Placement(231101, 1, 108.07f, 128.86f, 124.76f)]), new Option(20, [new Placement(233290, 1, 108.07f, 128.86f, 124.76f)]), new Option(50, [new Placement(233291, 1, 108.07f, 128.86f, 124.76f)]), new Option(10, [new Placement(233297, 1, 108.07f, 128.86f, 124.76f)]), new Option(10, [new Placement(233299, 1, 108.07f, 128.86f, 124.76f)]), new Option(10, [new Placement(233300, 1, 108.07f, 128.86f, 124.76f)]), new Option(10, [new Placement(233301, 1, 108.07f, 128.86f, 124.76f)]), new Option(100, [new Placement(233298, 1, 108.07f, 128.86f, 124.76f)])],
        // BIDRuneWP_Main_CallVritra06B
        [284681] = [new Option(100, [new Placement(231099, 1, 108.07f, 128.86f, 124.76f), new Placement(233299, 1, 108.07f, 128.86f, 124.76f), new Placement(233301, 1, 108.07f, 128.86f, 124.76f)])],
        // BIDRuneWP_Main_CallVritra10B
        [284682] = [new Option(100, [new Placement(231099, 1, 108.07f, 128.86f, 124.76f), new Placement(233299, 1, 108.07f, 128.86f, 124.76f), new Placement(233300, 1, 108.07f, 128.86f, 124.76f)])],
    };
}
